input-output-hk/cardano-js-sdk

.eslintrc.js
.github/PULL_REQUEST_TEMPLATE.md
.husky/commit-msg
commitlint.config.js
package.json
packages/cardano-graphql-provider/.gitignore
packages/cardano-graphql-provider/README.md
packages/cardano-graphql-provider/package.json
packages/cardano-graphql-provider/src/.eslintrc.js
packages/cardano-graphql-provider/src/cardanoGraphqlProvider.ts
packages/cardano-graphql-provider/src/index.ts
packages/cardano-graphql-provider/src/tsconfig.json
packages/cardano-graphql-provider/test/.eslintrc.js
packages/cardano-graphql-provider/test/cardanoGraphqlProvider.test.ts
packages/cardano-graphql-provider/test/jest.config.js
packages/cardano-graphql-provider/test/tsconfig.json
packages/core/package.json
packages/core/src/Provider/CardanoProvider.ts
packages/core/src/Provider/Provider.ts
packages/core/src/Provider/index.ts
packages/core/src/index.ts
yarn.lock

resolves #68 
Create an new package/SDK which forms as an abstraction above [cardano-graphql](https://github.com/input-output-hk/cardano-graphql).
N/A

feature(graphql-provider): create cardano-graphql-provider package

---

.eslintrc.js
.github/workflows/post_integration.yml
.gitignore
README.md
package.json
packages/cardano-graphql-provider/package.json
packages/cardano-graphql-provider/src/cardanoGraphqlProvider.ts
packages/cardano-graphql-provider/src/index.ts
packages/core/src/Provider/CardanoProvider.ts
packages/golden-test-generator/test/tsconfig.json
prototype/src/tsconfig.json
typedoc.json
yarn.lock

- docs, typedoc
This PR adds a script `yarn docs` which will auto-generate documentation with typedoc.
N/A

chore: auto-generate docs with typedoc

---

.eslintrc.js
README.md
packages/blockfrost/.gitignore
packages/blockfrost/README.md
packages/blockfrost/package.json
packages/blockfrost/src/.eslintrc.js
packages/blockfrost/src/blockfrostProvider.ts
packages/blockfrost/src/index.ts
packages/blockfrost/src/tsconfig.json
packages/blockfrost/src/utils.ts
packages/blockfrost/test/.eslintrc.js
packages/blockfrost/test/blockfrostProvider.test.ts
packages/blockfrost/test/jest.config.js
packages/blockfrost/test/tsconfig.json
packages/core/src/Provider/CardanoProvider.ts
yarn.lock

- [blockfrost](https://blockfrost.io/)
This PR creates a new package @cardano-sdk/blockfrost with a provider that can connect to the blockfrost service.

feat(blockfrost): create new provider called blockfrost

---

.eslintrc.js
README.md
package.json
packages/blockfrost/package.json
packages/cip30/.gitignore
packages/cip30/README.md
packages/cip30/package.json
packages/cip30/src/.eslintrc.js
packages/cip30/src/Wallet/Wallet.ts
packages/cip30/src/Wallet/WalletApi.ts
packages/cip30/src/Wallet/WalletPublic.ts
packages/cip30/src/Wallet/index.ts
packages/cip30/src/dataTypes.ts
packages/cip30/src/errors/ApiError.ts
packages/cip30/src/errors/DataSignError.ts
packages/cip30/src/errors/PaginateError.ts
packages/cip30/src/errors/TxSendError.ts
packages/cip30/src/errors/TxSignError.ts
packages/cip30/src/errors/index.ts
packages/cip30/src/index.ts
packages/cip30/src/tsconfig.json
packages/cip30/test/.eslintrc.js
packages/cip30/test/Wallet.test.ts
packages/cip30/test/index.d.ts
packages/cip30/test/jest.config.js
packages/cip30/test/tsconfig.json
packages/core/package.json
packages/golden-test-generator/package.json
yarn.lock

- [Dapp Connector CIP-30](https://github.com/cardano-foundation/CIPs/blob/b473884c9d208ed085414fb51fb339d09f4443e2/CIP-DappConnector/CIP-dapp-connector.md)
This PR creates a cip30 package that provides a `Wallet` class and TypeScript definitions for the dApp Connector as specified in CIP-30.

feat(cip-30): create cip30 package

---

packages/wallet/.gitignore
packages/wallet/README.md
packages/wallet/package.json
packages/wallet/src/tsconfig.json
packages/wallet/test/.eslintrc.js
packages/wallet/test/jest.config.js
packages/wallet/test/tsconfig.json

Upcoming wallet features are to be stored in a new package.
Sets up the package to keep the feature PRs well scoped.

chore(wallet): package setup

---

packages/cip30/package.json
packages/cip30/src/BrowserExtension/handleMessages.ts
packages/cip30/src/BrowserExtension/index.ts
packages/cip30/src/BrowserExtension/sendMessage.ts
packages/cip30/src/BrowserExtension/types.ts
packages/cip30/src/BrowserExtension/uiWallet.ts
packages/cip30/src/index.ts
yarn.lock

For the [Dapp Connector CIP-30](https://github.com/cardano-foundation/CIPs/blob/b473884c9d208ed085414fb51fb339d09f4443e2/CIP-DappConnector/CIP-dapp-connector.md) we will need a way to communicate between a webpage and the browser extension.
Create a Messaging interface to describe the API to communicate between the webpage and browser extension.

feat(cip30): create Messaging interface

---

packages/blockfrost/src/BlockfrostToOgmios.ts
packages/blockfrost/test/blockfrostProvider.test.ts
packages/cardano-graphql-db-sync/src/CardanoGraphqlToOgmios.ts
packages/cardano-graphql-db-sync/src/cardanoGraphqlDbSyncProvider.ts
packages/cardano-graphql-db-sync/test/cardanoGraphqlDbSyncProvider.test.ts
packages/core/src/Provider/CardanoProvider.ts

This parameter is required for input selection
Adds the property to the narrowed type and it's implementations.

feature: add maxTxSize to `ProtocolParametersRequiredByWallet`

---

packages/blockfrost/src/BlockfrostToOgmios.ts
packages/blockfrost/src/blockfrostProvider.ts
packages/blockfrost/test/blockfrostProvider.test.ts
packages/cardano-graphql-db-sync/src/CardanoGraphqlToOgmios.ts
packages/cardano-graphql-db-sync/src/cardanoGraphqlDbSyncProvider.ts
packages/cardano-graphql-db-sync/test/cardanoGraphqlDbSyncProvider.test.ts
packages/core/src/Provider/CardanoProvider.ts

The tip is needed to determine TTL rules during transaction construction.
- Add `ledgerTip` to the `Provider` interface
- Extend the two implementations.

Feature: `Provider.ledgerTip`

---

packages/wallet/src/KeyManagement/InMemoryKeyAgent.ts
packages/wallet/test/KeyManagement/InMemoryKeyAgent.test.ts

Add support for 2nd-factor mnemonic encryption passphrase

feat(wallet): 2nd-factor mnemonic encryption

---

packages/blockfrost/src/BlockfrostToCore.ts
packages/blockfrost/src/blockfrostWalletProvider.ts
packages/blockfrost/test/e2e/queryTransactions.test.ts

Fixed issue with collaterals in blockfrost

fix(blockfrost): added e2e test and fix for collaterals

---

packages/wallet/test/e2e/SingleAddressWallet/nft.test.ts

test(wallet): added e2e test for cip-25

---

packages/blockfrost/src/blockfrostWalletProvider.ts
packages/blockfrost/test/e2e/queryTransactions.test.ts

Added e2e tests for blockfrostWalletProvider

test(blockfrost): added e2e tests

---

packages/core/test/CSL/coreToCsl.test.ts

Added a few negative core tests for txMetadata

test: core txMetadata

---

packages/core/src/CSL/coreToCsl.ts
packages/core/src/errors.ts
packages/core/test/CSL/coreToCsl.test.ts

fix(core): throw serialization error for invalid metadata fields

---

packages/cip30/package.json

Closes #194
Remove the unused dependency

fix(cip30): remove dangling dependency

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml

This adds issue forms to the repo. See my fork master branch for an demo.

chore(issues): add issue forms

---

packages/ogmios/src/ogmiosTxSubmitProvider.ts

Fix `Ogmios` TS errors
- `ogmiosTxSubmitProvider` - add type to try/catch to fix ts error

fix(ogmios): fix ogmios ts errors

---

packages/ogmios/test/ogmiosTxSubmitProvider.test.ts

Fix `Ogmios` failing test
- `ogmiosTxSubmitProvider.test` - add type to try/catch to fix test failure

fix(ogmios): fix failing tests

---

packages/core/src/Cardano/types/TxSubmissionErrors.ts
packages/core/test/Cardano/types/TxSubmissionErrors.test.ts

Fixed mapping for core errors to Ogmios.

fix(core): tx error mapping fix

---

packages/wallet/package.json
packages/wallet/src/KeyManagement/util/mapHardwareSigningData.ts
packages/wallet/test/e2e/config.ts
yarn.lock

We need to update `ledgerjs-hw-app-cardano` to the latest published version `5.0.0.`. Update has few breaking changes and this PR will cover them.
This task is for updating `cardano-js-sdk's` Ledger support implementation with respect to the breaking changes in the `ledgerjs-hw-app-cardano` package.
`ledgerjs-hw-app-cardano` updated to version `5.0.0.`

chore(wallet): LedgerJS Breaking Changes

---

packages/wallet/package.json
packages/wallet/src/KeyManagement/LedgerKeyAgent.ts
packages/wallet/src/KeyManagement/TrezorKeyAgent.ts
packages/wallet/src/KeyManagement/index.ts
packages/wallet/src/KeyManagement/restoreKeyAgent.ts
packages/wallet/src/KeyManagement/types.ts
packages/wallet/src/KeyManagement/util/cachedGetPassword.ts
packages/wallet/test/KeyManagement/restoreKeyAgent.test.ts
packages/wallet/test/hardware/TrezorKeyAgent.integration.test.ts
packages/wallet/test/hardware/TrezorKeyAgent.test.ts
yarn.lock

SDK needs to be able to support the hardware devices / wallets. TrezorKeyAgent is responsible for communication with the Trezor device model.
Implement a KeyAgent to support the Trezor hardware devices
- TrezorKeyAgent added for handling Trezor device connection / communication.
- Web and Node based communication with Trezor devices via `trezor-connect` package

feat(wallet): Trezor Key Agent

---

packages/cardano-services-client/src/tsconfig.json
packages/cardano-services/test/tsconfig.json
packages/rabbitmq/src/tsconfig.json
packages/rabbitmq/test/tsconfig.json
packages/util-dev/test/tsconfig.json
packages/web-extension/src/tsconfig.json
packages/web-extension/test/tsconfig.json

I noticed there were a few issues with the tsconfig project references.
See individual commits.
n.a.

Chore: Correct and cleanup tsconfig project references

---

packages/wallet/test/e2e/SingleAddressWallet/nft.test.ts

fix(test): updated nft.test.ts

---

packages/cardano-services/src/NetworkInfo/openApi.json

Bug introduced in 5ee4c24ec7647957332c564130581a07b582f5ab

fix(cardano-services): updates NetworkInfo OpenAPI spec to align with refactor

---

packages/wallet/src/services/UtxoTracker.ts
packages/wallet/test/services/UtxoTracker.test.ts

It was keeping utxo in wallet's utxo set when a tx used an output from another chained tx, so there was sometimes a double-spend attempt.
See the commit

fix(wallet): consume chained tx outputs

---

packages/util/src/serializableObject.ts
packages/util/test/serializableObject.test.ts

#323 did not apply deserialization logic to Set items

fix(util): correctly deserialize Set items

---

packages/wallet/src/services/AssetsTracker.ts
packages/wallet/test/services/AssetsTracker.test.ts

`SingleAddressWallet.assets$` not removing assets when they're no longer available in `balance$`
Remove no longer available assets.

fix(wallet): remove assets no longer available in total balance

---

packages/cardano-services/src/Asset/AssetBuilder.ts
packages/cardano-services/src/Asset/DbSyncAssetProvider.ts
packages/cardano-services/src/Asset/DbSyncNftMetadataService.ts
packages/cardano-services/src/Asset/index.ts
packages/cardano-services/src/Asset/queries.ts
packages/cardano-services/src/Asset/types.ts
packages/cardano-services/test/Asset/AssetBuilder.test.ts
packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
packages/cardano-services/test/Asset/__snapshots__/AssetBuilder.test.ts.snap

We need to add an asset provider which use db-sync to fetch data.
Added `DbSyncAssetProvider`.

feat(cardano-services): add db-sync asset provider

---

packages/wallet/src/SingleAddressWallet.ts

Time settings is fetched once when epoch or time settings is
subscribed to, then refetched every time the epoch changes.
BREAKING CHANGE:
- currentEpochTracker creates an observable that emits a tuple of
TimeSettings and EpochInfo, instead of just EpochInfo.
TimeSettings is currently fetched every block, because it's using tipBlockHeight$ as trigger/source.
It can only change once per epoch, so we're doing some redundant fetching here.
Challenge here is that computing epoch # depends on knowing current TimeSettings, so it's a circular dependency.
`TimeSettingsManualTracker` wraps the provider and fetches once on subscription, while having a manual `refetch()` method to allow manual refetching.
`EpochTracker` subscribes to `TimeSettingsManualTracker`, thus triggering the initial …

fix(wallet)!: fetch time settings only when epoch changes (ADP-1682)

---

packages/cip30/src/WalletApi/types.ts
packages/wallet/src/cip30.ts
packages/wallet/test/integration/cip30mapping.test.ts
packages/wallet/test/integration/util.ts
packages/wallet/test/mocks/mockData.ts

Implements CIP 30 getCollateral method
Implements getCollateral method according to what is described [here](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030#apigetcollateralparams--amount-cborcoin--promisetransactionunspentoutput--null)

feat: implement cip30 getCollateral

---

packages/e2e/env/.env.cardano-services
packages/e2e/test/cardano-services/load/load.test.ts

Currently Cardano services load tests are broken on master.
Apply minor fixed to make the module compile again.
None

test(e2e): fixed cardano services load test compilation error

---

packages/e2e/test/wallet/SingleAddressWallet/nft.test.ts

I discovered a few issues in the NFT e2e test (currently not enforced in CI).
Please see each commit message

Test/e2e wallet NFT fix

---

packages/web-extension/src/messaging/BackgroundMessenger.ts

BackgroundMessenger re-emits all previously posted messages on every port connection. 
4b56cab7379f359b2d6dce41ff9533fdabdad4c4

fix(web-extension): do not re-emit all messages upon new port connection

---

packages/cardano-services/src/Http/HttpServer.ts
packages/cardano-services/test/Http/HttpServer.test.ts

The current metrics available are not enough for alerting and it is required that more suitable metrics be exposed.
We need to include a Prometheus gauge with the same object returned.
The exposed Prometheus Gauge interface allows values only with the type `number`.Due to that reason, we expose the server healthiness with the values 0 or 1 with Prometheus-scrapable format under `/metrics`
With a healthy state:
With an unhealthy state:
- add a health check to the `/metrics` endpoint using [Prometheus Gauge](https://github.com/siimon/prom-client#gauge)

feat: Enhance /metrics with custom HTTP server wide HealthCheckResponse

---

packages/cardano-services/src/Http/HttpServer.ts
packages/cardano-services/test/Http/HttpServer.test.ts

We need to increase the verbosity of our log
Now incoming requests are logged.

feat(cardano-services): adds log of incoming requests

---

packages/web-extension/src/messaging/BackgroundMessenger.ts

```ts
const obj1 = exposeApi(...);
const obj2 = exposeApi(...);
obj1.shutdown(); // this destroys ports for both 'obj1' and 'obj2'
```
87de6e126f9846f5a376bd120bd89c25c5cc985a
@lgobbi-atix confirmed that this fix resolves the error he was having

fix(web-extension): un-exposing an object in background process doesn't destroy the entire messaging

---

packages/wallet/src/TxBuilder/buildTx.ts
packages/wallet/src/TxBuilder/types.ts
packages/wallet/test/integration/buildTx.test.ts

ADP-2192
I want to know if the TxBuilder instance was already used to build and submit a transaction, so that I can avoid building and sending another transaction using the same instance, that still has the configurations (outputs/delegations/etc.) from the previously sent transaction.
TxBuilder `build()` method throws `TxBuilderDisabled` exception, if a transaction built with the same TxBuilder instance was already successfully submitted.
TxBuilder can be reenabled by calling it's `forceEnable()` method, to allow reusing it's configuration if needed.

feat(wallet): txBuilder disable after submit

---

packages/cardano-services/test/TxSubmit/rabbitmq/TxSubmitWorker.test.ts

The RabbitMQ parallel submission test now trusts on a 10ms delay (`setTimeout`) _to be sure_ the transactions are submitted in the correct order.
Any small change in the workload of the host running the test can be source of crosses between transaction submissions, making the test to fail.
Changed the submission delay mechanism trusting now on events governed by a `Promise`.

RabbitMQ parallel submission test increased robustness

---

packages/core/src/Asset/util/subtractTokenMaps.ts
packages/core/test/Asset/util/subtractTokenMaps.test.ts

Fix #442 
I called new Map(asset[0]) to create a copy of the input parameter.

fix(core): subtractTokenMaps shouldn't change first element

---

packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/types.ts
packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/mappers.test.ts
packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
packages/cardano-services/test/StakePool/__snapshots__/StakePoolHttpService.test.ts.snap
packages/core/src/Cardano/types/StakePool/StakePool.ts

Currently the backend is returning incorrect live stake and pool saturation values. 
Fix live state and saturation calculations to return the correct values.

fix(cardano-services): fixed an issue that was causing live stake and saturation values to be calculated incorrectly

---

packages/key-management/src/util/ownSignatureKeyPaths.ts
packages/wallet/src/SingleAddressWallet/prepareTx.ts
packages/wallet/test/SingleAddressWallet/methods.test.ts
packages/wallet/test/integration/buildTx.test.ts
packages/wallet/test/integration/txChainingBalance.test.ts

Working on #441 makes some bugs to issue. This fixes two of them.

Fixes: transactions with withdraw

---

packages/e2e/env/.env.local-network

fix(e2e): updated .env.local-network

---

packages/cardano-services/src/Http/HttpServer.ts

The team keeps having issues with figuring out what is deployed, so I added a little endpoint to help us with that
https://preprod-api.dev.lw.iog.io/meta

feat(cardano-services): Add '/meta' endpoint for deployment information

---

flake.nix

Unable to build/push image without this fix

fix(nix): fix not found /packages/cardano-services/node_modules

---

packages/cardano-services-client/src/HttpProvider.ts
packages/cardano-services-client/test/ChainHistoryProvider/chainHistoryProvider.test.ts
packages/cardano-services-client/test/HttpProvider.test.ts
packages/cardano-services-client/test/TxSubmitProvider/txSubmitHttpProvider.test.ts
packages/util/src/network.ts

Extended the list of handled connection errors.

fix(cardano-services): fixed http provider error handling

---

.github/workflows/continuous-integration-e2e.yaml
.github/workflows/nightly-e2e.yaml
packages/e2e/.env.example
packages/e2e/README.md
packages/e2e/src/environment.ts
packages/e2e/src/factories.ts
packages/e2e/src/scripts/mnemonic.ts
packages/e2e/test/local-network/register-pool.test.ts
packages/e2e/test/long-running/cache-invalidation.test.ts
packages/e2e/test/util.ts
packages/key-management/src/InMemoryKeyAgent.ts
packages/key-management/src/emip3.ts
packages/key-management/src/restoreKeyAgent.ts
packages/key-management/src/types.ts
packages/key-management/test/InMemoryKeyAgent.test.ts
packages/key-management/test/emip3.test.ts
packages/key-management/test/mocks/testKeyAgent.ts
packages/key-management/test/restoreKeyAgent.test.ts
packages/key-management/test/util/createAsyncKeyAgent.test.ts
packages/wallet/test/SingleAddressWallet/methods.test.ts

We need to replace "password" with "passphrase" for [BIP-39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) compliance.
Replace the relevant occurrences of `password` with `passphrase`.

refactor: replace occurrences of password with passphrase

---

packages/core/src/Cardano/types/Asset.ts

Webpack transforms this module to not have .default

fix(core): update @emurgo/cip14-js import style

---

packages/cardano-services/test/StakePool/HttpStakePoolMetadataService/HttpMetadataService.test.ts

Our unit tests are fetching `http://some_url/unfetchable` to check error handling.
The problem is that the error may depend on external system (the dns server) causing the error to be not deterministic: this can make the tests to fail.
Changed the URL to call into a mocked URL responding with error.

test(cardano-services): fixes a not deterministic error in tests

---

packages/cardano-services/src/Http/HttpServer.ts
packages/cardano-services/test/Http/HttpServer.test.ts

Added new metrics "node_sync_percentage" and "projection_sync_percentage".

feat: metric for sync status

---

packages/wallet/src/SingleAddressWallet/SingleAddressWallet.ts

Lace preprod network logs show some failed ValueNotConservedError transactions with consumed coins: 0.
Blocks produced more than 250 slots apart are rare (1 per epoch or less), given the current Preprod/Mainnet params of activeSlotCoeff: 0.05 and epochLength: 432000.
Updated the default, currently derived from the poll.maxInterval of 100 seconds, to be multiplied with 2.5 when used as reemit timeout.

fix(wallet): adjust time to wait before resubmit

---

packages/web-extension/src/messaging/runContentScriptMessageProxy.ts

errors from content script are not propagated 
ContentScriptMessageProxy will catch and return errors.

fix(web-extension): proxy error responses

---

packages/cardano-services/test/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.test.ts
packages/cardano-services/test/StakePool/TypeormStakePoolProvider/fitxures/TypeormFixtureBuilder.ts

Some unit tests sometimes fails...
- changed a single fixed sleep of 100ms into a loop... if the loop condition is never satisfied the tests will fail for timeout
- added some log lines to try to identify another source of flakiness

Test flakiness

---

packages/e2e/src/factories.ts
packages/e2e/test/util.ts
packages/e2e/test/wallet/PersonalWallet/handle.test.ts

E2E tests for minting and sending 'handles'.

test(e2e): handle discovery in PersonalWallet

---

packages/web-extension/src/messaging/remoteApi.ts

Change how the factory channel number is generated to avoid collisions.

refactor: use random id as channel number

---

packages/e2e/local-network/README.md
packages/e2e/local-network/scripts/mint-handles.sh
packages/e2e/local-network/scripts/mint-tokens.sh
packages/e2e/local-network/scripts/start.sh

Minting Ada handle on local test network

test(e2e): mint handles on localnet start

---

packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts

The error for asset not found is not so much verbose
Increased the error verbosity

feat(cardano-services): increase details in asset not found error

---

packages/cardano-services-client/src/HandleProvider/KoraLabsHandleProvider.ts
packages/cardano-services-client/test/util.ts

Mapped out background image and profile picture from koralab api response

feat: map out optional properties from Koralab api response

---

packages/cardano-services-client/src/HandleProvider/KoraLabsHandleProvider.ts
packages/cardano-services-client/test/util.ts

Handle undefined state for backgroundImage and profilePic on HandleResolution

fix: handle undefined state on HandleResolution

---

packages/projection-typeorm/test/operators/storeHandles.test.ts
packages/projection/src/operators/Mappers/util.ts
packages/projection/src/operators/Mappers/withHandles.ts
packages/projection/test/operators/Mappers/withHandles.test.ts
packages/util/src/errors.ts

Update the projection not return handles with unsupported characters

fix: unsupported character bug in handles projection

---

packages/cardano-services/package.json
packages/cardano-services/src/Program/services/ogmios.ts
packages/cardano-services/src/Program/services/postgres.ts
packages/cardano-services/src/Program/services/rabbitmq.ts
packages/cardano-services/src/Projection/ProjectionHttpService.ts
packages/cardano-services/test/Program/services/ogmios.test.ts
packages/cardano-services/test/Program/services/postgres.test.ts
packages/cardano-services/test/Program/services/rabbitmq.test.ts
packages/cardano-services/test/Program/services/util.ts
packages/cardano-services/test/Projection/ProjectionHttpService.test.ts
packages/e2e/test/long-running/projector-ogmios-connection.test.ts
packages/ogmios/test/mocks/mockOgmiosServer.ts
packages/ogmios/test/mocks/types.ts
packages/util/src/network.ts
packages/util/test/network.test.ts
yarn.lock

Follow-up to issues found in #778
See commits

fix: ogmios reconnection

---

packages/cardano-services/src/Program/programs/providerServer.ts
packages/cardano-services/src/Program/programs/types.ts
packages/cardano-services/src/Program/services/ogmios.ts
packages/cardano-services/src/cli.ts
packages/cardano-services/test/Program/programs/httpServer.test.ts
packages/cardano-services/test/cli.test.ts
packages/e2e/docker-compose.yml

The provider-server requires the configuration to choose between `KoraLabsHandleProvider` and `TypeOrmHandleProvider`
Added the required parameters to `cli.ts`.

LW-7345 add cli parameter to chose the handle provider

---

packages/e2e/local-network/scripts/mint-handles.sh
packages/e2e/local-network/scripts/mnemonic_keys.sh
packages/e2e/local-network/scripts/start.sh
packages/e2e/test/wallet/PersonalWallet/handle.test.ts

LW-7345 Change nft minting scripts to use keys from mnemonics

---

packages/e2e/local-network/scripts/mint-handles.sh
packages/e2e/local-network/scripts/mint-tokens.sh
packages/e2e/local-network/scripts/setup-wallets.sh
packages/e2e/local-network/scripts/start.sh

Added minting CIP-68(222) handle during local network startup.

test(e2e): mint cip-68(222) handle

---

packages/hardware-trezor/src/transformers/index.ts
packages/hardware-trezor/src/transformers/keyPaths.ts
packages/hardware-trezor/src/transformers/tx.ts
packages/hardware-trezor/src/transformers/withdrawals.ts
packages/hardware-trezor/test/testData.ts
packages/hardware-trezor/test/transformers/keyPaths.test.ts
packages/hardware-trezor/test/transformers/withdrawals.test.ts

This PR introduces the implementation of mapping Cardano tx withdrawals to Trezor withdrawals.

chore(hardware-trezor): trezor tx withdrawals mapper

---

packages/hardware-trezor/src/TrezorKeyAgent.ts
packages/hardware-trezor/src/transformers/tx.ts
packages/wallet/test/README.md

Implements misc simple tx sign mappers for the new trezor hw package (https://input-output.atlassian.net/browse/LW-6801)

LW-6801 miscellaneous mappers for trezor sdk implementation

---

packages/hardware-trezor/src/transformers/assets.ts
packages/hardware-trezor/src/transformers/tx.ts

This PR adds the mint bundle mapper for the new trezor package.

chore(hardware-trezor): add trezor mint bundle mapper

---

packages/cardano-services/test/cli.test.ts

Added typeorm stake pool provider cli test

Typeorm stake pool provider cli test

---

packages/projection/src/operators/Mappers/withNftMetadata.ts
packages/projection/test/operators/Mappers/withNftMetadata.test.ts

https://github.com/cardano-foundation/CIPs/pull/527

feat: project cip25 metadata only from positive quantity mint transactions

---

packages/wallet/src/PersonalWallet/PersonalWallet.ts
packages/wallet/test/PersonalWallet/methods.test.ts

Re-submitting transaction manually results in faulty state, as TransactionsTracker can't handle it.
LW-7873
babe6a5cbb834adafe90fa23714cc74822601eca

fix(wallet): make PersonalWallet.submitTx idempotent

---

packages/wallet/src/services/UtxoTracker.ts
packages/wallet/test/services/UtxoTracker.test.ts

Some bug in transactions tracker state machine or  backend utxo queries might result in duplicate utxo
Filter out the duplicates before emitting, but keep an error log message

feat(wallet): filter out duplicate utxo

---

.jira/config.yml

To effectively communicate the feature cycle across the team ...
... this PR maps GH Action environments to Jira environments c/o our GH - Jira integration (already set up).
None notable.
Works in tandem with https://github.com/input-output-hk/cardano-js-sdk/pull/864

ci: environment integration with jira

---

packages/tx-construction/src/output-validation/outputValidator.ts
packages/tx-construction/src/output-validation/types.ts
packages/tx-construction/src/tx-builder/OutputBuilder.ts
packages/tx-construction/src/tx-builder/types.ts
packages/tx-construction/test/output-validation/outputValidator.test.ts
packages/tx-construction/test/tx-builder/TxBuilder.test.ts

Added validation of asset quantity during tx construction

Negative or zero asset qty validation

---

.envrc
.gitignore

As now we are using `direnv` it could be nice to have the ability to set soma locally and personally defined variables.
Executed and _git-ignored_ a new `.envrc.local` file, so everybody can change it locally.
Removed also a file added by me sometime in the past by error.

chore: add support for local direnv cfg file

---

packages/e2e/test/k6/endpoints/stake-pool/search.test.js

K6 test for stake pool search endpoint

test(e2e): k6 stake pool search

---

packages/hardware-trezor/src/TrezorKeyAgent.ts

This PR fixes the Trezor transaction signing which was failing due to an invalid fee calculation.
Filter the Trezor signatures to those with the expected public keys (based on `ownSignatureKeyPaths`), so that the fees calculation (which is based on the number of signatures) is correct.
none

fix(hardware-trezor): trezor tx signing LW-6522

---

packages/cardano-services/test/cli.test.ts

Add a test for starting asset provider server with configuration in environment variables

test(cardano-services): add test for starting asset provider server with env vars

---

packages/ogmios/test/util.test.ts

Re-enable ogmios util tests to assert only the logic of the util itself

test(ogmios): mock ogmios in util test

---

packages/wallet/test/PersonalWallet/load.test.ts

A flaky tests requires to restart several times per day CI jobs.
Substituted two `delay`s with `Promise`s to try to make the test more stable

flaky test fix attempt

---

packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/util.ts
packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
packages/core/src/Cardano/util/computeImplicitCoin.ts
packages/core/test/Cardano/util/computeImplicitCoin.test.ts
packages/projection/src/operators/Mappers/certificates/withStakeKeyRegistrations.ts
packages/projection/src/operators/Mappers/certificates/withStakeKeys.ts
packages/wallet/src/services/DelegationTracker/DelegationTracker.ts
packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
packages/wallet/src/services/DelegationTracker/transactionCertificates.ts
packages/wallet/test/services/DelegationTracker/RewardAccounts.test.ts
packages/wallet/test/services/DelegationTracker/transactionCertificates.test.ts

Conway era introduced new certificates.
Implemented the new certificates in `ChainHistoryBuilder`.
Skipped the two tests files testing `ChainHistoryBuilder`.

 LW-8967 db sync chain history conway era certificates

---

packages/cardano-services-client/src/version.ts
packages/cardano-services-client/version.json
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
packages/cardano-services/src/ChainHistory/openApi.json

We need to add support for proposal procedures.
Added support to `DbSyncChainHistoryProvider` to provide proposal procedures in transactions history.

LW-8969 Proposal procedures

---

nix/cardano-services/deployments/pgboss-deployment.yaml

chore: fix pgboss worker SMASH_URL

---

nix/cardano-services/deployments/backend-deployment.yaml
nix/cardano-services/deployments/blockfrost-worker-deployment.yaml

chore: add blockfrost service

---

nix/cardano-services/deployments/backend-deployment.yaml
nix/cardano-services/deployments/blockfrost-worker-deployment.yaml

fix: duplicate USE_BLOCKFROST parameter

---

packages/core/src/Asset/NftMetadata/fromMetadatum.ts
packages/core/test/Asset/NftMetadata/fromMetadatum.test.ts

[CIP25](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0025) defines the name field as required, but some established projects (Cardano Crocs Club, Radioactive Crocs Club) do not follow the standard, relying just on the Asset name.
Modify SDK to handle NFTs (v1) without the name field, using asset_name when name not available
- fromMetadatum now uses asset_name as utf8 when name field is missing for CIP-25 V1

fix(core): fromMetadatum now uses asset_name as utf8 when name field is missing

---

packages/cardano-services/environments/.env.sanchonet
packages/cardano-services/environments/.schedule.sanchonet.json
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts

**db-sync** v3.0.0 introduced JSON encoded governance action proposals
Parsed and translated the governance action proposals from db-sync to our core types.

LW-9423 proposal procedures details

---

packages/cardano-services/test/Program/programs/httpServer.test.ts

With ogmios changes for Conway era some unit test was disabled.
In the end, just removing mock stuff related with ogmios was enough to re-enable the test.

test(cardano-services): re-enable http server unit tests

---

packages/cardano-services/package.json

While working on LW-9732 I noticed this typo.
Fixed the typo

LW-9732 fix cardano-submit-api parameters typo

---

.github/workflows/std.yml

[LW-9879](https://input-output.atlassian.net/browse/LW-9879)
A mini-follow up to #1119 
n/a
n/a
[LW-9879]: https://input-output.atlassian.net/browse/LW-9879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LW-9879] ci: comment with diffs for dev-preview on PRs to master

---

.github/workflows/std.yml

ci: fix discovery

---

packages/e2e/test/wallet/PersonalWallet/txChainHistory.test.ts
packages/projection-typeorm/test/createTypeormTipTracker.test.ts

A couple of flaky tests has a too high fail ratio.
Skipped them and tracked in dedicated tickets

test: skip flaky tests

---

.envrc
.github/workflows/std.yml

[Slack thread](https://input-output-rnd.slack.com/archives/C01S2DD5B0D/p1709725968964819?thread_ts=1709720209.694119&cid=C01S2DD5B0D)
n/a
n/a

fix: default to K8S_USER=eks-devs in .envrc

---

packages/e2e/test/web-extension/dapp-sdk/dapp-sdk.html
packages/e2e/test/web-extension/dapp-sdk/dapp-sdk.ts
packages/e2e/test/web-extension/dapp-sdk/features/connectLace.ts
packages/e2e/test/web-extension/dapp-sdk/features/sendCoins.ts
packages/e2e/test/web-extension/dapp-sdk/features/sendSeveralAssets.ts
packages/e2e/test/web-extension/dapp-sdk/utils.ts

As a dev I want to be able to check that I can successfully send assets in tx. 
Add the option to create a tx with several assets to send to an address on the dapp connector.
N/A

[LW-9974] build TX with assets

---

README.md

Adding instructions for manual deploy

docs: update README.md with instructions for manual deployment

---

.github/workflows/std.yml

[LW-10047](https://input-output.atlassian.net/browse/LW-10047)
See Jira ↑
n/a
n/a
[LW-10047]: https://input-output.atlassian.net/browse/LW-10047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LW-10047] chore: when diffing, update existing comments

---

.gitignore
flake.nix
nix/cardano-services/deployments/backend-ingress.nix
nix/cardano-services/deployments/blockfrost-worker-deployment.nix
nix/cardano-services/deployments/default.nix
packages/web-extension/README.md

Migrating dev-sanchonet from old to new clusters

chore: get sanchonet services ready for migration

---

.kube/us-east-2
nix/cardano-services/deployments/backend-ingress.nix
nix/cardano-services/deployments/backend.provider.nix
nix/cardano-services/deployments/default.nix
nix/local/envs.nix

Resolves https://github.com/input-output-hk/lace-ops/issues/82
After merge destroy us-east-1 deployments

chore: deploy live-{preview,preprod} to new cluster

---

.github/workflows/std.yml

[LW-10019](https://input-output.atlassian.net/browse/LW-10019)
Adding dev-sanchonet to CI
[LW-10019]: https://input-output.atlassian.net/browse/LW-10019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LW-10019] chore: set up sanchonet ci

---

packages/e2e/test/wallet/PersonalWallet/conwayTransactions.test.ts

We need to make the `PersonalWallet/conwayTransactions` more robust, sending the DRep Reg Cert only if non already registered as DRep.
Check the txs history to find relevant certificates in order to decide if sending or not the DRep Reg Cert.

LW-9898 conway era tx

---

nix/cardano-services/deployments/default.nix

chore: add live-{preview,preprod} v2 deployments

---

packages/tx-construction/src/tx-builder/TxBuilder.ts
packages/tx-construction/src/tx-builder/types.ts
packages/tx-construction/test/tx-builder/TxBuilder.test.ts
packages/web-extension/src/observableWallet/util.ts

Add setValidityInterval to txBuilder

[LW-10090] Add SetValidityInterval to txBuilder()

---

nix/cardano-services/deployments/default.nix

As per devs request adding NODE_ENV environment variable to live-* provider services

Pass node env

---

.github/workflows/std-release.yaml

Sorry guys, realized that I forgot to add this

ci: add staging-preprod to std-release.yaml workflow

---

nix/cardano-services/deployments/default.nix

https://input-output.atlassian.net/browse/LW-9965
Can someone deploy this to dev-preview and test it from a local machine? I am not sure how devs run the extension locally, if it is opened as a website - it should be good. If it is opened as extension, then it probably requires prefix but in that case i'd assume that it would have a custom hash in development mode as well

chore: add localhost as allowed origin to dev-*

---

packages/cardano-services/src/Http/HttpServer.ts
packages/cardano-services/src/Http/HttpService.ts
packages/cardano-services/src/util/provider.ts

We need to remove the user IP address from logs.
Removed the source IP address from HTTP handlers log lines.

LW-10159 Remove client ip address from logs

---

.github/workflows/std-release.yaml

[LW-10177](https://input-output.atlassian.net/browse/LW-10177)
Tweaks input-output-hk/cardano-js-sdk#1185 as per [Rhys' comment](https://input-output.atlassian.net/browse/LW-10177?focusedCommentId=272226).
[LW-10177]: https://input-output.atlassian.net/browse/LW-10177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ci: deploy staging-* only on demand

---

packages/cardano-services/src/Http/HttpService.ts

fix(cardano-services): emergency fix for lw-10209

---

nix/cardano-services/deployments/default.nix
nix/cardano-services/deployments/pg-boss-worker-deployment.nix

Goal is to let us update smash url  per environment

chore: split smash url per env

---

nix/cardano-services/deployments/default.nix

Sancho long url

---

nix/cardano-services/deployments/default.nix

Adding tracing-gc to dev-preview/preprod

chore: add dev-pre* tracing

---

nix/cardano-services/deployments/default.nix

Reverting live-preview@v1 removal since it is used by Midnight team

Add live preview v1

---

packages/cardano-services/src/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.ts
packages/cardano-services/src/StakePool/TypeormStakePoolProvider/util.ts
packages/cardano-services/test/StakePool/TypeormStakePoolProvider/util.test.ts
packages/cardano-services/test/cli.test.ts
packages/core/src/Provider/StakePoolProvider/types/StakePoolProvider.ts

After some refinement attempt we discovered we may need some more configurable options.
Added almost all `fuse.js` options as configurable

LW-10410 more configurable fuzzy stake pools search options

---

.kube/eu-central-1
nix/cardano-services/deployments/default.nix
nix/cardano-services/deployments/tf-outputs/lace-live-eu-central-1.json
nix/local/envs.nix

Add eu central live pre

---

README.md
nix/cardano-services/deployments/asset.nix
nix/cardano-services/deployments/backend-ingress.nix
nix/cardano-services/deployments/backend.provider.nix
nix/cardano-services/deployments/blockfrost-worker-deployment.nix
nix/cardano-services/deployments/default.nix
nix/cardano-services/deployments/handle.nix
nix/cardano-services/deployments/options.nix
nix/cardano-services/deployments/pg-boss-worker-deployment.nix
nix/cardano-services/deployments/stake-pool.nix

This partial path of [this PR](https://github.com/input-output-hk/cardano-js-sdk/pull/1235). Changes:
- Cleaner region/network management
- Configurable stakepool db
- Optional ingress
No diff throughout all environments

Deployment cleanup

---

nix/cardano-services/deployments/default.nix

Changes:
- [Cherry-picked commit](https://github.com/input-output-hk/cardano-js-sdk/pull/1235) which configures pg-boss-worker properly
- Added new live-mainnet@eu-central-1 deployment  (Not currently live until everything syncs. Current domain is tmp-live-mainnet.lw.iog.io)
@iccicci Are we okay with deploying pg-boss change to all environments?

New live mainnet eu central 1

---

packages/core/src/Cardano/types/Governance.ts
packages/hardware-ledger/src/LedgerKeyAgent.ts
packages/hardware-ledger/src/transformers/votingProcedures.ts
packages/hardware-ledger/src/transformers/withdrawals.ts
packages/hardware-ledger/test/testData.ts
packages/hardware-ledger/test/transformers/votingprocedures.test.ts
packages/hardware-ledger/test/transformers/withdrawals.test.ts
packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts

[JIRA Ticket](https://input-output.atlassian.net/browse/LW-10422)
Ledger: fix failing hw-ledger tests in the wallet package & add new tests due to upgrading to Ledgerjs v7.1.2
- fix the 2 failing hw-ledger tests in the wallet  package
- add missing tests in the wallet  package for new mappers related to governance “voting”
- use Transform interface in `votingProcedures` mapper
**_hardware-ledger package unit test:_**
**_wallet package unit test:_**
**QA Note:** After rebasing to the main branch we have new failing tests `conway-era`. AC from the ticket is covered and a follow-up ticket for new tests ( failing ) is created https://input-output.atlassian.net/browse/LW-10448

chore: votingProcedures improvements and tests

---

packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts

[Jira Ticket](https://input-output.atlassian.net/browse/LW-10448)
Ledger: Fix all 7 failing Conway-era tests that relate to the Cardano governance feature: https://github.com/input-output-hk/cardano-js-sdk/pull/1211

test(wallet): fix failing conway-era Ledger tests

---

nix/cardano-services/oci-images.nix

chore: test oci changes

---

nix/cardano-services/deployments/default.nix
nix/cardano-services/deployments/pg-boss-worker-deployment.nix
nix/cardano-services/deployments/stake-pool.nix

chore: point stakepool and pgboss services to stakepool-v2 database

---

.github/workflows/std.yml

[LW-10508](https://input-output.atlassian.net/browse/LW-10508)
A temporary fix (more like a test) before we get the proper one.
[LW-10508]: https://input-output.atlassian.net/browse/LW-10508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LW-10508] ci: temporarily restore `rev` in `/v1.0.0/meta`

---

.kube/eu-central-1
.kube/us-east-2
nix/cardano-services/deployments/default.nix

Promote eu central live pre envs

---

nix/local/envs.nix

Added `tmate` tool to `nix` configuration.

chore: add tmate

---

packages/cardano-services/src/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.ts
packages/cardano-services/test/StakePool/TypeormStakePoolProvider/util.test.ts
packages/cardano-services/test/cli.test.ts

[LW-10410] feat(cardano-services): implement new fuzzy search options

---

nix/cardano-services/deployments/default.nix

chore: enabled asset provider and projector in all environments

---

nix/cardano-services/deployments/default.nix

Deprecated legacy domains and added region specific domains

chore: deprecate long domains and add regional domains

---

nix/cardano-services/deployments/default.nix

Release/cardano services/0.28.x

---

nix/cardano-services/deployments/default.nix

Disabling asset provider as per @mchappell request

chore: disable asset-provider in dev-mainnet

---

nix/cardano-services/deployments/default.nix

Stakepool resync

---

nix/cardano-services/deployments/default.nix

chore: enable asset in dev-preview

---

justfile

Removed hardcoded eks-readonly context from justfile so it would work with other users

chore: remove eks-readonly hardcoding from justfile

---

nix/cardano-services/deployments/default.nix

chore: enable handle-provider in all envs, enable asset projector

---

nix/cardano-services/deployments/backend.provider.nix
nix/cardano-services/deployments/default.nix
nix/cardano-services/deployments/options.nix
nix/cardano-services/deployments/provider.resource.nix
nix/cardano-services/operables.nix
nix/cardano-services/packages.nix

This is a partner PR to [lace-ops/pull/142](https://github.com/input-output-hk/lace-ops/pull/142) which helps us set up the new core stack all of these services needs to connect to

Deploy local network

---

packages/e2e/local-network/scripts/start.sh
packages/e2e/local-network/sdk-ipc/.gitignore

Export generated configuration and genesis from `local-network`.

chore: dump local-network configuration

---

nix/cardano-services/deployments/default.nix

chore: upgrade live-preview

---

nix/cardano-services/deployments/chain-history.nix
nix/cardano-services/deployments/default.nix

chore: enable chain-history dev-pre*

---

nix/cardano-services/deployments/default.nix

chore: change live-preview@us-east-2 to use stakepoolv2 db

---

.github/workflows/std.yml
nix/cardano-services/deployments/default.nix

Remove dev-preprod-resync code from GH workflows and nix code

---

.github/workflows/std.yml

ci: fix .kube being not found

---

nix/cardano-services/deployments/default.nix

https://input-output.atlassian.net/browse/LW-10964
Enable typeORM aset provider (once deployed)

chore: [LW-10964] enable typeorm asset provider for dev environments

---

packages/web-extension/src/walletManager/SigningCoordinator/SigningCoordinator.ts
packages/web-extension/src/walletManager/SigningCoordinator/types.ts
packages/web-extension/src/walletManager/util.ts
packages/web-extension/test/walletManager/SigningCoordinator.test.ts

fix(web-extension): signing coordinator sign with 1854 purpose account

---

nix/cardano-services/deployments/backend.provider.nix
nix/cardano-services/deployments/default.nix

This changed was merged in with conway-era, we did this to get the local-network to work and is not meant for master

chore: remove backend s3 mount

---

packages/cardano-services/src/Asset/TypeOrmNftMetadataService.ts
packages/cardano-services/src/Asset/TypeormAssetProvider/TypeormAssetProvider.ts
packages/cardano-services/src/util/TypeormService/TypeormService.ts

Attempting to release again throws an error
it should be released in scope where it's created

fix: typeorm asset provider release query runner once

---

Dockerfile
packages/e2e/test/wallet_epoch_3/PersonalWallet/conwayTransactions.test.ts

Latest Docker versions give a lot of warnings due to this casing minor issue.
Fixed the casing.
Temporary skipped Conway era transactions e2e test to avoid its flakiness.

LW-11248 Fix Dockerfile casing

---

nix/cardano-services/deployments/default.nix

Release/cardano services/0.29.3

---

scripts/deployed-db.sh

feat: add staging env to the script to connect to deployed DBs

---

nix/cardano-services/deployments/default.nix
nix/cardano-services/deployments/wallet-api.nix

Add deployment for wallet-api service

chore: create wallet-api deploy

---

nix/cardano-services/deployments/default.nix

Increase default number of live-mainnet backend providers

chore: increase backend providers for mainnet

---

nix/cardano-services/deployments/default.nix

chore: alter deployment resource definitions

---

packages/cardano-services/src/Asset/TypeormAssetProvider/TypeormAssetProvider.ts
packages/cardano-services/src/Projection/migrations/1726479765002-nft-metadata-index.ts
packages/cardano-services/src/Projection/migrations/index.ts
packages/projection-typeorm/src/entity/NftMetadata.entity.ts

The `asset-projector` has some performances issues.
Added an index to reduce SQL queries weight.
Minor query refactoring to remove a `JOIN`.

LW-11521 be-v0.30.1

---

packages/cardano-services/src/Utxo/DbSyncUtxoProvider/mappers.ts
packages/cardano-services/src/Utxo/DbSyncUtxoProvider/types.ts
packages/core/src/Serialization/Update/Costmdls/CostModel.ts

Running sanchonet I discovered another couple of minor issues.
Please check commit details

LW-11572 V10 protocol fixes

---

packages/cardano-services/src/Handle/openApi.json

fix(cardano-services): incorrect OpenAPI title

---

.github/workflows/cardano-services.yaml
nix/cardano-services/deployments/default.nix

chore: move staging mainnet to dev cluster

---

packages/wallet/src/services/TransactionsTracker.ts
packages/wallet/test/services/TransactionsTracker.test.ts

There was a wrong assumption that transactions would return from the backend sorted by slot. However, this is not the case. We rely on transaction order for the new optimized algorithm, which operates under the assumption that transactions are sorted in ascending order.
After fetching all transactions, sort them by slot.

fix(wallet): transaction tracker now process transaction in chronological order

---

packages/wallet/src/services/TransactionsTracker.ts
packages/wallet/test/services/TransactionsTracker.test.ts

The transaction history should not contain any duplicate transactions. It will now make sure the transactions are sorted and de-duplicated.

fix(wallet): transaction tracker now de-duplicates transactions if needed

---

nix/cardano-services/deployments/asset.nix
nix/cardano-services/deployments/backend.provider.nix
nix/cardano-services/deployments/blockfrost-worker-deployment.nix
nix/cardano-services/deployments/chain-history.nix
nix/cardano-services/deployments/handle.nix
nix/cardano-services/deployments/pg-boss-worker-deployment.nix
nix/cardano-services/deployments/projector.resource.nix
nix/cardano-services/deployments/provider.resource.nix
nix/cardano-services/deployments/stake-pool.nix
nix/cardano-services/deployments/wallet-api.nix
nix/cardano-services/deployments/ws-server.deployment.nix

chore: remove tls

---

packages/wallet/src/Wallets/BaseWallet.ts

Limit tx build refetches of delegation info.

chore(wallet): refetch only if tip has changed

---

packages/cardano-services-client/src/ChainHistoryProvider/BlockfrostChainHistoryProvider.ts
packages/cardano-services-client/src/UtxoProvider/BlockfrostUtxoProvider.ts
packages/cardano-services-client/src/WebSocket.ts
packages/e2e/src/factories.ts
packages/e2e/test/artillery/wallet-restoration/WalletRestoration.ts
packages/e2e/test/web-extension/extension/background/cip30.ts
packages/ogmios/src/CardanoNode/OgmiosObservableCardanoNode/OgmiosObservableCardanoNode.ts
packages/ogmios/src/CardanoNode/queries.ts
packages/util/src/RunnableModule.ts
packages/util/test/RunnableModule.test.ts
packages/web-extension/src/walletManager/SigningCoordinator/SigningCoordinator.ts

This PR adjusts logger levels to ensure correct logging within the project. I modified the logging levels from `logger.info` to `logger.debug` where appropriate.

fix: adjust logger levels to ensure correct logging

---

nix/cardano-services/deployments/default.nix

@mirceahasegan request to add firefox extension origin
Not deployed anywhere yet

chore: add firefox extension origin to dev envs

---

.github/std-unexploded.yml
.github/workflows/std.yml

Upgrade failing aws-credentials to supported version.

chore: update known hosts and actions/aws-credentials vers

---

packages/core/src/Cardano/util/computeImplicitCoin.ts
packages/core/test/Cardano/util/computeImplicitCoin.test.ts

See [LW-12198](https://input-output.atlassian.net/browse/LW-12198)
Calculate withdrawals only for own reward accounts.
[LW-12198]: https://input-output.atlassian.net/browse/LW-12198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(core): withdrawal calculation in computeImplicitCoin [LW-12198]

---

packages/core/src/Provider/HandleProvider/types.ts

In Lace, we need to force the resolution of ADA handles bypassing the cache. The base type of the provider is defined here.
Added the `force` parameter the the resolution interface.

feat(core): add force parameter to handle resolution interface

---

packages/cardano-services/docker-compose.yml

Somewhere in time a port conflict was introduced which prevents running local instances of the real networks.
Resolved the ports conflict

chore: resolve docker compose ports conflict
