- packages/cardano-graphql-db-sync/src/cardanoGraphqlDbSyncProvider.ts
- packages/cardano-graphql-db-sync/src/utils.ts
- packages/cardano-graphql-db-sync/test/cardanoGraphqlDbSyncProvider.test.ts
- cardano-graphql-db-sync
This PR fixes the incorrect typescript types of the graphql responses and includes the related logic to map the response into the format inline with the `CardanoProvider` interface.
> fix(cardano-graphql-db-sync): typescript types of graphql responses

- packages/blockfrost/src/blockfrostProvider.ts
- packages/blockfrost/test/blockfrostProvider.test.ts
- packages/cardano-graphql-db-sync/src/cardanoGraphqlDbSyncProvider.ts
- packages/cardano-graphql-db-sync/test/cardanoGraphqlDbSyncProvider.test.ts
- packages/core/src/Provider/CardanoProvider.ts
The light wallet will need to fetch delegations & rewards & they are usually fetched together with uxtos.
Modify `Provider.utxo` to `Provider.utxoDelegationAndRewards` to return delegations & rewards along side utxos.
- `Provider.utxo` no longer exists.
> feat(core|blockfrost): modify utxo method on provider to return delegations & rewards

- packages/cardano-serialization-lib/src/index.ts
- packages/cardano-serialization-lib/src/loadCardanoSerializationLib.ts
`package.json` of `@emurgo/cardano-serialization-lib-nodejs` doesn't have a `browser` field, which means it will be bundled for browser builds when used with webpack.
Dynamic import
Re-export OgmiosToCardanoWasm from cardano-serialization-lib package main
> chore(cardano-serialization-lib): dynamic import for @emurgo/cardano-serialization-lib-nodejs

- packages/blockfrost/src/blockfrostProvider.ts
- packages/cardano-graphql-db-sync/src/cardanoGraphqlDbSyncProvider.ts
- packages/cardano-serialization-lib/package.json
- packages/core/package.json
- packages/core/src/Cardano/ChainSettings.ts
- packages/core/src/Cardano/index.ts
- packages/core/src/Provider/CardanoProvider.ts
- packages/core/src/index.ts
- packages/in-memory-key-manager/.gitignore
- packages/in-memory-key-manager/README.md
- packages/in-memory-key-manager/package.json
- packages/in-memory-key-manager/src/.eslintrc.js
- packages/in-memory-key-manager/src/InMemoryKey.ts
- packages/in-memory-key-manager/src/index.ts
- packages/in-memory-key-manager/src/tsconfig.json
- packages/in-memory-key-manager/src/util.ts
- packages/in-memory-key-manager/test/.eslintrc.js
- packages/in-memory-key-manager/test/InMemoryKeyManager.test.ts
- packages/in-memory-key-manager/test/jest.config.js
- packages/in-memory-key-manager/test/tsconfig.json
- packages/wallet/package.json
- packages/wallet/src/Address.ts
- packages/wallet/src/KeyManagement/KeyManager.ts
- packages/wallet/src/KeyManagement/errors/InvalidMnemonic.ts
- packages/wallet/src/KeyManagement/errors/index.ts
- packages/wallet/src/KeyManagement/index.ts
- packages/wallet/src/index.ts
- yarn.lock
- ADP-1103
This PR does two things:
1. Hoist the KeyManager interface and custom errors from the prototype into the core package.
2. Create a new package @cardano-sdk/in-memory-key-manager and hoist the InMemoryKeyManager implementation from the prototype.
> Create a new package @cardano-sdk/in-memory-key-manager

- package.json
- packages/blockfrost/package.json
- packages/cardano-graphql-db-sync/package.json
- packages/cardano-serialization-lib/package.json
- packages/cip30/package.json
- packages/core/package.json
- packages/golden-test-generator/package.json
- packages/in-memory-key-manager/package.json
- packages/wallet/package.json
With a package missing the `tsc` script, the pre-commit hook was calling the global executable and failing the pre-commit operation. Thanks for debugging @mkazlauskas 
Adds the missing script, and renames to avoid this in future.
> fix(in-memory-key-manager): add missing yarn script

- packages/cip2/src/RoundRobinRandomImprove/change.ts
- packages/cip2/src/types.ts
- packages/cip2/test/RoundRobinRandomImprove.test.ts
Input selection constraint for token bundle size takes in an entire `Value` (including coin), but coin quantity is not relevant.
Use `CSL.MultiAsset` instead
> fix(cip2): change token bundle size constraint arg to CSL.MultiAsset

- packages/cip2/README.md
- packages/cip2/jest.config.js
- packages/cip2/src/RoundRobinRandomImprove/change.ts
- packages/cip2/test/RoundRobinRandomImprove.test.ts
- packages/cip2/test/jest.setup.js
- packages/cip2/test/util/constraints.ts
- packages/cip2/test/util/index.ts
- packages/cip2/test/util/properties.ts
- packages/cip2/test/util/tests.ts
- packages/cip2/test/util/util.ts
Original implementation used property-based tests for happy paths only and it's difficult to test all remaining paths with regular example-based tests.
Generate `SelectionConstraints` and assert properties of input selection failure modes.
> test(cip2): generate selection constraints and assert failure properties

- collectCoverage.mjs
- package.json
- packages/blockfrost/package.json
- packages/cardano-graphql-db-sync/package.json
- packages/cardano-serialization-lib/package.json
- packages/cip2/README.md
- packages/cip2/package.json
- packages/cip30/package.json
- packages/core/package.json
- packages/golden-test-generator/package.json
- packages/in-memory-key-manager/package.json
- packages/wallet/package.json
We aim to have high code coverage. Generating coverage reports on each build would be nice.
Generate and upload coverage reports to gh-pages together with docs.
> docs: generate code coverage reports

- packages/blockfrost/src/blockfrostProvider.ts
- packages/blockfrost/test/blockfrostProvider.test.ts
- packages/cardano-graphql-db-sync/src/cardanoGraphqlDbSyncProvider.ts
- packages/cardano-graphql-db-sync/test/cardanoGraphqlDbSyncProvider.test.ts
- packages/core/src/Provider/CardanoProvider.ts
- packages/wallet/test/ProviderStub.ts
The light wallet requires some network and stake pool information.
Adds two new CardanoProvider properties: `networkInfo` and `stakePoolStats`. UTC dates are localised.
> Feature: CardanoProvider network info and stake pool stats

- packages/core/package.json
- packages/core/src/CSL/browser.ts
- packages/core/src/CSL/index.ts
- packages/core/src/CSL/loadCardanoSerializationLib.ts
- packages/core/src/CSL/nodejs.ts
- packages/wallet/test/createTransactionInternals.test.ts
Using `cardano-sdk/core` as a dependency in a project built with webpack is failing due to statically loading `@emurgo/cardano-serialization-lib-nodejs` in browser builds.
Load `@emurgo/cardano-serialization-lib-nodejs` dynamically in nodejs environment and exclude it from browser builds by utilizing `package.json/browser` field.
Exporting CSL types is now better, TypeScript won't allow you to use it as objects, only as types.
> chore(core): exclude nodejs version of csl from webpack browser builds

- packages/cip2/README.md
- packages/cip2/src/RoundRobinRandomImprove/index.ts
- packages/cip2/src/index.ts
- packages/cip2/src/selectionConstraints.ts
- packages/cip2/src/types.ts
- packages/cip2/src/util.ts
- packages/cip2/test/selectionConstraints.test.ts
- packages/cip2/test/util/properties.ts
- packages/in-memory-key-manager/test/jest.config.js
- packages/in-memory-key-manager/test/jest.setup.js
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/createTransactionInternals.ts
Since the CIP2 package is dependent on the CSL, we may as well include functions to cover the selection constraints:
- computeMinimumCost
- tokenBundleSizeExceedsLimit
- computeMinimumCoinQuantity
- computeSelectionLimit
Implement default selection constraints and export them from cip2 package. Use as defaults in coin selection if applicable.
> feat(cip2): add functions to create selection constraints

- packages/cip2/README.md
- packages/cip2/src/RoundRobinRandomImprove/change.ts
- packages/cip2/src/RoundRobinRandomImprove/index.ts
- packages/cip2/src/RoundRobinRandomImprove/roundRobin.ts
- packages/cip2/src/RoundRobinRandomImprove/util.ts
- packages/cip2/src/types.ts
- packages/cip2/src/util.ts
- packages/cip2/test/RoundRobinRandomImprove.test.ts
- packages/cip2/test/selectionConstraints.test.ts
- packages/cip2/test/util.test.ts
- packages/cip2/test/util/properties.ts
- packages/cip2/test/util/tests.ts
- packages/cip2/test/util/util.ts
- packages/core/src/Ogmios/util.ts
- packages/core/test/Ogmios/util.test.ts
- packages/wallet/src/InMemoryUtxoRepository.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/UtxoRepository.ts
- packages/wallet/src/createTransactionInternals.ts
- packages/wallet/test/InMemoryUtxoRepository.test.ts
- packages/wallet/test/SingleAddressWallet.test.ts
- packages/wallet/test/createTransactionInternals.test.ts
CIP2 spec didn't contain information about how to return min fee and we made a mistake of including fee quantity in change bundles. This is not the desired behavior and quantities in change bundles are used as transaction outputs to the return address.
After computing initial change bundles, deduct the estimated min fee and re-balance+re-validate change. There might be an exception when change becomes less than min utxo value at this point, in which case need to select an extra utxo and re-estimate the fee.
> fix(cip2): exclude fee from change bundles

- packages/blockfrost/package.json
- packages/cardano-graphql-db-sync/package.json
- packages/cip2/package.json
- packages/cip30/package.json
- packages/core/package.json
- packages/golden-test-generator/package.json
- packages/golden-test-generator/src/AddressBalance/getOnChainAddressBalances.ts
- packages/golden-test-generator/src/Block/getBlocks.ts
- packages/golden-test-generator/src/index.ts
- packages/wallet/package.json
- yarn.lock
The GTG has been lagging behind in the Mary era. We're also depending on a beta version of Ogmios.
Add support for Alonzo blocks in the GTG, bump to a pinned version of Ogmios across all packages.
> Chore/golden-test-generator Alonzo block support

- README.md
- packages/cardano-graphql-db-sync/package.json
- packages/cardano-graphql-db-sync/src/cardanoGraphqlDbSyncProvider.ts
- packages/core/src/Ogmios/ogmiosToCsl.ts
- packages/wallet/package.json
- packages/wallet/src/InMemoryUtxoRepository.ts
- packages/wallet/src/KeyManagement/InMemoryKeyManager.ts
- packages/wallet/src/KeyManagement/util.ts
- packages/wallet/test/InMemoryUtxoRepository.test.ts
- packages/wallet/test/KeyManagement/InMemoryKeyManager.test.ts
- packages/wallet/test/SingleAddressWallet.test.ts
- packages/wallet/test/createTransactionInternals.test.ts
- prototype/package.json
- prototype/src/Utils/mnemonic.ts
- prototype/src/lib/KeyManagers/InMemoryKey/index.ts
- prototype/src/test/RemoteWalletIntegration.spec.ts
- yarn.lock
`Buffer` needs a polyfill in browser env.
> chore: add buffer polyfill

- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/test/SingleAddressWallet.test.ts
We're missing the wallet name property, and the `createSingleAddressWallet` function interface could be improved before simply adding another property.
Restructure to group dependencies in an object, then add another as the first to carry wallet props.
> Feature: wallet name

- packages/wallet/src/KeyManagement/InMemoryKeyManager.ts
- packages/wallet/src/KeyManagement/types.ts
- packages/wallet/src/services/DelegationTracker/RewardsHistory.ts
- packages/wallet/src/services/RewardsTracker.ts
- packages/wallet/test/KeyManagement/InMemoryKeyManager.test.ts
- packages/wallet/test/integration/withdrawal.test.ts
- packages/wallet/test/services/RewardsTracker.test.ts
Blockfrost provider expects bech32 format for reward address and SDK using key hash.
> fix: reward account format

- packages/blockfrost/src/BlockfrostToCore.ts
- packages/blockfrost/src/blockfrostProvider.ts
- packages/blockfrost/test/blockfrostProvider.test.ts
- packages/core/src/Cardano/types/DelegationsAndRewards.ts
- packages/core/src/WalletProvider/types.ts
- packages/wallet/src/services/RewardsTracker.ts
Currently 404s for address-based lookups are allowed to fall through to an error state,
however, they need to be interpreted as expected results since it indicates the address is unused.
- Refactors the Blockfrost client implementation to remove `addressesUtxosAll`
in favour of `addressesUtxos`, and `addressesTransactionsAll` with `addressesTransactions`
as each of the former sends a batch of requests asynchronously, often over-fetching and
over-consuming the API quota. The new implementation fetches results sequentially as needed.
- Replaces the `utxoDelegationAndRewards` parameter `stakeKeyHash` with `stakeAddress`
> fix(blockfrost): interpret 404s in Blockfrost provider and optimise batching

- package.json
- packages/wallet/.env.example
- packages/wallet/.gitignore
- packages/wallet/README.md
- packages/wallet/e2e.jest.config.js
- packages/wallet/package.json
- packages/wallet/src/services/UtxoTracker.ts
- packages/wallet/test/e2e/SingleAddressWallet.test.ts
- packages/wallet/test/e2e/config.test.ts
- packages/wallet/test/e2e/config.ts
- test/base.jest.config.js
- test/e2e.jest.config.js
- test/jest.config.js
UtxoTracker currently passes an empty string as RewardsAccount. The argument is now optional.
Remove the argument.
Set up e2e tests for `wallet` package. Add e2e test for `SingleAddressWallet.balance`.
> fix(wallet): UtxoTracker should not query rewards

- packages/blockfrost/src/blockfrostWalletProvider.ts
- packages/blockfrost/src/util.ts
- packages/blockfrost/test/blockfrostWalletProvider.test.ts
- packages/blockfrost/test/util.test.ts
Transaction metadata from Blockfrost might possibly be of type `number` and our core type only supports `bigint`.
Recursively convert blockfrost metadata json fields from number to bigint
> fix(blockfrost): ensure tx metadata number type aligns with core

- package.json
Errors on install when using incompatible version of Node allowed by current engines value.
Set minimum version to `14.15.0`. Also set the maximum to `<15.0.0`, because some of the dependencies are not compatible with Node versions above 14.
```
nvm install 14.14.0
yarn install --force
```
Output:
```
error jest@27.0.6: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.14.0"
```
> chore: set node version to >=14.15.0 <15.0.0

- packages/cip2/src/RoundRobinRandomImprove/change.ts
- packages/cip2/src/RoundRobinRandomImprove/index.ts
- packages/cip2/src/RoundRobinRandomImprove/roundRobin.ts
- packages/cip2/src/RoundRobinRandomImprove/util.ts
- packages/cip2/src/index.ts
- packages/cip2/src/selectionConstraints.ts
- packages/cip2/src/types.ts
- packages/cip2/test/RoundRobinRandomImprove.test.ts
- packages/cip2/test/selectionConstraints.test.ts
- packages/cip2/test/util/properties.ts
- packages/cip2/test/util/tests.ts
- packages/core/src/CSL/coreToCsl.ts
- packages/core/test/CSL/coreToCsl.test.ts
- packages/util-dev/src/index.ts
- packages/util-dev/src/selectionConstraints.ts
- packages/util-dev/src/txTestUtil.ts
- packages/util-dev/test/selectionConstraints.test.ts
- packages/util-dev/test/txTestUtil.test.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/Transaction/createTransactionInternals.ts
- packages/wallet/src/types.ts
- packages/wallet/test/SingleAddressWallet.test.ts
- packages/wallet/test/Transaction/createTransactionInternals.test.ts
Wallets need to know minimum coin quantity on outputs so that they can create a valid transaction.
```typescript
interface MinimumCoinQuantity {
minimumCoin: Cardano.Lovelace;
coinMissing: Cardano.Lovelace;
}
type MinimumCoinQuantityPerOutput = Map<Cardano.TxOut, MinimumCoinQuantity>;
interface InitializeTxPropsValidationResult {
minimumCoinQuantities: MinimumCoinQuantityPerOutput;
}
interface Wallet {
validateInitializeTxProps(props: InitializeTxProps): Promise<InitializeTxPropsValidationResult>;
}
```
- Update `cip2` package types to use SDK's core types instead of CSL. As a result,
- Add a few new test utils to `util-dev` package
- Add `coreToCsl.tokenMap`
- Add `inputSelection` field to result of `wallet.initializeTx`
> feat: InitializeTxProps validation

- packages/wallet/src/KeyManagement/cachedGetPassword.ts
- packages/wallet/src/KeyManagement/emip3.ts
- packages/wallet/src/index.ts
- packages/wallet/src/util.ts
- packages/wallet/test/KeyManagement/cachedGetPassword.test.ts
Using `InMemoryKeyAgent` in (polyfilled) browser environment throws `TypeError: nonce.readUInt32LE is not a function`.
Convert `Uint8Array` to `Buffer`, as `chacha` library expects.
- Re-export `firstValueFrom` and `lastValueFrom` from rxjs as `wallet` package util. This will eliminate the need of having `rxjs` as a direct dependency for some use cases.
- `cachedGetPassword` will no longer call underlying `GetPassword` function while already authenticating.
> fix: chacha lib usage changes to work in polyfilled browser env

- packages/blockfrost/src/blockfrostAssetProvider.ts
- packages/blockfrost/test/blockfrostAssetProvider.test.ts
- packages/blockfrost/test/e2e/config.ts
- packages/blockfrost/test/e2e/getAsset.test.ts
- packages/core/src/Cardano/types/Asset.ts
- packages/wallet/test/mocks/mockAssetProvider.ts
Blockfrost asset provider `getAsset` throws an error for assets that have mint/burn history.
Refactor core `AssetMintOrBurn` type to use negative quantity to indicate burn (instead of `action` field).
> fix: blockfrost getAsset

- packages/cip2/test/util/properties.ts
cip2 property tests are occasionally failing due to having 0 quantity of tokens, which doesn't make sense to have as an output.
Only test with quantities >0
> fix(cip2): property tests generate quantities >0

- packages/wallet/src/KeyManagement/restoreKeyAgent.ts
- packages/wallet/test/KeyManagement/restoreKeyAgent.test.ts
Restoring InMemoryKeyAgent requires the passphrase
Do not decrypt private key on InMemoryKeyAgent restoration. If it's desired, user can trigger it manually
> fix(wallet): do not decrypt private key on InMemoryKeyAgent restoration

- packages/blockfrost/src/blockfrostAssetProvider.ts
- packages/blockfrost/test/blockfrostAssetProvider.test.ts
- packages/core/src/CSL/certificate.ts
- packages/core/src/CSL/coreToCsl.ts
- packages/core/src/Cardano/types/Address.ts
- packages/core/src/Cardano/types/Asset.ts
- packages/core/src/Cardano/types/AuxiliaryData.ts
- packages/core/src/Cardano/types/StakePool/primitives.ts
- packages/core/src/Cardano/util/index.ts
- packages/core/src/Cardano/util/metadatum.ts
- packages/core/test/Cardano/types/Address.test.ts
- packages/core/test/Cardano/types/StakePool.test.ts
- packages/core/test/Cardano/util/metadatum.test.ts
- packages/wallet/src/KeyManagement/types.ts
- packages/wallet/src/NftMetadata/createNftMetadataProvider.ts
- packages/wallet/src/NftMetadata/index.ts
- packages/wallet/src/NftMetadata/metadatumToCip25.ts
- packages/wallet/src/NftMetadata/types.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/index.ts
- packages/wallet/src/services/AssetsTracker.ts
- packages/wallet/src/types.ts
- packages/wallet/test/NftMetadata/createNftMetadataProvider.test.ts
- packages/wallet/test/NftMetadata/metadatumToCip25.test.ts
- packages/wallet/test/NftMetadata/types.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/delegation.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/nft.test.ts
- packages/wallet/test/mocks/mockAssetProvider.ts
- packages/wallet/test/services/AssetsTracker.test.ts
As an developer integrating the SDK wallet into an application
I want to show NFT metadata
so that I can present a rich user interface for my users that includes metadata that describes the asset
Add optional NFT metadata to `Wallet.assets$`
`core` package:
- Add partial support for Byron (base58) addresses (using it in a new tx is out of scope of this PR)
- Add partial support for genesis pool IDs (using it in a new tx is out of scope of this PR)
- Add a few metadatum parsing utils
- (BREAKING) change type of Asset.name to AssetName opaque string
- Since CIP-0025 does not specify encoding for `<asset_name>`, we'll support both hex and utf8 encoded strings.
- `<other properties>` are currently modeled like that:
```typescript
export interface NftMetadata {
...
otherProperties: { …
```
> feat: nft metadata

- packages/cardano-graphql/scripts/buildSchema.js
- packages/core/src/Provider/TimeSettingsProvider/index.ts
- packages/core/src/Provider/TimeSettingsProvider/types.ts
- packages/core/src/Provider/index.ts
- packages/core/src/util/index.ts
- packages/core/src/util/slotTimeCalc.ts
- packages/core/test/util/slotTimeCalc.test.ts
- packages/util-dev/src/createStubTimeSettingsProvider.ts
- packages/util-dev/src/index.ts
- packages/util-dev/test/createStubTimeSettingsProvider.test.ts
- packages/wallet/.env.example
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/types.ts
- packages/wallet/test/SingleAddressWallet.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/delegation.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/nft.test.ts
- packages/wallet/test/e2e/config.ts
- packages/wallet/test/integration/transactionTime.test.ts
- packages/wallet/test/integration/withdrawal.test.ts
Wallet needs to display transaction date
- add util for computing slot date given ledger time settings in `core` package
- add a new provider type (`TimeSettingsProvider`) in `core` package
- add a stub `TimeSettingsProvider` implementation in `util-dev` package
- add `Wallet.timeSettings$` and an integration test for usage example
An actual provider implementation is out of scope of this PR. Blockfrost doesn't seem to support this, so will implement it for `cardano-graphql`.
Running `buildSchema.js` script in `cardano-graphql` package broke due to not knowing how to import ES modules from `lodash-es`. Having mixed modules is not great, we should probably set up the packages to build both esm and cjs. For now I added a workaround so that it can build successfully.
> feat: slot datetime computation util

- packages/blockfrost/src/blockfrostWalletProvider.ts
- packages/blockfrost/test/blockfrostWalletProvider.test.ts
- packages/core/src/Address/util.ts
- packages/core/src/CSL/coreToCsl.ts
- packages/core/src/CSL/index.ts
- packages/core/src/CSL/parseCslAddress.ts
- packages/core/src/Cardano/types/Address.ts
- packages/core/src/Cardano/types/Block.ts
- packages/core/src/Cardano/types/StakePool/primitives.ts
- packages/core/test/Address/util.test.ts
- packages/core/test/CSL/coreToCsl.test.ts
- packages/core/test/CSL/parseCslAddress.test.ts
- packages/core/test/Cardano/types/Address.test.ts
- packages/core/test/Cardano/types/Block.test.ts
- packages/core/test/Cardano/types/StakePool.test.ts
* Loading a transaction with Byron addresses throws
* Loading a transaction with Shelley genesis delegate as slot leader throws
* (BREAKING) Accept base58-encoded addresses in `Cardano.Address` type and update `coreToCsl` to support that
* (BREAKING) Change type of `Block.slotLeader` to `PoolId | GenesisDelegate` and update `blockfrost` WalletProvider implementation to support that
`cardano-graphql` types/schema updates to reflect updated types
> fix: add support for byron addresses and genesis delegates as slot leaders

- packages/cip2/src/RoundRobinRandomImprove/change.ts
- packages/cip2/test/RoundRobinRandomImprove.test.ts
`cip2` property tests [failed](https://github.com/input-output-hk/cardano-js-sdk/runs/4871444863?check_suite_focus=true#step:7:51)
Filter out assets in change bundles at the last step of change calculation
> fix(cip2): omit 0 qty assets from change bundles

- packages/wallet/src/KeyManagement/InMemoryKeyAgent.ts
- packages/wallet/src/KeyManagement/KeyAgentBase.ts
- packages/wallet/src/KeyManagement/index.ts
- packages/wallet/src/KeyManagement/restoreKeyAgent.ts
- packages/wallet/src/KeyManagement/types.ts
- packages/wallet/src/KeyManagement/util/bip39.ts
- packages/wallet/src/KeyManagement/util/cachedGetPassword.ts
- packages/wallet/src/KeyManagement/util/index.ts
- packages/wallet/src/KeyManagement/util/key.ts
- packages/wallet/src/KeyManagement/util/ownSignatureKeyPaths.ts
- packages/wallet/src/KeyManagement/util/stubSignTransaction.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/test/KeyManagement/InMemoryKeyAgent.test.ts
- packages/wallet/test/KeyManagement/KeyAgentBase.test.ts
- packages/wallet/test/KeyManagement/restoreKeyAgent.test.ts
- packages/wallet/test/KeyManagement/util/cachedGetPassword.test.ts
- packages/wallet/test/KeyManagement/util/ownSignaturePaths.test.ts
- packages/wallet/test/KeyManagement/util/stubSignTransaction.test.ts
- packages/wallet/test/SingleAddressWallet.test.ts
- packages/wallet/test/mocks/mockWalletProvider.ts
- packages/wallet/test/mocks/testKeyAgent.ts
`SingleAddressWallet.initializeTx` calls input selection, which attempts to build a full transaction in order to compute it's size. It results in doing the actual transaction signing, which is not necessary at this point.
Use stub (any) signatures for input selection constraints.
- (BREAKING) Track known/derived addresses in KeyAgent. As a result there's an extra field in `SerializableInMemoryKeyAgentData`.
- Add `KeyManagement.util.ownSignaturePaths` which returns partial derivation paths required to sign a given transaction.
- (BREAKING) Consolidate KeyManagement utils under 1 directory. The breaking part is `KeyManagement.cachedGetPassword`->`KeyManagement.util.cachedGetPassword`
> fix: wallet initializeTx stub sign

- packages/blockfrost/src/blockfrostWalletProvider.ts
- packages/blockfrost/src/util.ts
- packages/blockfrost/test/blockfrostWalletProvider.test.ts
- packages/blockfrost/test/e2e/queryTransactions.test.ts
- packages/blockfrost/test/util.test.ts
- packages/cardano-graphql/src/WalletProvider/queryTransactions/graphqlTransactionsToCore.ts
- packages/cardano-graphql/test/WalletProvider/queryTransactions/graphqlTransactionsToCore.test.ts
- packages/cip2/src/selectionConstraints.ts
- packages/cip2/test/selectionConstraints.test.ts
- packages/core/src/Asset/types/NftMetadata.ts
- packages/core/src/Asset/util/metadatumToCip25.ts
- packages/core/src/CSL/coreToCsl.ts
- packages/core/src/Cardano/types/AuxiliaryData.ts
- packages/core/src/Cardano/util/metadatum.ts
- packages/core/test/Asset/util/metadatumToCip25.test.ts
- packages/core/test/CSL/coreToCsl.test.ts
- packages/core/test/Cardano/util/metadatum.test.ts
- packages/wallet/package.json
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/Transaction/createTransactionInternals.ts
- packages/wallet/src/types.ts
- packages/wallet/test/e2e/SingleAddressWallet/metadata.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/nft.test.ts
Building transaction with metadata is not implemented.
Implement it:
- Add `coreToCsl.txAuxiliaryData`
- Add `InitializeTxProps.auxiliaryData`
- (BREAKING) Change type of `Cardano.MetadatumMap` to `Map<Metadatum, Metadatum>` and `AuxiliaryData.blob` to `Map<bigint, Metadatum>`. This structure better reflects [the underlying model](https://github.com/input-output-hk/cardano-ledger/blob/master/eras/alonzo/test-suite/cddl-files/alonzo.cddl#L321).
- `computeMinimumCost` doesn't work correctly for transactions with metadata - computed fee is too low. It seemed to work correctly some of the time. Need to investigate if we're using 'CSL.min_fee` incorrectly or if there's a bug in either CSL or our code. For now I just adjusted the fee by hardcoded value (+10k).
- `wallet` package e2e test suite …
> feat: metadata serialization

- packages/wallet/src/KeyManagement/emip3.ts
emip3decrypt throws when called with Uint8Array data in browser env: it attempts to call `readUInt16LE` which is only available on Buffer.
Convert data to Buffer
> fix(wallet): fix emip3decrypt to work in polyfilled browsers

- packages/core/src/CSL/coreToCsl.ts
- packages/core/test/CSL/coreToCsl.test.ts
Fix a condition from `>=` to `>`
> fix(core): correct metadata length check

- packages/cip2/src/RoundRobinRandomImprove/change.ts
- packages/cip2/src/RoundRobinRandomImprove/index.ts
- packages/cip2/src/RoundRobinRandomImprove/roundRobin.ts
- packages/cip2/src/RoundRobinRandomImprove/util.ts
- packages/cip2/test/RoundRobinRandomImprove.test.ts
- packages/cip2/test/jest.setup.js
- packages/cip2/test/util/properties.ts
- packages/util-dev/src/selectionConstraints.ts
- packages/util-dev/test/selectionConstraints.test.ts
Transactions occasionally fail due to fee too low. This is due to a bug within input selection, where it does not recompute the fee after selecting an extra utxo.
Reproduce the bug in a test and fix it.
- Add support for custom random function for round robin random improve
- Update mock selection constraints fee computation to be a function of selected # of inputs instead of a constant
> fix: recompute fee after selecting extra utxo due to min utxo value

- packages/blockfrost/test/e2e/queryTransactions.test.ts
- packages/cip2/src/selectionConstraints.ts
- packages/cip2/test/selectionConstraints.test.ts
Remove hardcoded workaround for something that has just been fixed in earlier commit.
> fix(cip2): remove hardcoded value in minimum cost selection constraint

- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/persistence/inMemoryStores.ts
- packages/wallet/src/persistence/index.ts
- packages/wallet/src/persistence/types.ts
- packages/wallet/src/services/ProviderStatusTracker.ts
- packages/wallet/src/services/TrackedWalletProvider.ts
- packages/wallet/src/services/index.ts
- packages/wallet/src/services/types.ts
- packages/wallet/src/types.ts
- packages/wallet/test/SingleAddressWallet.test.ts
- packages/wallet/test/persistence/inMemoryStores.test.ts
- packages/wallet/test/services/ProviderStatusTracker.test.ts
- packages/wallet/test/services/TrackedWalletProvider.test.ts
`SingleAddressWallet` takes a long time to load (fetching all transactions and utxo)
In preparation to implementing wallet persistence, do the following:
- (BREAKING) Remove `address` prop from `SingleAddressWallet` constructor, using `KeyAgent.knownAddresses` for initialization
- Define storage interfaces, implement in-memory storage (intended for development and testing, but could potentially be used to initialize wallets that do not want to store their state, or when shutting down and then restoring the wallet)
- Add `Wallet.syncStatus$` {Syncing, UpToDate}, so that wallet users have some insight on whether their wallet is currently synced or outdated. Implement it by wrapping a `WalletProvider` and tracking calls/responses of each function.
> feat: preparation for SingleAddressWallet persistence implementation

- packages/blockfrost/src/blockfrostTxSubmitProvider.ts
- packages/blockfrost/test/blockfrostTxSubmitProvider.test.ts
- packages/cardano-graphql-db-sync/src/cardanoGraphqlDbSyncTxSubmitProvider.ts
- packages/core/src/Provider/Provider.ts
- packages/core/src/Provider/TxSubmitProvider/types.ts
- packages/core/src/Provider/index.ts
- packages/ogmios/src/ogmiosTxSubmitProvider.ts
- packages/ogmios/test/mocks/mockOgmiosServer.ts
- packages/ogmios/test/ogmiosTxSubmitProvider.test.ts
- packages/wallet/src/services/ProviderTracker/TrackedTxSubmitProvider.ts
- packages/wallet/test/mocks/mockTxSubmitProvider.ts
- packages/wallet/test/services/TrackedTxSubmitProvider.test.ts
Checking the health of a service is an important aspect for application logic and system monitoring. All providers have this common model, but we don't currently have a base interface. The service of interest is tx submission due to a dependent chunk of work now on hold awaiting this feature.
Implement a base interface with minimal model for a boolean response, but room for an extension to include other metrics at a later date. I've purposely left the other provider refactors out of this scope to avoid overloading this PR, as it can be completed separately.
> feat: add Provider interface, use as base for TxSubmitProvider

- packages/core/src/Address/util.ts
- packages/core/src/util/index.ts
- packages/core/src/util/txInspector.ts
- packages/core/test/Address/util.test.ts
- packages/core/test/util/txInspector.test.ts
Added a transaction inspection feature to differentiate between transaction types
Create util function `createTxInspector` in `core` package that receives inspector functions to identify different operations in a transaction.
Create inspector functions for sending, receiving, delegation, stake key registration, stake key registration transactions and withdrawals.
> feat(core): add tx inspector

- packages/cip2/src/selectionConstraints.ts
- packages/cip2/test/selectionConstraints.test.ts
- packages/wallet/src/KeyManagement/types.ts
- packages/wallet/src/KeyManagement/util/mapHardwareSigningData.ts
- packages/wallet/src/KeyManagement/util/ownSignatureKeyPaths.ts
- packages/wallet/src/KeyManagement/util/stubSignTransaction.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/cip30.ts
- packages/wallet/src/services/WalletUtil.ts
- packages/wallet/src/services/index.ts
- packages/wallet/src/types.ts
- packages/wallet/test/KeyManagement/InMemoryKeyAgent.test.ts
- packages/wallet/test/KeyManagement/util/stubSignTransaction.test.ts
- packages/wallet/test/SingleAddressWallet/load.test.ts
- packages/wallet/test/SingleAddressWallet/methods.test.ts
Wallets might want to validate some transaction properties before building it. We currently have `Wallet.validateInitializeTxProps`, which was originally designed as a general validation function that could be called prior to calling `Wallet.initializeTx` to ensure that `initializeTx` will succeed, as well as providing additional context about any validation errors. Problem with this approach is that one of the potential errors is the overall transaction size being too large. To perform this validation, you have to run input selection algorithm, which has randomness involved and could therefore select a different number of inputs, resulting in a different transaction size when you later call `initializeTx`. Therefore, it is way more practical to keep validation of transaction size as an …
> feat: additional output validation

- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/persistence/inMemoryStores/inMemoryWalletStores.ts
- packages/wallet/src/persistence/pouchdbStores/pouchdbWalletStores.ts
- packages/wallet/src/persistence/types.ts
- packages/wallet/src/services/BalanceTracker.ts
- packages/wallet/src/services/UtxoTracker.ts
- packages/wallet/src/services/types.ts
- packages/wallet/src/services/util/persistentTrackerSubjects.ts
- packages/wallet/test/services/BalanceTracker.test.ts
- packages/wallet/test/services/UtxoTracker.test.ts
Allow wallet to set unspendable UTxO set, which won't be present in available UTxO or balance for input selection.
Jira Issue: [ADP-1647](https://input-output.atlassian.net/browse/ADP-1647)
- Add `unspendable$` at `UtxoTracker` and `BalanceTracker`
- Add `setUnspendable(utxo: Cardano.Utxo[])` at `UtxoTracker` to update store values
- Filter out unspendable utxo in `available$` utxo in `UtxoTracker`
- `UtxoTracker` now has `unspendableStore` and `unspendableUtxoSource$` arguments
- `PersistentCollectionTrackerSubject.next` now also sets all store values
> feat(wallet): add unspendable utxo observable and store

- packages/core/src/util/txInspector.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/src/services/types.ts
- packages/wallet/test/integration/transactionTime.test.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
Simplify `SingleAddressWallet.transactions.history.all` by changing it’s type to `Cardano.TxAlonzo[]`
- Use the transaction inspector to identify an outgoing or incoming transaction and get rid of `DirectionalTransaction` type
- Changed `transactions.history.all$` type from `DirectionalTransaction` to `TxAlonzo`
- Removed `DirectionalTransaction` and `TransactionDireciton`
> refactor(wallet): change transactions history all type to TxAlonzo

- packages/core/src/Address/util.ts
- packages/core/src/Asset/util/index.ts
- packages/core/src/Asset/util/removeNegativesFromTokenMap.ts
- packages/core/src/Asset/util/subtractTokenMaps.ts
- packages/core/src/Cardano/util/index.ts
- packages/core/src/Cardano/util/resolveInputValue.ts
- packages/core/src/Cardano/util/subtractValueQuantities.ts
- packages/core/src/util/BigIntMath.ts
- packages/core/src/util/txInspector.ts
- packages/core/test/Address/util.test.ts
- packages/core/test/Asset/util/removeNegativesFromTokenMap.test.ts
- packages/core/test/Asset/util/subtractTokenMaps.test.ts
- packages/core/test/Cardano/util/coalesceValueQuantities.test.ts
- packages/core/test/Cardano/util/resolveInputValue.test.ts
- packages/core/test/Cardano/util/subtractValueQuantities.test.ts
- packages/core/test/util/BigIntMath.test.ts
- packages/core/test/util/txInspector.test.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/services/DelegationTracker/DelegationTracker.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/src/services/types.ts
- packages/wallet/test/SingleAddressWallet/load.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/delegation.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/metadata.test.ts
- packages/wallet/test/integration/transactionTime.test.ts
- packages/wallet/test/services/DelegationTracker/DelegationTracker.test.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
`outgoing$` and `incoming$` transactions definitions are not clear. It's better if we removed them and instead let the sdk user use the transaction inspector to classify transactions as needed.
Thread discussing the issue: https://github.com/input-output-hk/cardano-js-sdk/pull/230#discussion_r855336487
- Remove `history.outgoing$` and `history.incoming$`, replace `history.all$` with just `history$`.
- Improve inspectors to properly tell if a transaction was sent by an address, calculate inputs and outputs total value sent and received and calculate total net value sent and received
**TransactionsTracker:**
- `TransactionsTracker.history.outgoing$` and `TransactionsTracker.history.incoming$` were removed 
- `TransactionsTracker.incoming$` was removed
- `TransactionsTracker.history.all$` …
> refactor: transactions tracker

- packages/cardano-services-client/package.json
- packages/cardano-services-client/src/HttpProvider.ts
- packages/cardano-services-client/test/HttpProvider.test.ts
- packages/cardano-services-client/test/StakePoolSearchProvider/stakePoolSearchHttpProvider.test.ts
- packages/cardano-services-client/test/TxSubmitProvider/txSubmitHttpProvider.test.ts
- packages/cardano-services/package.json
- packages/cardano-services/test/Http/HttpServer.test.ts
- packages/cardano-services/test/StakePoolSeach/StakePoolSearchHttpService.test.ts
- packages/cardano-services/test/TxSubmit/TxSubmitHttpService.test.ts
- packages/cardano-services/test/entrypoints.test.ts
- yarn.lock
`got` does not support browser environment so we need to replace it with something else.
Replace `got` in `HttpProvider` with `axios`, which can be used in both node and browser environments
- refactor `HttpProvider`
- replace all uses of `got` with `axios` in tests
> refactor: use `axios` in `HttpProvider` instead of `got` to support browser usage

- .vscode/launch.json
- packages/cardano-services/package.json
- packages/cardano-services/src/StakePoolSearch/DbSyncStakePoolSearchProvider/DbSyncStakePoolSearch.ts
- packages/cardano-services/src/StakePoolSearch/DbSyncStakePoolSearchProvider/StakePoolSearchBuilder.ts
- packages/cardano-services/src/StakePoolSearch/DbSyncStakePoolSearchProvider/queries.ts
- packages/cardano-services/test/StakePoolSeach/StakePoolSearchHttpService.test.ts
- packages/cardano-services/test/StakePoolSeach/__snapshots__/StakePoolSearchHttpService.test.ts.snap
- packages/core/src/Provider/StakePoolSearchProvider/types/StakePoolSearchProvider.ts
Add ordering control to the stake pool search interface
Apply a sort by given field and order at the database level before the actual pagination. This ensures that in case we have passed pagination with sort, the entire result set will be sorted A-z, not only each individual page.
- extend stake pool query options interface with a sort
- apply sort by order and field (order by name) on queryPoolData query
- apply default sort if not provided (order by name then by pool id ascending)
- apply the pagination after sorting
- add debug config for local HTTP service (VSCode)
Most of the DB Stake pools snapshots are modified due to the default sort of stake pools. (by name ascending) - [StakePoolSearchHttpService.test.ts.snap](https://github.com/input-output-hk/cardano-js-sdk/pull/250/files#diff- …
> feat: add ordering to stake pool search interface

- packages/cardano-services/src/Utxo/DbSyncUtxoProvider/queries.ts
- packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
- packages/cardano-services/test/Utxo/__snapshots__/UtxoHttpService.test.ts.snap
The UTxO return is currently not reproducible as there's no explicit ordering within the SQL query, which in turn results in a flakey test suite.
Cherry-picked 775d259c8f06cfea35b08dae6ab0698cdef37044, and reverted the snapshot update since it's not yet been updated on _master_. This commit orders the `findUtxosByAddresses` by a fixed, on-chain reliable value.
Also removes the use of `got` in the test, which was a dangling dependency
> fix: use ordering within UTxO query for reproducible results

- packages/cardano-services/test/StakePoolSeach/DbSyncStakePoolSearchProvider/StakePoolSearchBuilder.test.ts
- packages/cardano-services/test/StakePoolSeach/DbSyncStakePoolSearchProvider/__snapshots__/StakePoolSearchBuilder.test.ts.snap
Since Db Snapshot can be taken from different databases some autoincremental IDs can vary from db to db due to cases such rollbacks. So, instead of checking for every ID number, we would check only object's data by replacing every registry ID per a generic one
> Refactor StakePoolBuilder tests

- packages/wallet/src/KeyManagement/LedgerKeyAgent.ts
- packages/wallet/test/hardware/LedgerKeyAgent.test.ts
Bugfix for transaction signing with Ledger devices when the account index is different than zero.
[JIRA ticket](https://input-output.atlassian.net/browse/ADP-1800)
Wallet user can create a single account / address wallet with any account index, and perform all wallet actions using it. In this particular case to sign and send transactions using Ledger.
- Fixed witnesses preparation in LedgerKeyAgent
> fix(wallet): Ledger transaction submission bug fix

- packages/wallet/src/persistence/pouchdbStores/PouchdbCollectionStore.ts
- packages/wallet/src/persistence/pouchdbStores/PouchdbKeyValueStore.ts
- packages/wallet/src/persistence/pouchdbStores/PouchdbStore.ts
- packages/wallet/test/persistence/pouchdbStores.test.ts
When testing in web-extension e2e setup I noticed occasional write failures when setting asset data. Data of each asset is fetched independently and 2 assets can sometimes resolve at roughly the same time, causing 2 simultaneous writes to pouchdb, which results in a conflict error.
Queue pouchdb write operations
> fix(wallet): queue pouchdb writes

- packages/cardano-services-client/test/HttpProvider.test.ts
Fixed test that may cause 'address already in use' error
> test(client): fixed 'address already in use' issue

- packages/wallet/src/KeyManagement/types.ts
- packages/wallet/src/KeyManagement/util/createAsyncKeyAgent.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/services/EpochTracker.ts
- packages/wallet/src/services/ProviderTracker/ProviderStatusTracker.ts
- packages/wallet/src/services/util/persistentTrackerSubjects.ts
- packages/wallet/src/types.ts
- packages/wallet/test/KeyManagement/util/createAsyncKeyAgent.test.ts
- packages/wallet/test/services/ProviderTracker/ProviderStatusTracker.test.ts
- packages/web-extension/src/messaging/remoteApi.ts
- packages/web-extension/src/messaging/types.ts
- packages/web-extension/src/observableWallet/util.ts
e2e tests do not exit for a long time after passing all tests
Add missing SingleAddressWallet cleanup:
- add AsyncKeyAgent.shutdown
- [refactor(web-extension): update types to never expose shutdown()](https://github.com/input-output-hk/cardano-js-sdk/pull/268/commits/590de0724b44b8c1849cec96e5bd786e35d495ca)
- add ProviderStatusTracker.shutdown
- add a missing `complete()/shutdown()` calls in SingleAddressWallet.shutdown
- add a missing optional `auxiliaryData` argument in `ObservableWallet.finalizeTx`
> fix(wallet): add missing cleanup for SingleAddressWallet

- .github/workflows/continuous-integration.yaml
The workflow has had a failure with the artefact upload for some time now:
- Bump upload-artifact version
- Use the new glob-based matcher to dynamically select both npm packages and GTG executables
The changes can be verified by comparing the [last CI run on master ](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/2453480464) with this [branch's run](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/2453386707). Downloading the fixed workflow artifacts and unpacking will demonstrate it.
> ci: update CI upload artifact steps

- packages/core/src/CSL/coreToCsl/coreToCsl.ts
- packages/core/test/CSL/coreToCsl.test.ts
- packages/core/test/CSL/testData.ts
ADP-1763
remove duplicated insert when assets from the same policy are present in the token map
Conversion back to core types test is failing. Currently investigating
> fix: Core TokenMap to CSL multiasset insert de-dupe  

- .github/workflows/post_integration.yml
- .gitignore
- package.json
- packages/cardano-services/package.json
- packages/rabbitmq/package.json
- yarn.lock
CI `deploy-docs` workflow is failing. See [this](https://github.com/input-output-hk/cardano-js-sdk/runs/6860533004).
See commit log
[chore(cardano-services): add --runInBand arg to jest](https://github.com/input-output-hk/cardano-js-sdk/pull/279/commits/ca6641b972bc06b141c6a6f3db06ec60be2352fd) is unrelated to CI failure as it's probably single-threaded, but it is an issue for devs when running locally. This is a temporary fix until we get ADP-1891 done
> chore: bump typedoc

- packages/cardano-services/src/cli.ts
`yarn cli` in `cardano-services` is broken
Correctly resolve `package.json` path when run in `ts-node`
> fix(cardano-services): resolve package.json path when cli is run with ts-node

- packages/web-extension/e2e/extension/util.ts
- packages/web-extension/package.json
- packages/web-extension/src/keyAgent/util.ts
- packages/web-extension/src/messaging/remoteApi.ts
- packages/web-extension/src/messaging/types.ts
- packages/web-extension/src/observableWallet/util.ts
- packages/web-extension/test/messaging/remoteApi.test.ts
- yarn.lock
Extension messaging remote api object shouldn't recreate objects on every property access
```typescript
const obj = consumeRemoteApi(...)
obj.prop === obj.prop // false, should be true
```
Cache remote api properties 44764aa6ef578d43b5726ba56a7d5c2f80958359
- chore(web-extension): bump chromedriver dependency version 9d042391c237836108f22c98044a447f1982a399
- refactor(web-extension)!: rename RemoteApiProperty.Observable->HotObservable 4bc99224d3cdcadc90729eecd8cb9ea2d6227438
> fix: messaging prop cache

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/types.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/mappers.test.ts
- packages/cardano-services/test/StakePool/__snapshots__/StakePoolHttpService.test.ts.snap
When stake-pool server is started with testnet-db-snapshot DB then called POST ”stake-pool/search”   with the request - 
```
{ "args":[] }
```
It returns 500 and divide by zero error. 
Add `WHEN COALESCE(stake.active_stake, 0) = 0 THEN 0` check to epoch rewards query
> fix: division by zero error at pool rewards query

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePool.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/types.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/util.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/mappers.test.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/util.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/StakePool/__snapshots__/StakePoolHttpService.test.ts.snap
- packages/core/src/Provider/StakePoolProvider/index.ts
- packages/core/src/Provider/StakePoolProvider/types/StakePoolProvider.ts
- packages/core/src/Provider/StakePoolProvider/util.ts
The current sort order for results returned from the `DbSyncStakePoolProvider.queryStakePools` method is ordered by name. We require the interface to also include `saturation`.
- Add `saturation` sort field with `desc` order as default
- Adapt `withSort` function to be able to sort queries other than `findPoolData`
- Refactor `DbSyncStakePoolProvider.queryStakePools` so it can identify which query to use to order the response
- `DbSyncStakePoolProvider.queryStakePools` refactor
- Added `getQueryBySortType` private method to `DbSyncStakePoolProvider`
- Added sort by saturation to pool metrics query
- Fix a bug where sorting by name was case sensitive, leading to results like: `['CLIO1','July 2021','banderini']`
- Fix a bug where sorting by name `desc` would return pools with no name first …
> feat: add sort stake pools by saturation

- packages/cardano-services/src/InMemoryCache/InMemoryCache.ts
- packages/cardano-services/test/InMemoryCache/InMemoryCache.test.ts
In case when the cache is cleared and multiple simultaneous requests come in, we would run the DB query multiple times.
Raised by @mkazlauskas 
Caching the promise instead of resolving the value, so the next invocation will instantly return the same promise.
In case of DB query fails -> `result.catch()` resets the cache so don't have to wait for the TTL
> feat: Enhance InMemoryCache 'get' method

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/queries.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
Currently, we are retrieving the last epoch using `ORDER BY id DESC LIMIT 1`, with `id` being the table id.
We should use `no` of the epoch record instead of `id` . Given that the epoch table index is created by `no` (`idx_epoc_no`)
Modify block and epoch queries so they are ordered by number instead of `id`
> refactor(cardano-services): order epoch and block queries by number instead of id

- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/cip30.ts
- packages/wallet/src/services/AssetsTracker.ts
- packages/wallet/src/services/BalanceTracker.ts
- packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
- packages/wallet/src/services/UtxoTracker.ts
- packages/wallet/src/services/types.ts
- packages/wallet/src/types.ts
- packages/wallet/test/SingleAddressWallet/load.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/delegation.test.ts
- packages/wallet/test/e2e/SingleAddressWallet/nft.test.ts
- packages/wallet/test/integration/txChainingBalance.test.ts
- packages/wallet/test/integration/withdrawal.test.ts
- packages/wallet/test/services/AssetsTracker.test.ts
- packages/wallet/test/services/BalanceTracker.test.ts
- packages/wallet/test/services/DelegationTracker/RewardAccounts.test.ts
- packages/wallet/test/services/UtxoTracker.test.ts
- packages/web-extension/e2e/extension/ui.ts
- packages/web-extension/src/observableWallet/util.ts
It’d be useful to be able to submit a transaction that has an input that is an output of a transaction that didn’t get onto chain yet.
- Include pending transaction change outputs in available utxo set [95c2671](https://github.com/input-output-hk/cardano-js-sdk/pull/283/commits/95c2671055627a7c6cb334adc1a05b6b43bcb738)
- Improve `ObservableWallet.balance` interface: with transaction chaining, deposit and rewards should be reflected to balance immediately and it no longer makes sense to have `balance.{total$,available$}.{deposit,rewards}`. Therefore there is now just a single field for deposit and rewards. [b8371f9](https://github.com/input-output-hk/cardano-js-sdk/pull/283/commits/b8371f97e151c2e9cb18e0ac431e9703fe490d26)
> feat: transaction chaining

- packages/cardano-services/test/ChainHistory/__snapshots__/ChainHistoryHttpService.test.ts.snap
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/NetworkInfo/__snapshots__/NetworkInfoHttpService.test.ts.snap
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
- packages/cardano-services/test/StakePool/__snapshots__/StakePoolHttpService.test.ts.snap
- packages/cardano-services/test/jest-setup/dump-db-sdk.sh
Adds block `3556390` to current db-snapshot in order to handle transactions with nft metadata test cases
> test(cardano-services): add block 3556390 to current db snapshot

- packages/cardano-services/test/Reward/RewardsHttpService.test.ts
- packages/cardano-services/test/Reward/__snapshots__/RewardsHttpService.test.ts.snap
Test case “RewardsHttpService healthy state with rewardsHttpProvider rewardsHistory returns address rewards history with epochs 1” has an empty expected result.
Change epochs filters and address of the request in order to expect a non empty response.
N/A
> test(cardano-services): update test case for rewardsHttpProvider

- packages/cardano-services/src/ChainHistory/ChainHistoryHttpService.ts
- packages/cardano-services/src/Http/HttpServer.ts
- packages/cardano-services/src/Http/HttpService.ts
- packages/cardano-services/src/NetworkInfo/NetworkInfoHttpService.ts
- packages/cardano-services/src/Program/loadHttpServer.ts
- packages/cardano-services/src/Rewards/RewardsHttpService.ts
- packages/cardano-services/src/StakePool/StakePoolHttpService.ts
- packages/cardano-services/src/TxSubmit/TxSubmitHttpService.ts
- packages/cardano-services/src/Utxo/UtxoHttpService.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/Http/HttpServer.test.ts
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/Program/loadHttpServer.test.ts
- packages/cardano-services/test/Reward/RewardsHttpService.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/TxSubmit/TxSubmitHttpService.test.ts
- packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
We need to keep all services pure during initialization time (static `create` method). 
In order to do that, we need to remove real health checks inside `create` service method, more of that, the static `create` method becomes redundant and we can use `public constructor` directly for the service creation phase.
Provider's health checks should be performed during the service initialization phase and all services need to be aligned with that.
See the changes introduced.
- make `HttpService` a concrete class, extending `RunnableModule`
- make all HTTP services constructable, remove the static `create` method from them
- perform provider health checks during service `initialize`
- hoist all repeatable methods from individual services to `HttpService` parent class
- rework `loadHttpServer` …
> refactor: Remove HTTPService.create static methods and perform provider health checks during service initialization

- packages/cardano-services/src/StakePool/openApi.json
- packages/cardano-services/test/Reward/DbSyncRewardsProvider/RewardsBuilder.test.ts
- packages/cardano-services/test/Reward/DbSyncRewardsProvider/__snapshots__/RewardsBuilder.test.ts.snap
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/StakePool/__snapshots__/StakePoolHttpService.test.ts.snap
- packages/cardano-services/test/jest-setup/dump-db-sdk.sh
`stake-pool/search` endpoint returns 500 error reponse as `ipv4`, `ipv6` and `port` fields fail to validate against open api specs when `null`
Example:
```json
{
"path": ".response.pageResults[3].relays[0].ipv6",
"message": "should be string",
"errorCode": "type.openapi.validation"
}
```
- Allow those fields to be `null` or `undefined`
- Add `pool_relays` table to dump script and test data
- Add block `1932634` to fixture data to cover all test cases with `pool_update.id = 355`
> fix: allow pool relay nullable fields in open api validation

- packages/util/src/serializableObject.ts
- packages/util/test/serializableObject.test.ts
initializeTx takes in Set objects. Using a remote wallet does not serialize/deserialize sets correctly. 
Add Set support (similar to [Map](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/util/src/serializableObject.ts#L56))
> fix(util): add Set serialization support

- packages/wallet/src/services/WalletUtil.ts
- packages/wallet/test/integration/CustomObservableWallet.test.ts
- packages/wallet/test/services/WalletUtil.test.ts
- Implementing new providers for `SingleAddressWallet` requires resolving **all** fields defined in core package. This is not always possible.
- Using `ObservableWallet` interface as a base in a custom wallet application in not always possible for similar reasons.
- Creating a new wallet interface and basing implementation on SDK utils is also complicated, because most utils depend on either full `Cardano.*` types or full `ObservableWallet`, which (again) could not necessarily be resolved and might be difficult or impossible to do without losing type safety that is provided by TypeScript.
- Refactor `WalletUtil` as an example of what we would eventually do with the rest of the SDK utils 0339afdc86494cea7d760383c869a0258deafc07:
- Replace `ObservableWallet` arg with minimal …
> refactor: modular wallet utils

- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/Transaction/createTransactionInternals.ts
- packages/wallet/src/types.ts
- packages/wallet/test/SingleAddressWallet/methods.test.ts
- packages/wallet/test/Transaction/createTransactionInternals.test.ts
Some transaction body fields have not yet been defined in our[ core type](https://github.com/input-output-hk/cardano-js-sdk/blob/6431f57ee5d0624784e9ae6c6b6a73b35a514ee0/packages/core/src/Cardano/types/Transaction.ts#L37-L48), so the task here is to complete the mapping to all available properties of the current era (Babbage is out of scope, as it requires the unreleased v11 of the CSL)
Add support for those fields we're missing in [createTransactionInternals](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/wallet/src/Transaction/createTransactionInternals.ts), [cslToCore](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/core/src/CSL/cslToCore/cslToCore.ts), [coreToCsl](https://github.com/input-output-hk/cardano-js-sdk/tree/master/packages/core/ …
> feat: add missing transaction fields

- packages/cardano-services/.env.test
- packages/cardano-services/package.json
- packages/cardano-services/src/Program/ProgramOptionDescriptions.ts
- packages/cardano-services/src/Program/errors/InvalidArgsCombination.ts
- packages/cardano-services/src/Program/errors/MissingProgramOption.ts
- packages/cardano-services/src/Program/errors/index.ts
- packages/cardano-services/src/Program/index.ts
- packages/cardano-services/src/Program/loadHttpServer.ts
- packages/cardano-services/src/Program/utils.ts
- packages/cardano-services/src/ProgramsCommon/CommonOptionDescriptions.ts
- packages/cardano-services/src/ProgramsCommon/options.ts
- packages/cardano-services/src/TxWorker/loadTxWorker.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/src/run.ts
- packages/cardano-services/src/startWorker.ts
- packages/cardano-services/test/Program/loadHttpServer.test.ts
- packages/cardano-services/test/Program/utils.test.ts
- packages/cardano-services/test/entrypoints.test.ts
- packages/cardano-services/test/entrypoints.txWorker.test.ts
- yarn.lock
Add new `cardano-services` CLI and HttpServer arguments to support resolving the ports using DNS SRV records for:
**CLI:**
`--ogmios-srv-service-name` (alternative to `--ogmios-url`)
`--rabitmq-srv-service-name` (alternative to `--rabbitmq-url`)
`--postgres-srv-service-name` + `--postgres-db` + `--postgres-user` + `--postgres-password` (alternative to `--db-connection-string`)
**HTTP Server:**
`RABBITMQ_SRV_SERVICE_NAME` (alternative to `--RABBITMQ_URL`)
`OGMIOS_SRV_SERVICE_NAME` (alternative to`OGMIOS_URL`)
`POSTGRES_SRV_SERVICE_NAME` + `POSTGRES_DB` + `POSTGRES_USER` + `POSTGRES_PASSWORD` (alternative to `DB_CONNECTION_STRING`)
Use those new variables to resolve port of those services with [dns.resolveSrv](https://nodejs.org/docs/latest-v14.x/api/dns.html#dns_dns_resolvesrv_hostname_call …
> feat: cardano-services dependency port resolution using DNS SRV records

- packages/e2e/test/blockfrost/queryTransactions.test.ts
Due to recent DBSync schema and general Babbage era changes, some behavior changed in the Blockfrost API that is breaking some of our end-to-end unit tests.
Fix Blockfrost unit tests to account for these changes.
Blockfrost e2e tests were updated to account for the change of behavior of the API.
> test(e2e): fix Blockfrost e2e breaking tests due to Babbage era changes

- Dockerfile
The Cardano services docker file is missing three dependencies needed to be able to build on Mac (M1).
Add the missing dependencies to the docker file.
The following packages were added as dependencies in the Docker file of cardano services.
- pkg-config 
- libusb-1.0
- libudev-dev
> chore: add missing dependencies to cardano services docker file

- packages/cardano-services-client/src/AssetInfoProvider/assetInfoHttpProvider.ts
- packages/cardano-services-client/src/AssetInfoProvider/index.ts
- packages/cardano-services-client/src/index.ts
- packages/cardano-services-client/test/AssetInfoProvider/assetInfoHttpProvider.test.ts
We need to add an asset info http provider to `@cardano-sdk/cardano-services-client`.
Added `assetInfoHttpProvider`.
> feat(cardano-services-client): add asset info http provider

- packages/cardano-services-client/test/AssetInfoProvider/assetInfoHttpProvider.test.ts
- packages/cardano-services/copy-assets.sh
- packages/cardano-services/src/Asset/AssetHttpService.ts
- packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider.ts
- packages/cardano-services/src/Asset/index.ts
- packages/cardano-services/src/Asset/openApi.json
- packages/cardano-services/src/Http/HttpService.ts
- packages/cardano-services/src/Program/ProgramOptionDescriptions.ts
- packages/cardano-services/src/Program/ServiceNames.ts
- packages/cardano-services/src/Program/loadHttpServer.ts
- packages/cardano-services/src/Program/utils.ts
- packages/cardano-services/src/ProgramsCommon/CommonOptionDescriptions.ts
- packages/cardano-services/src/TxWorker/loadTxWorker.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/src/index.ts
- packages/cardano-services/src/run.ts
- packages/cardano-services/test/Asset/AssetBuilder.test.ts
- packages/cardano-services/test/Asset/AssetHttpService.test.ts
- packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
- packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
- packages/cardano-services/test/Program/utils.test.ts
- packages/cardano-services/test/entrypoints.test.ts
We need to add an http service to serve asset related functions.
Added `AssetHttpService` and `TokenMetadataProvider` to expose `CardanoTokenRegistry.getTokenMetadata`.
> feat(cardano-services): adds asset http service

- packages/wallet/test/cip36.test.ts
We've been seeing the odd test failure that this change may fix. The working theory from @mkazlauskas is that `getNonce` is
being called within the same ms, which produces an identical value, rather than the documented expectation.
Change the delay to `2`. We can debug further if this doesn't resolve it, however, it's a low-impact change worth running with.
> test(wallet): potentially fix cip36 test race condition

- Dockerfile
- packages/cardano-services/docker-compose.yml
- packages/e2e/docker-compose.yml
The Docker files are currently not covered by e2e tests in CI, so there were some bugs with configuration structure that slipped though, and the latest HTTP service, `asset`, was not appended to the default.
- Fix the malformed string
- Add `asset` to the list
> fix: malformed string and add missing service to Docker defaults

- packages/cardano-services/src/Program/utils.ts
- packages/cardano-services/src/TxWorker/loadTxWorker.ts
- packages/cardano-services/src/TxWorker/utils.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/src/startWorker.ts
- packages/cardano-services/test/Program/utils.test.ts
- packages/cardano-services/test/TxWorker/utils.test.ts
- packages/cardano-services/test/entrypoints.txWorker.test.ts
- packages/rabbitmq/src/TxSubmitWorker.ts
- packages/rabbitmq/src/utils.ts
- packages/rabbitmq/test/TxSubmitWorker.test.ts
Since dependency port resolution using DNS SRV records for the HTTP server is in place, we need also to wrap [TxSubmitWorker](https://github.com/input-output-hk/cardano-js-sdk/blob/8fd7c5267f8250848f954350f58bfef3735aea12/packages/cardano-services/src/TxWorker/loadTxWorker.ts#L26) within abstraction which to perform DNS resolution with retry logic if a connection error occurs between the `worker` and `rabbitmq` broker.
- `TxSubmitWorker` class extends `EventEmitter` to be able to raise events, in our case connection-related.
- Implement `getRunningTxSubmitWorker` abstraction which determines how to instantiate TxSubmitWorker based on the provided args ( with or without service discovery )
- Implement `startTxSubmitWorkerWithDiscovery` which manages worker instances and handles …
> feat: service discovery error handling for TxSubmitWorker

- .github/workflows/nightly.yaml
Need to be able to manually trigger nightly publish workflow
> ci: add on workflow_dispatch in nightly publish workflow

- packages/blockfrost/src/blockfrostAssetProvider.ts
- packages/blockfrost/test/blockfrostAssetProvider.test.ts
When using Blockfrost provider, NFT gets rejected with array in image field when parsing a transaction and Array in description field shown as undefined.
Create AssetInfo.TokenMetadata only from response.metadata, since onchain_metadata refers to cip 25.
> fix(blockfrost): handle arrays in image and description fields

- .github/workflows/nightly.yaml
- lerna.json
Scheduled `nightly` workflow run [failed](https://github.com/input-output-hk/cardano-js-sdk/runs/7551048091?check_suite_focus=true) due to `yarn-project.nix` changing with `yarn install --immutable`.
`git checkout yarn-project.nix` after running `yarn install`. It will be regenerated and git added in a later step (after bumping the packages).
Failed build has [succeeded](https://github.com/input-output-hk/cardano-js-sdk/runs/7553812425?check_suite_focus=true) using workflow from this branch.
[ignore changes under /test when determining version bumps](https://github.com/input-output-hk/cardano-js-sdk/pull/361/commits/2a82349afe4f16cee9d86a96e0e2ba4f3ed0c070)
> ci: fix dirty yarn-project.nix in nightly publish workflow

- packages/cardano-services/docker-compose.yml
- packages/e2e/docker-compose.yml
This is a change to support cardano-db-sync@13, but it was missed or lost in the process of
upgrading. The snapshot expects this new path, otherwise, it will fail during unpacking. This change will only cause existing containers to be rebuilt, which will happen next time the stack is started without intervention. There were also a couple of other issues that I've corrected, see the commit log for details.
> chore: Docker Compose config fixes

- packages/e2e/env/.env.wallet
- packages/e2e/src/factories.ts
- packages/e2e/test/cardano-services/load/load.test.ts
- packages/e2e/test/local-network/local-network.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/delegation.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/metadata.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/pouchdbWalletStores.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/txChaining.test.ts
- packages/e2e/test/wallet/environment.ts
The current implementation using a configurable pair of pool IDs was done when we had the `StakePoolProvider` mocked. Since this is no longer a condition, we can now fetch active pools in the network to delegate to.
- Refactor the `getWallet` function to return the provider instances, enabling tests to also use them directly.
- Query the StakePoolProvider to select an active one randomly, filtering the ensure it's not the same as the current delegation.
- `POOL_ID_1` and `POOL_ID_2` are no longer required, so you can now remove from git ignored `.env`s
> test(e2e): refactor delegation e2e test to use a dynamic pool selection

- packages/cardano-services/README.md
- packages/cardano-services/package.json
We're missing basic docs to assist with deploying the services. Prior to a docs site, we just need the basics in the package README.
- Introduces the package, listing some notable features.
- Examples include:
- using direct or queue-based tx submission
- static or discovered config
> docs(cardano-services): add basics and a couple of examples

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
If the network is configured to have an epoch length duration of less than one day, the APY calculation query throws a division by 0 error.
Make sure the division by zero can not occur in the query.
A small change in the query was introduced to avoid the division by 0.
> fix(cardano-services): fixed a division by 0 on APY calculation

- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/DbSyncNetworkInfoProvider.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/NetworkInfoBuilder.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/queries.ts
- packages/cardano-services/src/Program/services/ogmios.ts
- packages/cardano-services/test/NetworkInfo/DbSyncNetworkInfoProvider/NetworkInfoBuilder.test.ts
- packages/cardano-services/test/NetworkInfo/DbSyncNetworkInfoProvider/__snapshots__/NetworkInfoBuilder.test.ts.snap
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/Program/services/ogmios.test.ts
- packages/cardano-services/test/Program/services/postgres.test.ts
- packages/cardano-services/test/tsconfig.json
- packages/core/src/CardanoNode/types/CardanoNode.ts
- packages/core/src/CardanoNode/util/index.ts
- packages/core/src/CardanoNode/util/stakeDistribution.ts
- packages/core/test/CardanoNode/mocks.ts
- packages/core/test/CardanoNode/util/stakeDistribution.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/delegation.test.ts
- packages/ogmios/src/CardanoNode/OgmiosCardanoNode.ts
- packages/ogmios/test/CardanoNode/OgmiosCardanoNode.test.ts
- packages/ogmios/test/CardanoNode/__snapshots__/OgmiosCardanoNode.test.ts.snap
- packages/ogmios/test/mocks/mockOgmiosServer.ts
Live stake is the current stake that will be used to determine the block leadership schedule of the epoch following the next, and can potentially change with each new chain tip.  Active stake is the stake snapshotted two epochs prior and is now playing a role in block production. Querying the cardano-db-sync schema for the network's live stake is an extremely inefficient operation requiring a multitude of joins and complexity that is very hard to grok, plus it cannot be practically offered with complete precision, only as a cached response. Querying active stake is very efficient, as the database contains a table for the snapshot results, and it also is static for the entire epoch.
Ogmios has a[ LocalStateQuery](https://ogmios.dev/mini-protocols/local-state-query/) to return the current …
> Replace live stake DB query with Local State Query 

- packages/wallet/src/services/DelegationTracker/DelegationTracker.ts
- packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
- packages/wallet/test/services/DelegationTracker/RewardAccounts.test.ts
Undesirable behavior was observed during testing of a remote deployment of the HTTP server with restricted resources, where a wallet without a delegation was requesting all pools via an unbounded query, resulting in resource exhaustion. The fix is two-fold, one contained in this branch, and the other to reject such query as a `400` in the HTTP service (ADP-2120).
This fix stops the observable returned from `createQueryStakePoolsProvider` querying the `StakePoolProvider` if an empty array of pool IDs is passed, as this indicates no data is required, rather than all.
> fix(wallet): stop querying the `StakePoolProvider` for all pools when no current delegation

- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/DbSyncNetworkInfoProvider.ts
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
The extension loads but the test is still not passing on master, the error is related to the `NetworkInfo` service dependency `CardanoNode`, the test is trying to get the `eraSummaries` and the service is throwing an error:
`{"__type":"Error","value":{"reason":"UNHEALTHY","innerError":{"name":"CardanoNodeNotInitializedError","message":"eraSummaries cannot be called until CardanoNode is initialized","stack":"CardanoNodeNotInitializedError: eraSummaries cannot be called until CardanoNode is initialized\n    at OgmiosCardanoNode.eraSummaries`
Revert the not intentional [removal](https://github.com/input-output-hk/cardano-js-sdk/commit/3b65972b74d410312005c9c60d1b48c269b81aaa#diff-93293b161f83ab2bf95474e66fcb0cd45438d4a6b4775fd2761964eb393902a5L109) of `CardanoNode`'s `initialize` and …
> fix(cardano-services): initialize CardanoNode

- packages/e2e/test/blockfrost/getAsset.test.ts
- packages/e2e/test/blockfrost/queryTransactions.test.ts
- packages/e2e/test/web-extension/extension/background/config.ts
Blockfrost e2e tests update after logger mandatory param was added
> fix(e2e): add missing logger param

- packages/wallet/src/SingleAddressWallet.ts
- packages/web-extension/src/messaging/BackgroundMessenger.ts
- packages/web-extension/src/messaging/NonBackgroundMessenger.ts
- packages/web-extension/src/messaging/remoteApi.ts
web-extension messaging sometimes works unreliably (observable doesn't emit)
Problem seems to be that `message$` emits before it is subscribed to (probably synchronously). Replacing `Subject` with `ReplaySubject(1)` seems to fix the issue. 2095fc944c6d1eea47b400d9eaaf507f232aa704
- [fix(wallet): create contextLogger with non-undefined 'name'](https://github.com/input-output-hk/cardano-js-sdk/commit/89a93bd417fa0940fa9b09028d71a8da7900bc72)
- [feat(web-extension): slightly improve messengers log output](https://github.com/input-output-hk/cardano-js-sdk/commit/6d3b82b380959d6d0f5047059a0e1539e4f71e0a)
- Consolidate 2 `pipe` calls into 1 (not part of the main fix in 2095fc944c6d1eea47b400d9eaaf507f232aa704)
> fix: messenger connect race

- packages/blockfrost/src/tsconfig.json
- packages/cardano-services-client/src/tsconfig.json
- packages/cardano-services/src/tsconfig.json
- packages/cardano-services/test/entrypoints.txWorker.test.ts
- packages/cardano-services/test/tsconfig.json
- packages/cip2/src/tsconfig.json
- packages/cip30/src/tsconfig.json
- packages/core/src/tsconfig.json
- packages/e2e/package.json
- packages/e2e/src/tsconfig.json
- packages/e2e/test/blockfrost/getAsset.test.ts
- packages/e2e/test/blockfrost/queryTransactions.test.ts
- packages/e2e/test/tsconfig.json
- packages/e2e/test/web-extension/extension/background/config.ts
- packages/e2e/test/web-extension/tsconfig.json
- packages/golden-test-generator/src/tsconfig.json
- packages/ogmios/src/tsconfig.json
- packages/rabbitmq/src/tsconfig.json
- packages/rabbitmq/test/TxSubmitWorker.test.ts
- packages/rabbitmq/test/docker.ts
- packages/rabbitmq/test/tsconfig.json
- packages/util-dev/src/tsconfig.json
- packages/util-rxjs/src/tsconfig.json
- packages/util/src/tsconfig.json
- packages/wallet/src/tsconfig.json
- packages/wallet/test/tsconfig.json
- packages/web-extension/src/tsconfig.json
- test/tsconfig.json
- `yarn test:build:verify` is not detecting all compile errors. The reason is: in some of our unit tests we are including files from `test` directories of other packages and we achieve this through the `include` root field of `packages/*/test/tsconfig.json` files with a list of `test` directories of other packages from which we need to import files. 
- We experienced some build inconsistencies between build environments. `rootDir` seems to take part in the reason (AFAIK still not perfectly identified) of these inconsistencies.
While investigating the problems I checked the relationships between following `tsconfig.json` options.
- `include`: this is the list of **all the files which compose the project**.  When it appears in our `test` directories it do not includes the files from the …
> build: fix interdependencies between tsconfig.json files

- Dockerfile
Currently, the nix lock file is not being included in the Docker build context, which will result in a new file being generated at built time.
`COPY` the file in the Dockerfile `nodejs-builder` stage.
> build: add yarn-project.nix to Dockerfile build context

- packages/blockfrost/src/blockfrostChainHistoryProvider.ts
- packages/blockfrost/test/blockfrostChainHistoryProvider.test.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/__snapshots__/ChainHistoryBuilder.test.ts.snap
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/cardano-services/test/ChainHistory/__snapshots__/ChainHistoryHttpService.test.ts.snap
- packages/cip2/src/RoundRobinRandomImprove/change.ts
- packages/cip2/src/RoundRobinRandomImprove/index.ts
- packages/cip2/src/RoundRobinRandomImprove/roundRobin.ts
- packages/cip2/src/RoundRobinRandomImprove/util.ts
- packages/cip2/src/types.ts
- packages/cip2/test/RoundRobinRandomImprove.test.ts
- packages/cip2/test/util/properties.ts
- packages/cip2/test/util/tests.ts
- packages/core/src/CSL/util.ts
- packages/core/src/Cardano/types/Transaction.ts
- packages/core/src/Cardano/util/computeImplicitCoin.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/test/mocks/mockChainHistoryProvider.ts
Input selection does not take token mint/burn into consideration.
Add mint/burn support as `InputSelectionParameters.implicitValue.mint`.
- [feat(core): export cslUtil MIN_I64 and MAX_I64 consts](https://github.com/input-output-hk/cardano-js-sdk/commit/618eef04e7c9d2e27d2b0c5a9f1a172d340abde4)
- [refactor!: rm TxAlonzo.implicitCoin](https://github.com/input-output-hk/cardano-js-sdk/commit/167d205dd15c857b229f968ab53a6e52e5504d3f)
- [refactor!: rename InputSelectionParameters implicitCoin->implicitValue.coin](https://github.com/input-output-hk/cardano-js-sdk/commit/3242a0dc63da0e59c4f8536d16758ea19f58a2c0)
> feat: cip2 mint support

- packages/cardano-services/src/InMemoryCache/InMemoryCache.ts
- packages/cardano-services/src/InMemoryCache/defaults.ts
- packages/cardano-services/src/util/validators.ts
- packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
Some methods of `InMemoryCache` class accept a `ttl` parameter; sometimes they expect it expressed in seconds sometimes in minutes.
Changed the interface of `InMemoryCache` class to make all the methods to accept the `ttl` parameter expressed in seconds; 
- Since the `cli` script accepts TTLs in minutes, to not make this breaking change for all the `cli` script users: the parameter validator converts the TTLs from minutes to seconds.
> Uniform ttl parameter of InMemoryCache methods to be expressed in seconds

- Dockerfile
- packages/cardano-services/docker-compose.yml
- packages/e2e/docker-compose.yml
Setting the Compose-specific ENV values within the Dockerfile is the wrong context.
Move the relevant ENVs from the Dockerfile to each Compose file.
This change also fixes the missing `RABBITMQ_URL` from the `http-server` service
> build: move docker-compose service ENVs into compose files

- packages/e2e/package.json
`e2e` package is not being published
[chore(e2e): add package.json publishConfig](https://github.com/input-output-hk/cardano-js-sdk/commit/109ffdc212bdd86ce8ad5b2b302399f5d2f9a7aa)
[chore: regenerate yarn-project.nix](https://github.com/input-output-hk/cardano-js-sdk/commit/159a89a0b83e3dabb03dc3a121d9ac94a6f6e4ed)
> chore: add e2e publish config

- packages/core/src/util/slotCalc.ts
- packages/core/test/util/slotCalc.test.ts
It's possible to configure when particular eras are upgraded, without an upgrade proposal, in testnet `cardano-node` configuration, including the specification of multiple eras in the same epoch.
Both of these configs are valid:
```json
"TestAllegraHardForkAtEpoch": 0,
"TestAlonzoHardForkAtEpoch": 0,
"TestEnableDevelopmentHardForkEras": true,
"TestMaryHardForkAtEpoch": 0,
"TestShelleyHardForkAtEpoch": 0,
```
```json
"TestAllegraHardForkAtEpoch": 2,
"TestAlonzoHardForkAtEpoch": 4,
"TestEnableDevelopmentHardForkEras": true,
"TestMaryHardForkAtEpoch": 3,
"TestShelleyHardForkAtEpoch": 1,
```
Filter the era summaries that represent eras effectively being skipped, which is evidenced by a later era starting in the same slot.
> fix: invalid epoch number calculations when using testnet auto-upgrading configuration

- packages/core/src/util/slotCalc.ts
- packages/core/test/util/slotCalc.test.ts
Hardcoded `testnetEraSummaries` have wrong `{start: {time}}` of shelley era (offset by 1h)
8489da9da98e90e9e3a2198ee19b662ed3475772
> fix: correct hardcoded era summary offset

- packages/cardano-services/README.md
- packages/cardano-services/package.json
Our integration tests DB snapshot is still of _testnet_, but as the e2e tests are now network agnostic and the Docker Hub registry no longer has the required base images, removing support for starting the services makes sense.
- Remove the npm script that simplifies starting the _testnet_ stack
- Update docs to use _preprod_ instead
> chore(cardano-services): remove support for starting a testnet stack

- packages/e2e/test/wallet/SingleAddressWallet/nft.test.ts
The NFT test on the wallet e2e test suite is querying data in the old test network. We must make this test network agnostic to run in any test and production environment.
The test must mints the tokens is going to query
> test(e2e): wallet nft test was made network agnostic

- packages/wallet/src/SingleAddressWallet.ts
- packages/web-extension/src/cip30/initializeBackgroundScript.ts
- packages/web-extension/src/messaging/BackgroundMessenger.ts
- packages/web-extension/src/messaging/NonBackgroundMessenger.ts
- packages/web-extension/src/messaging/index.ts
- packages/web-extension/src/messaging/remoteApi.ts
- packages/web-extension/src/messaging/types.ts
- packages/web-extension/test/messaging/remoteApi.test.ts
Unsubscribing exposed web-extension object keeps a port open.
[fix(web-extension): destroy messenger ports upon unsubscribing exposed object](https://github.com/input-output-hk/cardano-js-sdk/commit/905087b54218e061ae1e19a6377f1a262f8b47d2) 
Some general improvements:
- [fix(wallet): set correct context for utxo and assets tracker loggers](https://github.com/input-output-hk/cardano-js-sdk/commit/7eaea77b8e3a6cc5342e5e8486e965fdb1f3ad99)
- [fix(web-extension): encapsulate potential EmptyError with a new RemoteApiShutdownError](https://github.com/input-output-hk/cardano-js-sdk/commit/d439f271a1784951d7aee72c5615d9ddee3a228d) 
- [refactor(web-extension)!: rename messaging destroy->shutdown for consistent naming](https://github.com/input-output-hk/cardano-js-sdk/commit/caec612382e09993f51f39f5 …
> fix: destroy messenger

- packages/blockfrost/src/BlockfrostToCore.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/queries.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/types.ts
- packages/cardano-services/test/NetworkInfo/DbSyncNetworkInfoProvider/__snapshots__/NetworkInfoBuilder.test.ts.snap
- packages/cip2/src/types.ts
- packages/core/src/Cardano/types/ProtocolParameters.ts
- packages/core/src/Cardano/types/Script.ts
- packages/core/src/Provider/NetworkInfoProvider/types.ts
The type we’ve been inheriting from Ogmios as described by it’s name is invalid:
[refactor: removed Ogmios schema package dependency by AngelCastilloB · Pull Request #388 · input-output-hk/cardano-js-sdk](https://github.com/input-output-hk/cardano-js-sdk/pull/388#discussion_r953396868) 
The reason for this loose nullability is due to context within Ogmios. It’s the type specified for both protocol update objects and the current parameters, which, while it works, is not an accurate model.
We should make each parameter non-nullable, remove the now unnecessary [casting](https://github.com/input-output-hk/cardano-js-sdk/blob/141f2caa1b845d73616437bc9b6ddbd33268f3d0/packages/core/src/Provider/NetworkInfoProvider/types.ts#L3), and fix any tests that are only checking for a limited set of …
> fix: Remove nullability of ProtocolParametersBabbage properties

- packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider.ts
- packages/cardano-services/src/Asset/openApi.json
- packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
- packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
`AssetInfo.tokenMetatdata` is stored in an off-chain registry, which cannot be depended on for returning a match for the given assetIds, nor it's service availability. Currently we’re rethrowing request errors as a Provider error, which is not ideal since it then couples our own service health, as opposed to the desired behaviour of omitting the metadata from the response. 
[cardano-js-sdk/CardanoTokenRegistry.ts at 8fe1cdd7683a7802bebd081616abead292488953 · input-output-hk/cardano-js-sdk](https://github.com/input-output-hk/cardano-js-sdk/blob/8fe1cdd7683a7802bebd081616abead292488953/packages/cardano-services/src/Asset/CardanoTokenRegistry.ts#L151) 
This issue does raise an important question of how can a client differentiate between a response that included a `404` from the registry vs a …
> fix: Gracefully handle `CardanoTokenRegistry` errors during `getAsset` request

- packages/core/src/CSL/coreToCsl/coreToCsl.ts
- packages/core/src/CSL/cslToCore/cslToCore.ts
- packages/core/src/Cardano/types/Transaction.ts
- packages/core/src/Cardano/util/primitives.ts
- packages/core/test/CSL/cslToCore.test.ts
- packages/core/test/Cardano/util/primitives.test.ts
It is not clear what format/encoding the following strings use:
```ts
export type ChainCode = string;
export type AddressAttributes = string;
```
See notes in commit message a217e00161e3e8b86fd1df5cc780fed20d213708
> feat(core): narrow down BootstrapWitness types

- packages/e2e/test/wallet/SingleAddressWallet/delegation.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/metadata.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/multisignature.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/nft.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/pouchDbWalletStores.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/txChaining.test.ts
- packages/e2e/test/wallet/util.ts
There is a race condition between starting the local test network and running the e2e tests, sometimes the e2e test can start before the state of the local test network is fully indexed by dbSync, which causes the tests to fail since the wallet balance is still not available. 
Make the e2e test wallet for balance to be available at the beginning of the test.
> test(e2e): add balance check before running e2e tests

- packages/ogmios/src/CardanoNode/mappers.ts
- packages/ogmios/test/CardanoNode/__snapshots__/OgmiosCardanoNode.test.ts.snap
- packages/ogmios/test/CardanoNode/mappers.test.ts
Slot date is computed incorrectly in SingleAddressWallet
Correctly map `slotLength` returned by Ogmios
> fix(ogmios): correctly map era summary slotLength

- .github/workflows/nightly.yaml
Nightly CI publishes have been failing recently.
The error seems to be inconsistent, so I'm guessing it's a CI resources issue when trying to build all packages. Running `yarn build` before `lerna publish` seems to help ([tried to publish once and it worked](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/3053057180/jobs/4923194329)). The idea is that `tsc` will prime some cache to use when building in `prepack` scripts.
> ci: build before publishing nightly packages

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/types.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/util.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/mappers.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
Run this twice:
`time curl -d '{"filters":{"pledgeMet":true,"status":["active","activating"]},"pagination":{"startAt":0,"limit":10}}' -H "Content-Type: application/json" -X POST https://testnet-dev-backend.dev.lw.iog.io/stake-pool/search`
2nd run (cache should be primed) takes ~12s
The run this twice:
`time curl -d '{"filters":{"status":["active","activating"]},"pagination":{"startAt":0,"limit":10}}' -H "Content-Type: application/json" -X POST https://testnet-dev-backend.dev.lw.iog.io/stake-pool/search`
2nd run takes ~0.3s
After troubleshooting and reproducing the issue locally with the restored latest `db-sync` snapshot, it's found out that the bottleneck is `#builder.queryTotalCount(query, params)` which initially wasn't cached due to its relative simplicity but it turned out its …
> fix: stake pool search with applied pledge met filter

- packages/core/src/util/calcStabilityWindow.ts
- packages/core/src/util/index.ts
- packages/core/test/util/calcStabilityWindow.test.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/services/TransactionReemitter.ts
- packages/wallet/test/SingleAddressWallet/rollback.test.ts
- packages/wallet/test/services/TransactionReemiter.test.ts
The stability window must be calculated to determine which confirmed transactions might be subject to rollback.
[The formula to calculate this window is 3k/f (where k is the security parameter in genesis, and f is the active slot co-efficient parameter in genesis that determines the probability of amount of blocks created in an epoch.)](https://docs.cardano.org/learn/chain-confirmation-versus-transaction-confirmation)
Once NetworkInfo includes the parameters, it should be used to calculate the stability window and use it instead of the hardcoded value.
Apply the stability window formula on the client (wallet) and provide the value as observable where it is needed.
- extend `createTransactionReemitter` with `stabilityWindowSlotsCount$`
- apply the formula to calculate …
> feat: calculate stability window slots count in wallet

- packages/e2e/local-network/scripts/make-babbage.sh
- packages/e2e/local-network/scripts/start.sh
- packages/e2e/local-network/scripts/update-pools-certificate.sh
Currently the local test network is not issuing rewards to delegators due short epoch length (previously 100). 
The epoch length was increased to 500 which seems to be the minimum required for rewards to be issue.
This PR also introduce an update to the pool certificates to add meaningful metadata (pool cost, pool merging, pledge and pool metadata)
> test(e2e): Increase epoch length and update stake pools certificates on the local test network

- packages/blockfrost/src/BlockfrostToCore.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
- packages/core/src/Provider/NetworkInfoProvider/types.ts
#416 introduced an unnecessary breaking change: add more properties to `ProtocolParametersRequiredByWallet`
Rollback the change to `ProtocolParametersRequiredByWallet`
> fix: rollback ProtocolParametersRequiredByWallet type

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
Make stake pool search by ticker and name case insensitive
Replace `SIMILAR TO` sentence by `~*` POSIX regular expression.
Ref: https://stackoverflow.com/questions/7005302/how-to-make-case-insensitive-query-in-postgresql
> feat(cardano-services): make search stake pool case insensitive

- packages/core/src/CSL/coreToCsl/coreToCsl.ts
- packages/core/test/CSL/coreToCsl.test.ts
- packages/core/test/CSL/testData.ts
I commit another change because I found that coreToCsl.txOut doesn't include the datum hash when the attibute _TxOut.datum?_ is defined. 
I added an if statement in the function to convert the 32 bytes hex strting to a DataHash:
``` javascript
export const txOut = (core: Cardano.TxOut): TransactionOutput => {
const cslTxOut = TransactionOutput.new(parseCslAddress(core.address.toString())!, value(core.value));
if (core.datum !== undefined) {
cslTxOut.set_data_hash(DataHash.from_bytes(Buffer.from(core.datum.toString(), 'hex')));
}
return cslTxOut;
};
```
I also added as test data _txOutWithDatum_ and the following unit test, which failed with the old implementation:
``` javascript
it('converts datum to CSL.DataHash', () => {
const cslTxOut = coreToCsl.txOut(txOutWithDatum); …
```
> fix(core): coreToCsl converts datum in txOut function

- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/TxBuilder/types.ts
- packages/wallet/src/types.ts
- packages/wallet/test/integration/withdrawal.test.ts
ADP-2190 Wallet users shouldn’t have to manually withdraw rewards. 
Update SingleAddressWallet implementation to withdraw rewards on every transaction (if available)
removed `withdrawals` property from `InitializeTxProps`
> feat(wallet)!: withdraw rewards on every transaction

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/types.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/__snapshots__/StakePoolBuilder.test.ts.snap
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/mappers.test.ts
- packages/cardano-services/test/StakePool/__snapshots__/StakePoolHttpService.test.ts.snap
Currently pool saturation is being returned as 0. This happens due to a small bug in a `mapEpoch` in the service which maps the dbSync result to a domain type. The query returns `optimal_pool_count`  but the mapping function was expecting it as `pool_optimal_count`.
Fix the mapping function to expect the right field name.
- Small bug was fixed in the pool saturation calculation.
- A new unit test to verify the proper function of the mapping function was added.
> fix(cardano-services): fixed an issue that was causing pool saturation to be always 0

- .github/workflows/nightly.yaml
- README.md
The CI badge on the homepage is misleading, as it's reflecting the pre-merge state which is often not passing. It's better to show the _post-integration_ workflow run. There are also now two more workflows of interest, _nightly_ and _release_ that we could use some more oversight of.
- replace CI with Post-integration
- Add Nightly and Release
See rendered MD here: https://github.com/input-output-hk/cardano-js-sdk/blob/12171b8265fcda1ac6606deabad0874ada3f5558/README.md
> docs: update README workflow badges

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/__snapshots__/ChainHistoryBuilder.test.ts.snap
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/cardano-services/test/ChainHistory/__snapshots__/ChainHistoryHttpService.test.ts.snap
- packages/e2e/test/wallet/SingleAddressWallet/txChainHistory.test.ts
- packages/e2e/test/wallet/util.ts
The `txId` for the inputs is different than the one provided by Blockfrost.
Cardano services have the tx id of the current transaction, Blockfrost has the tx id of the tx that had that input as output
Requests to both `cardano-services` and `blockfrost` in preview:
Extend DB query to extract the correct tx input id which represents the transaction(source) id where the input was spent as an output. We can conclude that the tx input `txId` is equal to the source transaction `id`.
We extend the query because before the final mapping to `Cardano.TxIn` return type, we need both `tx_input_id` and `tx_source_id` to filter and map by.
- extract the correct `tx_source_id` from db and use it as input `txId`
- update the mappings and types
- added a new e2e test
Introduced e2e test - …
> fix(cardano-services): wrong tx onput `txId` value

- packages/wallet/src/TxBuilder/buildTx.ts
- packages/wallet/src/TxBuilder/types.ts
- packages/wallet/test/integration/buildTx.test.ts
ADP-2246
TxBuilder build method should return the input selection and transaction hash. They are needed by the lace, to be displayed.
Include `inputSelection` and `hash` returned by wallet `initializeTx`,  in the `ValidTx` object returned on `build()`
> feat(wallet): tx builder returns inputSelection and hash on build

- packages/cardano-services/src/Asset/DbSyncNftMetadataService.ts
- packages/cardano-services/src/Asset/types.ts
- packages/cardano-services/test/Asset/DbSyncNftMetadataService.test.ts
- packages/core/src/Asset/util/metadatumToCip25.ts
- packages/core/test/Asset/util/metadatumToCip25.test.ts
`DbSyncAssetProvider.getAsset` returns `nftMetadata: undefined` when the asset is not an NFT.
Related to [PR-412 fix: Gracefully handle CardanoTokenRegistry errors during getAsset request ](https://github.com/input-output-hk/cardano-js-sdk/pull/412)
It should return `nftMetadata: null` instead of undefined, similar to `tokenMetadata`.
It should catch `getTokenMetadata` errors and return `undefined`. Clients can then retry the fetch.
> feat(cardano-services): get metadata should return undefined on errors

- packages/ogmios/src/CardanoNode/OgmiosCardanoNode.ts
- packages/ogmios/src/Provider/TxSubmitProvider/ogmiosTxSubmitProvider.ts
- packages/ogmios/src/util.ts
- packages/ogmios/test/util.test.ts
Currently, we're logging the whole WebSocket object as an `info` message on any close event, which is cumbersome and invalid given a particular closure is actually an error. There's also some uncertainty about reconnection behaviour, however this PR is scoped just to address the logging issue.
https://www.rfc-editor.org/rfc/rfc6455#section-7.4.1
- Add a util to `createInteractionContextWithLogger`, that includes the capability to later include a reconnect handler. 
- Refactor the invalid implementations, without introducing restart logic, which will be considered in a later PR
> Fix/Ogmios WebSocket close logging

- packages/e2e/test/wallet/SingleAddressWallet/delegation.test.ts
- packages/wallet/src/SingleAddressWallet.ts
- packages/wallet/src/persistence/inMemoryStores/inMemoryWalletStores.ts
- packages/wallet/src/persistence/pouchDbStores/pouchDbWalletStores.ts
- packages/wallet/src/persistence/types.ts
- packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
- packages/wallet/src/services/SmartTxSubmitProvider.ts
- packages/wallet/src/services/TransactionReemitter.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/src/services/UtxoTracker.ts
- packages/wallet/src/services/index.ts
- packages/wallet/src/services/types.ts
- packages/wallet/test/SingleAddressWallet/load.test.ts
- packages/wallet/test/SingleAddressWallet/methods.test.ts
- packages/wallet/test/SingleAddressWallet/rollback.test.ts
- packages/wallet/test/integration/withdrawal.test.ts
- packages/wallet/test/mocks/mockTxSubmitProvider.ts
- packages/wallet/test/services/DelegationTracker/RewardAccounts.test.ts
- packages/wallet/test/services/SmartTxSubmitProvider.test.ts
- packages/wallet/test/services/TransactionReemitter.test.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
- packages/wallet/test/services/UtxoTracker.test.ts
Transactions should be resubmitted (TransactionReemiter) when:
- Resubmit on certain errors (probably with some timeout and maybe considering online status as well): ProviderFailure.{~~Unknown~~,Unhealthy,ConnectionFailure}
- Previously submitted transaction didn't get into history$ for too long (e.g. due to timing of rollback - when tx was submitted successfully but never got to history$)
See notes in the commits
> fix: re-submit recoverable transactions

- packages/cardano-services/src/Rewards/DbSyncRewardProvider/queries.ts
- packages/wallet/src/SingleAddressWallet/SingleAddressWallet.ts
- packages/wallet/src/SingleAddressWallet/index.ts
- packages/wallet/src/SingleAddressWallet/prepareTx.ts
- packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
- packages/wallet/test/services/DelegationTracker/RewardAccounts.test.ts
Rewards are computed by subtracting in-flight tx withdrawals. Once tx is confirmed, it triggers a re-fetch of rewards balance from the provider. During this re-fetch, the tx is no longer 'in-flight', so there was a brief period of time when rewards balance is incorrect.
See inline comment in the commit
ADP-2275 (see inline comment in [this wip commit](https://github.com/input-output-hk/cardano-js-sdk/commit/131a18ee33148ab55bdb456c0ba5ca7c5d6b49af#diff-a24ba91fcdc49ed6949e92d1ceeef8b221721a0c810cb4f1c54b758a9d243a84R279-R295)).
f50ce5dc84a76a0a5db7426906f13458f1df869f isn't really needed for this PR and is just some preparation work for that parked commit, but I think it's better to merge it now to have less git conflicts later.
> fix(wallet): await for updated rewards after tx confirmation

- packages/cardano-services/src/Program/loadHttpServer.ts
- packages/cardano-services/src/Rewards/DbSyncRewardProvider/DbSyncRewardsProvider.ts
- packages/cardano-services/src/Rewards/DbSyncRewardProvider/RewardsBuilder.ts
- packages/cardano-services/test/Asset/AssetHttpService.test.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/Reward/RewardsHttpService.test.ts
- packages/cardano-services/test/TxSubmit/TxSubmitHttpService.test.ts
This query currently returns unconstrained results, posing a DOS risk.
Since the return type of [rewardsHistory](https://github.com/input-output-hk/cardano-js-sdk/blob/5910f552755e2a3fda75c48437f8534a913ad6c2/packages/cardano-services/src/Rewards/DbSyncRewardProvider/DbSyncRewardsProvider.ts#L18-L21) is a simple map (not a list with multiple items) : `<Map<Cardano.RewardAccount,EpochRewards[]>` and the relation between the `rewardAccounts` arg and mapped response is 1:1 then we might be better just to apply the `props.rewardAccounts` limitation of `PAGINATION_PAGE_SIZE` without pagination of the response.
- apply `rewardAccounts` arg runtime limitation of max page size limit
- extends with missing expect.assertions()
> feat: RewardsProvider.rewardsHistory constraints

- packages/cardano-services-client/test/StakePoolProvider/stakePoolHttpProvider.test.ts
- packages/cardano-services/src/Program/loadHttpServer.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/types.ts
- packages/cardano-services/src/StakePool/openApi.json
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/core/src/Provider/StakePoolProvider/types/StakePoolProvider.ts
- packages/util-dev/test/createStubStakePoolProvider.test.ts
- packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
- packages/wallet/test/mocks/mockChainHistoryProvider.ts
- packages/wallet/test/mocks/mockRewardsProvider.ts
- packages/wallet/test/services/DelegationTracker/RewardAccounts.test.ts
- packages/wallet/test/services/DelegationTracker/RewardsHistory.test.ts
- packages/wallet/test/services/ProviderTracker/TrackedStakePoolProvider.test.ts
Currently the `StakePoolProvider.queryStakePools` query _“Will return all stake pools matching the query if not specified”_. As this interface has been faithfully implemented by the DbSyncStakePoolProvider, the server will run out of memory if queried without pagination.
**Acceptance Criteria**
Type updated to require pagination.
The HTTP response must be paginated and arguments must be passed and enforced at runtime. Interpret the error as a 400 code response in the HTTP service.
Make pagination a configurable option, defaulting to 25. as `PAGINATION_PAGE_SIZE_LIMIT`
StakePoolQueryOptions.identifier should be limited to `PAGINATION_PAGE_SIZE_LIMIT`
- enforce `pagination` as required argument
- add pagination page size limit constraints in the provider
- interpret the error as a 400 code …
> feat!: StakePoolProvider query constraints

- packages/cardano-services-client/src/NetworkInfoProvider/networkInfoHttpProvider.ts
- packages/cardano-services-client/test/NetworkInfo/networkInfoHttpProvider.test.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/DbSyncNetworkInfoProvider.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/NetworkInfoBuilder.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/queries.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/types.ts
- packages/cardano-services/src/NetworkInfo/NetworkInfoHttpService.ts
- packages/cardano-services/src/NetworkInfo/openApi.json
- packages/cardano-services/test/NetworkInfo/DbSyncNetworkInfoProvider/NetworkInfoBuilder.test.ts
- packages/cardano-services/test/NetworkInfo/DbSyncNetworkInfoProvider/__snapshots__/NetworkInfoBuilder.test.ts.snap
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/core/src/Cardano/types/ProtocolParameters.ts
- packages/core/src/Cardano/util/computeImplicitCoin.ts
- packages/core/src/Provider/NetworkInfoProvider/types.ts
- packages/core/test/Cardano/util/computeImplicitCoin.test.ts
- packages/wallet/src/SingleAddressWallet/SingleAddressWallet.ts
- packages/wallet/src/persistence/inMemoryStores/inMemoryWalletStores.ts
- packages/wallet/src/persistence/pouchDbStores/pouchDbWalletStores.ts
- packages/wallet/src/persistence/types.ts
- packages/wallet/src/services/BalanceTracker.ts
- packages/wallet/src/services/ProviderTracker/ProviderStatusTracker.ts
- packages/wallet/src/services/ProviderTracker/TrackedWalletNetworkInfoProvider.ts
- packages/wallet/src/services/WalletUtil.ts
- packages/wallet/src/types.ts
- packages/wallet/test/mocks/mockNetworkInfoProvider.ts
- packages/wallet/test/mocks/mockNetworkInfoProvider2.ts
- packages/wallet/test/services/BalanceTracker.test.ts
- packages/wallet/test/services/ProviderTracker/TrackedWalletNetworkInfoProvider.test.ts
The task is to replace the wallet protocol param types with complete protocol param types.
Provide the complete set of protocol parameters by `cardano-services` (`NetworkInfo` provider) as we extract and map these bits of data from `db-sync`.
- rename method `currentWalletProtocolParameters` to `protocolParameters`
- update `/current-wallet-protocol-parameters` -> `/protocol-parameters`
- remove `ProtocolParametersRequiredByWallet` entirely
- support all protocol params by NetworkInfo and Blockfrost providers
- align code base with the introduced changes
- insert cost models fixture db data for tests
> feat!: Support the complete set of protocol parameters by cardano services

- .github/workflows/nightly.yaml
`nightly` workflow often fails due to not being able to automatically merge `yarn-project.nix` file
Update `nightly` workflow to:
1. Checkout `yarn-project.nix` from `master`, so that it's identical to the one being merged in
2. Regenerate `yarn-project.nix` after merging
It creates 2 extra commits when there are changes in yarn-project.nix when merging. Could potentially reduce it to 2 commits by amending the merge commit instead of adding a commit on top of it. See commits created [here](https://github.com/input-output-hk/cardano-js-sdk/commits/nightly). 
CI nightly run using a workflow from this branch [here](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/3376433258/jobs/5604149590)
> ci: regenerate yarn-project.nix & yarn.lock after nightly merge in master

- .github/workflows/nightly-publish.yaml
- .github/workflows/nightly-test.yaml
- .github/workflows/release.yaml
1. Cancelled nightly workflows have 'succeeded' status. This will make it to attempt to publish the packages if the merge fails.
2. [fails to reset](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/3391733766/jobs/5637178718#step:6:28) CHANGELOGs that don't exist in master
1. Replace cancellation plugin with `exit 1`
2. See commits on release workflow fixes:
- [ci: fix release to restore CHANGELOGs that didn't exist](https://github.com/input-output-hk/cardano-js-sdk/pull/505/commits/d463875ec40cab0f5f8584d50182e5ecb318cdd4)
- [ci: release now attempts to build before making a release to reduce chance of failure](https://github.com/input-output-hk/cardano-js-sdk/pull/505/commits/42e71ceb2858bbfe9c07db5610d50761f85fed25)
- [ci: replace release workflow github.token with …
> ci: nightly and release workflow fixes

- .github/workflows/nightly-test.yaml
We're seeing a failure when testing against the latest, which is currently v19.0.1, and cannot
justify the time spent on investigating, but need this workflow to be functional.
Removing now until we can dedicate some time to debug v19 compat.
> ci: Remove Node.js latest testing from nightly workflow

- .yarnrc.yml
https://github.com/stephank/yarn-plugin-nixify/issues/47
Use the available configuration option to lock the expression path to the repo root.
This makes it possible to run `yarn install` in any workspace directory as per the usual Yarn development practice.
> build: specify nix expression path to prevent path in yarn-project.nix being inferred

- packages/cardano-services/test/jest-setup/docker.ts
CI failure example: [feat!: StakePoolProvider query constraints · input-output-hk/cardano-js-sdk@f8461f1](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/3180001721/jobs/5184154187)
Perform an additional DB check to ensure the PostgreSQL database is being created before proceeding with the test executions.
The CI workflow passed 4 times in a row (manually re-triggered) 🤞🏻
> test(cardano-services): Troubleshoot and resolve flaky CI 'database does not exist'

- packages/e2e/README.md
- packages/e2e/docker-compose.yml
- packages/e2e/local-network/Dockerfile
- packages/e2e/local-network/file-server/SP1.json
- packages/e2e/local-network/file-server/SP2.json
- packages/e2e/local-network/file-server/SP3.json
- packages/e2e/local-network/file-server/index.html
- packages/e2e/local-network/scripts/update-pools-certificate.sh
We need to add a web server to our local network to serve at least small static files as stake pools and asset metadata.
Add to the end-to-end environment a Nginx instance that allows us to serve files directly to the local-network.
Any file added to the `file-server` folder will be served to the docker cluster via `http://files-server/`, for example, `http://files-server/SP1.json`. The contents of this folder can be altered dynamically, and the files will be available instantly to the docker images (no need to restart the container).
It is also possible to access the file server from outside the docker cluster as the instance binds to port `7890` on the host by default:
`http://localhost:7890/SP1.json`
You can override this port mapping by setting the `FILE_SERVER_PORT` environment …
> ADP-2350: Add a local web server to the e2e environment

- packages/e2e/env/.env.load-testing
- packages/e2e/env/.env.local-network
- packages/e2e/test/load-testing/tx-submit-load.test.ts
Looking for a good test to stress the transaction submission, we found that the tx submissions load test could be a good candidate, but it needs some fixes/improvements.
- removed the `try/catch` block around the body of the test which was hiding test failures
- coins are now self sent to the same account to avoid the too many inputs error in subsequent test runs (with high `TRANSACTIONS_NUMBER`)
> test(e2e): load test improvements

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
The cip30 method `signTx` should take and sign an entire transaction, not just the transaction body
update `cip30.ts` to sign an entire transaction, as well as associated tests
> fix(wallet): sign entire transaction in cip30 mapping instead of transaction body

- packages/input-selection/src/selectionConstraints.ts
- packages/input-selection/test/selectionConstraints.test.ts
- packages/util/src/freeable.ts
- packages/util/test/freeable.test.ts
- packages/wallet/src/SingleAddressWallet/SingleAddressWallet.ts
- packages/wallet/src/SingleAddressWallet/prepareTx.ts
Calls computeMinimumCoinQuantity 4 times for every tx change for each asset. If tx is changed too fast it errors with undefined and then RangeError: offset is out of bounds.
Fix some memory leaks when calling CML.
> fix!: create a new CML scope for every call of BuildTx in selection constraints

- .gitignore
`result` is created by `nix build`
`source` is created by `nix develop --unpack`
neither should be tracked by git
Just adding a couple of directories that nix can create to gitignore.
> chore: add paths created by nix to .gitignore

- packages/e2e/test/web-extension/extension/util.ts
Using `chromedriver` 107.*  in local dev env, observed the following error:
_Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
Helper files that use other `browser` commands have to be moved to `before` hook_
Removed unused `ownOrigin` variable.
It was making web-extension tests fail with newer chromedriver versions (107+). The reason was the usage of `browser` like objects outside of tests.
> test(e2e): removed browser usage outside of tests

- flake.nix
- packages/cardano-services/src/Program/services/ogmios.ts
- packages/cardano-services/test/Program/services/ogmios.test.ts
- packages/cardano-services/test/util.ts
The Lace team raised an issue related to OgmiosTxSubmitProvider not being initialized: 
```
{"name":"http-server","hostname":"9d06efc80cb7","pid":1,"level":50,"err":{"message":"submitTx cannot be called until OgmiosTxSubmitProvider is initialized","name":"NotInitializedError","stack":"NotInitializedError: submitTx cannot be called until OgmiosTxSubmitProvider is initialized\n    at OgmiosTxSubmitProvider.submitTx (/nix/store/gg5qhqwjfmyw4xlpvvrgii4sbm4kjzi8-cardano-
```
Setting the Runnable prototype explicitly of the Proxy class abstraction
- set explicitly a Runnable prototype of the Proxy abstractions
> fix(cardano-services): `OgmiosTxSubmitProvider` is not initialized error

- packages/key-management/src/KeyAgentBase.ts
- packages/key-management/src/restoreKeyAgent.ts
- packages/key-management/src/types.ts
- packages/key-management/src/util/ownSignatureKeyPaths.ts
- packages/key-management/test/restoreKeyAgent.test.ts
- packages/key-management/test/util/ownSignaturePaths.test.ts
- packages/wallet/test/SingleAddressWallet/load.test.ts
- packages/wallet/test/SingleAddressWallet/methods.test.ts
- packages/wallet/test/SingleAddressWallet/rollback.test.ts
- packages/wallet/test/hardware/LedgerKeyAgent.test.ts
- packages/wallet/test/hardware/TrezorKeyAgent.test.ts
- packages/wallet/test/mocks/mockData.ts
ownSignatureKeyPaths is currently not checking the type and .rewardAccount of certificates, so it will just blindly sign with stake key any transactions that have any certificates. We need to have some additional logic to determine if a transaction needs to be signed with the stake key.
ownSignatureKeyPaths now inspect all certificates to determine if the transaction must be signed with the wallet stake key.
> ADP-2330 - feat(key-management): ownSignatureKeyPaths now checks for reward accounts in certificates

- packages/key-management/test/util/ownSignaturePaths.test.ts
CI build is blocked currently due to a compile error in one test file.
Fix the compile error on the latest _master_
> fix(key-management): compile error in `key-management` package

- packages/e2e/local-network/Dockerfile
- packages/e2e/local-network/README.md
- packages/e2e/local-network/scripts/install.sh
The IOG Hydra service has been discontinued, which we are relying on for `cardano-node` binaries in the e2e package.
Replace the Hydra URLs with the replacement server.
We no longer need build numbers, so this is a simpler solution to maintain.
> build(e2e): replace cardano-node hydra build URLs

- packages/cardano-services-client/src/index.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/openApi.json
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/cardano-services/test/data-mocks/tx.ts
- packages/core/src/CML/cmlToCore/cmlToCore.ts
- packages/core/src/CML/coreToCml/coreToCml.ts
- packages/core/src/Cardano/types/Script.ts
- packages/core/src/Cardano/types/Transaction.ts
- packages/core/src/Cardano/util/primitives.ts
- packages/core/test/CML/coreToCml.test.ts
- packages/core/test/Cardano/util/primitives.test.ts
- packages/ogmios/src/ogmiosToCore/block.ts
- packages/ogmios/src/ogmiosToCore/tx.ts
- packages/ogmios/src/ogmiosToCore/util.ts
- packages/ogmios/test/ogmiosToCore/__snapshots__/block.test.ts.snap
- packages/ogmios/test/ogmiosToCore/block.test.ts
- packages/ogmios/test/ogmiosToCore/testData.ts
- packages/wallet/src/services/SmartTxSubmitProvider.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/test/SingleAddressWallet/rollback.test.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
Currently, only certificates are mapped. We need to map the rest of the transactions.
Since transaction types are supposed to be backward-compatible, this should be straightforward. Properties not available in every epoch should be `nullable?.`
Search the code for any other era-specific types and see if they can be generalized
Mostly all of them are expressed by commit messages:
- align the name for one of the native script types (`RequireMOf` -> `RequireNOf`)
- change core Block's body type from `HydratedTx[]` to `Tx[]` due to Ogmios translation compatibility as agreed with @mkazlauskas  (`HydratedTxIn.address` is not available in Ogmios types)
- amend the `TxBody.validityInterval` field as `optional` due to Ogmios compatibility (some of the props are introduced after a specific era in …
> feat: Introduce Ogmios transaction to core mapping

- packages/cardano-services/src/Http/HttpServer.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/NetworkInfoBuilder.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/queries.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/types.ts
- packages/cardano-services/src/util/DbSyncProvider/DbSyncProvider.ts
- packages/cardano-services/src/util/DbSyncProvider/util.ts
- packages/cardano-services/test/Asset/AssetHttpService.test.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/Http/HttpServer.test.ts
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/Program/services/ogmios.test.ts
- packages/cardano-services/test/Program/services/postgres.test.ts
- packages/cardano-services/test/Reward/RewardsHttpService.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
- packages/cardano-services/test/cli.test.ts
- packages/core/src/Provider/Provider.ts
- packages/core/test/CardanoNode/mocks.ts
- packages/ogmios/test/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.test.ts
Not ok health check response may not give enough information about the reason of the failed check.
Added `projectedTip` to the `healthCheck` response of the `Provider`s extending `DbSyncProvider`.
- Since the `findLastBlockNo` query used by `DbSyncProvider.healthCheck` becomes as the `findLedgerTip` from `DbSyncNetworkInfoProvider.queryLedgerTip`; the second one was removed to reduce code repetition.
- The same changed was applied the the relative `LedgerTipModel` interface.
> Feat health check enhancement

- packages/cardano-services/docker-compose.yml
- packages/e2e/docker-compose.yml
A new release of DBSync has been tagged (13.1.0.0 ). We must update our docker-compose files to bump the DBSync version.
> chore: bump cardano-db-sync to version 13.1.0.0

- packages/core/src/CML/cmlToCore/cmlToCore.ts
- packages/core/src/CML/coreToCml/coreToCml.ts
- packages/core/test/CML/testData.ts
Add missing conversations to both  `cmlToCore` and `coreToCml` for all transaction properties in the current ledger era (Babbage).
Added tx witness conversion (`core` to `CML` and `CML` to `core`) of:
- redeemers
- bootstrap (fixed)
- datums (`plutus_data` in CML)
- scripts (native, plutusv1, plutusv2)
- extend tx witness set conversions in `coreToCml` and `cmlToCore`
- extend tx test data in order to verify that the conversion works as expected from/to core/CML (covered in unit tests)
> feat(core): add missing tx core to CML and CML to core conversions 

- packages/wallet/src/services/DelegationTracker/RewardsHistory.ts
- packages/wallet/test/services/DelegationTracker/RewardsHistory.test.ts
Some Lace Open Beta testing feedback has highlighted that the “total rewards” displayed (in the delegation centre) are incorrect when compared to Eternl or [Cardano Explorer | Stake pools | Cexplorer.io](http://preprod.cexplorer.io/). For the user who reported this, their rewards balance shown was 37.31 tADA (incorrect), according to Eternl and [Cexplorer.io](http://cexplorer.io/) their actual “total rewards” were 32.73 tADA (correct). This is causing confusion for users. Other users have not reported this yet, and this may be an issue when restoring a wallet that already has staking rewards available. 
The value the user is familiar with & reporting is actually "Rewards Withdrawn" which is arguably different to “Total Rewards”.
Investigation details and solution in the …
> fix(wallet):  Incorrect Rewards Amount

- packages/wallet/src/persistence/pouchDbStores/PouchDbStore.ts
- packages/wallet/test/persistence/pouchDbStores.test.ts
By default, PouchDB stores all document revisions forever. SingleAddressWallet doesn’t take advantage of it, so we should keep it small.
Enable [auto-compaction](https://pouchdb.com/guides/compact-and-destroy.html#auto-compaction).
> feat(wallet): Enable pouchdb auto-compaction

- packages/core/src/Cardano/types/Address.ts
- packages/core/test/Cardano/util/address.test.ts
- packages/dapp-connector/src/WalletApi/types.ts
- packages/dapp-connector/test/WalletApi/Cip30Wallet.test.ts
- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
Using the signData method of cardano-js-sdk with a test dapp with a hex encoded address throws a DataSignError code 2 (Invalid address). This is because cardano-js-sdk only expects it to be in bech32 format.
According to the CIP-30 spec, the address argument should accept either bech32 or hex-encoded bytes. However, it seems that the cardano-js-sdk only accepts bech32. Support for hex-encoded addresses should be added.
Accept hex encoded address.
> fix: cip30 wallet has to accept hex encoded address

- packages/wallet/src/SingleAddressWallet/SingleAddressWallet.ts
- packages/wallet/src/services/AssetsTracker.ts
- packages/wallet/src/services/DelegationTracker/DelegationTracker.ts
- packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
- packages/wallet/src/services/DelegationTracker/RewardsHistory.ts
- packages/wallet/src/services/SupplyDistributionTracker.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/src/services/UtxoTracker.ts
- packages/wallet/src/services/util/coldObservableProvider.ts
- packages/wallet/src/types.ts
- packages/wallet/test/SingleAddressWallet/load.test.ts
- packages/wallet/test/services/DelegationTracker/RewardsHistory.test.ts
- packages/wallet/test/services/util/coldObservableProvider.test.ts
- packages/web-extension/src/observableWallet/util.ts
Currently the wallet is retrying operations even the raised error can't be tried.
Added a _filter_ to `coldObservableProvider` retry strategy.
Added a `SingleAddressWallet.error$` observable which emits those errors that can't be retried.
> feat(wallet): adds a retry strategy to single address wallet

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/mappers.test.ts
We have a problem on stake pool saturation compute which is also causing a bad sorting in case the stake pool query is performed sorting by saturation
Fixed the DB query which performs that compute
Simplified stake pool metric computation removing an additional saturation compute and using the data got from DB instead.
> stake pool saturation compute

- packages/cardano-services/copy-assets.sh
- packages/cardano-services/src/Http/HttpServer.ts
- packages/cardano-services/src/Http/openApi.json
- packages/cardano-services/src/Http/types.ts
- packages/cardano-services/src/Program/Options.ts
- packages/cardano-services/src/Program/loadHttpServer.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/src/util/validators.ts
- packages/cardano-services/test/Http/HttpServer.test.ts
- packages/cardano-services/test/cli.test.ts
There was a [contributed a solution ](https://github.com/input-output-hk/cardano-js-sdk/pull/496)to expose deployment metadata, which has made it possible to understand critical details that are important for dev and test engineers, and is being consumed in this wallet-world document https://github.com/input-output-hk/wallet-world/blob/master/ENVIRONMENTS.md. Feedback has been provided in the PR about how to turn it into a feature we can support, but due to time constraints it was decided to merge as-is, then dedicate some time for improvements in a future sprint.
With provided a valid BUILD_INFO JSON format
With an invalid BUILD_INFO JSON format on server startup
- introduce `ServerMetadata` type
- add `--build-info` CLI arg and `BUILD_INFO` env
- add metadata JSON validation on startup …
> feat(cardano-services)!: upgrade /meta endpoint

- packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
- packages/cardano-services/src/Asset/DbSyncNftMetadataService.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/Metadata/DbSyncMetadataService.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
- packages/cardano-services/src/Rewards/DbSyncRewardProvider/mappers.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
- packages/cardano-services/src/Utxo/DbSyncUtxoProvider/mappers.ts
- packages/cardano-services/src/util/DbSyncProvider/DbSyncProvider.ts
- packages/cardano-services/test/Asset/AssetBuilder.test.ts
- packages/cardano-services/test/Asset/AssetHttpService.test.ts
- packages/cardano-services/test/Asset/fixtures/FixtureBuilder.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/ChainHistory/fixtures/FixtureBuilder.ts
- packages/cardano-services/test/Metadata/DbSyncMetadataService.test.ts
- packages/cardano-services/test/Metadata/fixtures/FixtureBuilder.ts
- packages/cardano-services/test/Reward/RewardsHttpService.test.ts
- packages/cardano-services/test/Reward/fixtures/FixtureBuilder.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/StakePool/fixtures/FixtureBuilder.ts
- packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
- packages/cardano-services/test/Utxo/fixtures/FixtureBuilder.ts
Based on the "**Loading SPIKE: Wallet with large # of txs uses a lot of CPU in cardano-services**"  and the profiled processed data, we could apply some optimizations in cardano-services backend in order to reduce/resolve the high CPU errors during the performing of intensive E2E tests which are opening/closing a  “heavy” wallet multiple times in a short period of time.
- remove the usage of core types with validation in mappings/utils when data comes from the database as we trust the format of the stored addresses. 
- each validation is hosted to the test scope
This is not only about `Cardano.Address()` validation but also other validations such as `TransactionId()`, `BlockId()`, `RewardAccount()`, and more. The ones which don't perform a type validation should be used in mappers as it …
> perf(cardano-services): `Cardano-services` optimizations based on processed profiled data

- packages/cardano-services/src/util/validators.ts
- packages/cardano-services/test/util/validators.test.ts
Currently, both [DbCacheTtl](https://github.com/input-output-hk/cardano-js-sdk/blob/e9c3a5b74a2cc1f69c53f562af8a5b4e693bd20a/packages/cardano-services/src/Program/Options.ts#L4) CLI arg and [InMemoryCache](https://github.com/input-output-hk/cardano-js-sdk/blob/670d0c12589a4385b72c445e5f332e195f3b8000/packages/cardano-services/src/InMemoryCache/InMemoryCache.ts#L10-L16) are aligned and accept the TTL value in seconds since the latest PR [update](https://github.com/input-output-hk/cardano-js-sdk/pull/530/commits/f0eb80f73e61ea48f10809fb3c329fb5c4022e6b).
Noticed we forgot to update the [cacheTtlValidator](https://github.com/input-output-hk/cardano-js-sdk/blob/e9c3a5b74a2cc1f69c53f562af8a5b4e693bd20a/packages/cardano-services/src/util/validators.ts#L37-L46) itself - there is no need to …
> fix(cardano-services): Fix cache TTL validator

- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
- packages/core/src/Cardano/types/Genesis.ts
- packages/core/src/Cardano/util/index.ts
- packages/core/src/CardanoNode/types/CardanoNode.ts
- packages/core/src/util/index.ts
- packages/core/src/util/slotCalc.ts
- packages/core/src/util/time.ts
- packages/core/test/CardanoNode/mocks.ts
- packages/core/test/util/slotCalc.test.ts
- packages/core/test/util/time.test.ts
- packages/e2e/test/util.ts
- packages/ogmios/src/CardanoNode/mappers.ts
- packages/ogmios/src/ogmiosToCore/genesis.ts
- packages/ogmios/test/CardanoNode/mappers.test.ts
- packages/projection/test/events/genesisToEraSummary.ts
- packages/projection/test/operators/withEpochNo.test.ts
- packages/util-dev/src/eraSummaries.ts
- packages/wallet/src/SingleAddressWallet/prepareTx.ts
- packages/wallet/src/Transaction/ensureValidityInterval.ts
- packages/wallet/src/services/TransactionReemitter.ts
- packages/wallet/test/Transaction/ensureValidityInterval.test.ts
- packages/wallet/test/mocks/mockData.ts
TTL is calculated as 3600 slots, which should be 1h provided that the slot length is 1s.
Use slotLength to calculate the TTL to 2h
- Updated CompactGenesis.slotLength type from `number` to `Seconds`.
-  Updated EraSummary.parameters.slotLength type from `number` to `Milliseconds`.
> Convert static TTL to be calculated from slotLength

- packages/core/src/Asset/util/metadatumToCip25.ts
- packages/core/test/Asset/util/metadatumToCip25.test.ts
Currently, we return `null` for the whole [NftMetadata](https://github.com/input-output-hk/cardano-js-sdk/blob/f92bca87dbc84ae1ad58daef6017d9a9e86a411a/packages/core/src/Asset/types/NftMetadata.ts#L44-L55) if `metadatum` input has missing data fields. 
We need to omit those ones with invalid format/missing and return the rest data as nft metadata.
- omits NFT metadata files with missing fields (`name`, `src`, `mediaType`)
> fix(core): omits NFT metadata files with invalid format

- packages/cardano-services/src/Http/HttpService.ts
- packages/cardano-services/src/TxSubmit/rabbitmq/TxSubmitWorker.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/Reward/RewardsHttpService.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
We're currently lacking detail to help understand the reason for throwing `Provider.Unhealthy` errors.
Include the `healthCheck` response as stringified JSON in the error detail. I've elected to leave [this](https://github.com/input-output-hk/cardano-js-sdk/blob/1058e5491d19b34789289826250055f6728ca148/packages/cardano-services/src/TxSubmit/TxSubmitHttpService.ts#L41-L42) instance alone due to the error handling logic being different and the intent to refactor it anyway.
``` console
{"name":"http-server","hostname":"741e2e41edef","pid":1,"level":30,"msg":"[OgmiosCardanoNode] Initialized","time":"2023-02-02T12:26:08.726Z","v":0}
{"name":"http-server","hostname":"741e2e41edef","pid":1,"level":30,"msg":"[asset] Initializing...","time":"2023-02-02T12:26:08.726Z","v":0}
ProviderError: …
```
> feat(cardano-services): include healthCheck response as detail in Provider.Unhealthy errors

- packages/cardano-services/src/Metadata/mappers.ts
- packages/cardano-services/src/Metadata/queries.ts
- packages/cardano-services/src/Metadata/types.ts
- packages/cardano-services/test/Metadata/mappers.test.ts
- packages/core/package.json
- packages/core/src/Asset/util/metadatumToCip25.ts
- packages/core/test/Asset/util/metadatumToCip25.test.ts
- packages/e2e/README.md
- packages/e2e/docker-compose-dev.yml
- packages/e2e/package.json
- packages/e2e/test/wallet/SingleAddressWallet/nft.test.ts
- yarn.lock
We are currently supporting CIP-0025 v1, but not v2
Changed `metadatumToCip25` to support CIP-0025 version 2 as well.
-  added the development version of local-network;
- NFT metadata are no longer read from DB in json format as it can be prone to ambiguity; now are read in raw bytes format;
- added an e2e test to assert CIP-0025 v2 is supported.
> Add support for CIP-0025 version 2

- packages/cardano-services-client/test/tsconfig.json
- packages/cardano-services/src/tsconfig.json
- packages/e2e/src/tsconfig.json
- packages/governance/src/tsconfig.json
- packages/governance/test/tsconfig.json
- packages/key-management/src/LedgerKeyAgent.ts
- packages/key-management/src/tsconfig.json
- packages/key-management/src/util/mapHardwareSigningData.ts
- packages/key-management/test/tsconfig.json
- packages/ogmios/src/tsconfig.json
- packages/projection/src/tsconfig.json
- packages/projection/test/tsconfig.json
- packages/wallet/src/tsconfig.json
- packages/wallet/test/SingleAddressWallet/load.test.ts
- packages/wallet/test/hardware/LedgerKeyAgent.test.ts
- packages/wallet/test/mocks/mockChainHistoryProvider.ts
- packages/wallet/test/mocks/mockRewardsProvider.ts
- packages/wallet/test/mocks/mockUtxoProvider.ts
- packages/wallet/test/tsconfig.json
- packages/web-extension/test/tsconfig.json
Ledger was signing a different transaction hash due to incorrect property name when mapping transaction props
Fix it to the correct property name and also add a check to throw an error if Ledger signs a different transaction hash
A few chores that fix minor issues with SDK setup:
- 389f8d4eff9c29543ff4a14c282ec87107635bd7
- 5a96d0b2f0829159b0046848cb8c7473cbdccfdd
> fix: ledger mapper validity interval prop name

- flake.nix
It was missing since this PR landed: https://github.com/input-output-hk/cardano-js-sdk/pull/589
> build: Add crypto package to the Nix build

- packages/e2e/test/artillery/wallet-restoration/WalletRestoration.ts
- packages/e2e/test/artillery/wallet-restoration/WalletRestoration.yml
I found one issue in debug log severity while performing a bunch of load test executions - the wallet restoration scenario uses one and the same fetched address from DB as the exposed [walletRestoration](https://github.com/input-output-hk/cardano-js-sdk/blob/90de06309ddccd971c8ba5c95e1ee23761891f31/packages/e2e/test/artillery/wallet-restoration/WalletRestoration.ts#L54-L87) function doesn’t iterate over all fetched addresses. 
The issue is caused due to the index variable which tracks the current address from the addresses found list. The walletRestoration function is invoked for each new virtual user, so the index should be located in the global scope rather than the function scope, and then incremented accordingly by each invocation.
- fix DB addresses traversing, move current address …
> fix(e2e): wallet restoration scenario

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/util.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/core/src/Provider/StakePoolProvider/types/StakePoolProvider.ts
Following our dev huddle with the team, we decided to change the default behavior of Stake pool data fetching with defaulting rewardsHistoryLimit to 3 if not provided as an argument. That would be one of the optimizations related to the bad performance of the stake pool’s load test against `mainnet` .
- default rewards history limit to 3 if not specified
> feat: update rewards history limit default

- packages/e2e/test/util.ts
normalizeTxBody sorts inputs by txId.
If inputs are from same txId but different indices, sorting will ignore the indices.
Sort by index too
> test(e2e): fix sorting for inputs from same txId

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/types.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/util.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/StakePool/fixtures/queries.ts
Due to recent investigations we discovered we have two bugs in stake pools search related queries.
1. In order compute the _saturation_, the total staked amount is required: we are currently using the total UTXOs amount;
2. in case of phase 2 validation fail, **db-sync** stores the collateral inputs and outputs in `tx_in` and `tx_out` as if they were non collateral: we are excluding these UTXOs
1. Replaced the query to get total UTXOs with the call to `OgmiosCardanoNode` to get the required value.
2. Removed the `tx.valid_contract = TRUE` condition from the `WHERE` clauses in stake pools search related queries.
> Fix stake pools queries fixes

- packages/core/src/Cardano/Address/PaymentAddress.ts
- packages/e2e/src/scripts/mnemonic.ts
- packages/e2e/test/util.ts
- packages/key-management/src/util/mapHardwareSigningData.ts
- packages/key-management/src/util/ownSignatureKeyPaths.ts
- packages/key-management/test/InMemoryKeyAgent.test.ts
- packages/key-management/test/KeyAgentBase.test.ts
- packages/key-management/test/mocks/mockKeyAgentDependencies.ts
- packages/key-management/test/restoreKeyAgent.test.ts
- packages/key-management/test/tsconfig.json
- packages/key-management/test/util/createAsyncKeyAgent.test.ts
- packages/key-management/test/util/ownSignaturePaths.test.ts
- packages/wallet/src/services/WalletUtil.ts
- packages/wallet/test/SingleAddressWallet/methods.test.ts
- packages/wallet/test/services/WalletUtil.test.ts
Applications wishing to display Values relating to the resolved input need to independently fetch the entire transaction to resolve every input. This is sub-optimal in both needing to remotely fetch transactions already present in the wallet, and that most of the data is not needed, so the we’re placing significant unnecessary load on the provider backend. As a result, the UX is impacted as a result of network latency.
Rename the function and return `{address, value}` instead of just the address.
> feat!: upgrade resolveInputAddress to resolveInput

- packages/input-selection/src/RoundRobinRandomImprove/change.ts
- packages/input-selection/test/change.test.ts
The was a bug in the `coalesceChangeBundlesForMinCoinRequirement` function used internally by `roundRobinSelection`. This function must ensure that all change bundles meet the minAdaRequired. The bundles would be sorted by coin value and then it would iterate in ascending order until it found bundle that meet the requirement, this meant that if there was a bungle with low coin value that meet the requirement and a bundle with higher coin value that didn't it would go undetected and the bundle would not be coalesced.
Fix the `coalesceChangeBundlesForMinCoinRequirement` function to make sure all bundles are verified and coalesced if needed.
- The coalesceChangeBundlesForMinCoinRequirement function should now verify all bundles.
- Added several unit test to the …
> fix(input-selection): roundRobinSelection now ensures all change bundles meet minRequiredAda

- packages/crypto/package.json
- packages/util-dev/package.json
A couple of packages have `@types/*` packages listed as `dependencies`, rather than `devDependencies`. This causes complexities when consuming the package in some environments.
Move them to `devDependencies`
> build: correct invalid production dependencies

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/src/Metadata/DbSyncMetadataService.ts
- packages/cardano-services/src/Metadata/queries.ts
- packages/cardano-services/src/Metadata/types.ts
- packages/cardano-services/src/Metadata/util.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
The `/chain-history/txs/by-addresses` endpoint (called by wallet restoration procedure) may take a long time depending on the number of the transactions affecting the addresses.
The `transactionsByAddresses` exposed function takes advantage from `transactionsByHashes` exposed function.
- Added a new `transactionsByIds` internal function.
- Changed the two previously said function to call the new one.
This let to change the main query performed by `transactionsByAddresses` to return the `tx.id` rather than `tx.hash` optimizing it.
Changed all the `ChainHistoryBuilder` methods called by `transactionsByHashes` to accept `tx.id` rather than `tx.hash`.
> perf: Optimize transactions by addresses SQL queries

- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/mappers.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/cli.test.ts
On _mainnet_ the current solution of calculating stake pool APY, to cache for later queries, is too resource intensive. As a short-term solution it's acceptable to omit this field from the response.
- Add support for disabling select fields from the Stake Pool provider search response
- Add an option to the CLI to disable the APY metric
New PR for the same branch reviewed in https://github.com/input-output-hk/cardano-js-sdk/pull/609
> feat(cardano-services): support disabling stake pool APY metric

- packages/cardano-services/src/Program/options/postgres.ts
- packages/cardano-services/src/Program/services/postgres.ts
- packages/cardano-services/test/cli.test.ts
There's no exposed interface to control the pgpool size, which impacts ability to tune the application at runtime.
- Plumb in the `PoolConfig` `max` property, exposed on the CLI. The original type covered the previous options, but it was technically incorrect.
> feat(cardano-services): configurable pgpool size

- packages/cardano-services/package.json
The default docker timeout between sending signal 1 and signal 9 to a process while stopping the container is 10 seconds.
The mainnet node may take a bit longer to correctly shutdown: in such cases, the next start takes about 25 minutes to recheck all the tx history.
Increased the said timeout to 30 seconds.
> docker compose down timeout between signals 1 and 9

- packages/cardano-services/src/Http/HttpService.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/Reward/RewardsHttpService.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/TxSubmit/TxSubmitHttpService.test.ts
- packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
- packages/cardano-services/test/cli.test.ts
Change from throwing an error to logging a warning if the `HttpService` provider health is
not ok on init, to ensure it always starts, facilitating improved metrics and usability.
The original intent was that we could have assurance at startup that the service is "ready",
but that's a fairly weak situation, since the provider health could immediately revert, so
the client just gets a false sense of security. Administrators will get a warning in the logs,
and clients will now be able to use the /health endpoint to make the correct decision for
their context, with a single approach to dealing with unhealthy provider exceptions.
Log a warning instead of throwing an error in the `HttpService` initialisation method.
> refactor(cardano-services): stop throwing provider unhealthy errors from HttpService init

- packages/cardano-services/src/Http/HttpService.ts
```
export interface Logger {
trace(message?: any, ...optionalParams: any[]): void;
debug(message?: any, ...optionalParams: any[]): void;
info(message?: any, ...optionalParams: any[]): void;
warn(message?: any, ...optionalParams: any[]): void;
error(message?: any, ...optionalParams: any[]): void;
[x: string]: any;
}
```
This is the interface from `ts-log` which makes us prone to the error fixed in this PR.
Just emergency fixed the effect problem, not the source problem.
> fix(cardano-service): fixes a log called method

- packages/cardano-services/src/util/DbSyncProvider/DbSyncProvider.ts
- packages/cardano-services/test/util/DbSyncProvider/DbSyncProvider.test.ts
- packages/ogmios/src/CardanoNode/OgmiosCardanoNode.ts
- packages/ogmios/src/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.ts
- packages/ogmios/test/CardanoNode/OgmiosCardanoNode.test.ts
- packages/ogmios/test/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.test.ts
- packages/ogmios/test/mocks/mockOgmiosServer.ts
- packages/ogmios/test/mocks/types.ts
The current health check functions have the potential to throw, which is invalid behaviour given an internal error should be interpreted as unhealthy state.
- This fix improves: `DbSyncProvider`, `OgmiosCardanoNode`, and `OgmiosTxSubmitProvider`.
- Catch all errors, log instead of throw, report the state as unhealthy
- Add missing tests to cover the desired behaviour
- Move Ogmios health check logic and mapping to static method, to reduce duplication in other modules.
> fix: always return a healthcheck response, logging errors instead of throwing

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
stake-pool/search endpoint was returning `{"reason":"BAD_REQUEST","detail":"APY metric is disabled"}` when the query was sorting using APY and the APY calculation was disabled on the backend.
Instead of throwing an error, the backend will set the default sorting under such condition.
> fix(cardano-services): stake-pool APY sorted search no longer returns error when APY is disabled

- packages/cardano-services/test/cli.test.ts
The CLI test is producing hard to debug failures in CI. There's a fragile assertion that swallows the underlying failure, and we're blind to the child process failures since their output is not logged.
- Improve assertion to better reveal failure
- Add a configurable logger to the CLI tests
Not in scope is a way to dynamically set the logger level, so for now, if needing to debug, we can just update the min level in the code. Ideally we should be able to choose this at runtime, or use some other indicator such as commit message content to set it in the workflow.
> test(cardano-services): improve CLI test - assertion and logging

- packages/cardano-services/test/cli.test.ts
- packages/cardano-services/test/jest-setup/jest-setup.ts
`yarn workspace @cardano-sdk/cardano-services test` suffers some flakiness.
Handling the output chunks should resolve one source of flakiness.
- The change to `jest-setup.ts` does not actually addresses the other source of flakiness, but at least makes the not yet identified error to immediately throw rather than making the test hanging silently. Hopefully this can give us some more info to address the root cause.
- Fixed 4 occurrences of the typo `--service_names` instead of `--service-names`
- `dataMatchOnError` is now required to be sure the got error is the expected one.
> yarn test flakiness

- packages/cardano-services/src/cli.ts
Nightly builds have been failing on Node v14
Process is not existing on unhandledRejections by default in Node 14. Explicitly exit when it happens.
> fix(cardano-services): explicitly process.exit(1) on unhandledRejections

- packages/dapp-connector/README.md
While exploring the code base I noticed there is a broken link to README file so I fixed It.
> docs: fix broken `web-extension` link

- packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/Asset/AssetHttpService.test.ts
- packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
- packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
- packages/cardano-services/test/Asset/fixtures/mocks.ts
- packages/cardano-services/test/StakePool/HttpStakePoolMetadataService/HttpMetadataService.test.ts
- packages/cardano-services/test/cli.test.ts
- packages/util-dev/src/createGenericMockServer.ts
We need to expose an interface for request timeouts to external sources such as the TokenMetadata registry, so it’s configurable while performing fetching through HTTP.
Logged variation of internal network errors related to the Token Metadata Server
- expose `TOKEN_METADATA_REQUEST_TIMEOUT` env var
- expose `--token-metadata-request-timeout` CLI arg
- use default request timeout of `3` seconds for the token metadata registry
- log corresponding extended error message when the client doesn't get the actual error
- refactor `mockTokenRegistry()` with async handler
> feat: Make request timeout to external services configurable

- packages/cardano-services/src/util/DbSyncProvider/util.ts
The query executed on polling by wallets to get the ledger tip takes about 500ms on _mainnet_.
Rewrote the query in a more optimized way.
> feat(cardano-services): optimizes the query to get the ledger tip

- packages/e2e/package.json
- packages/e2e/test/artillery/wallet-restoration/WalletRestoration.ts
- packages/e2e/test/load-test-custom/wallet-restoration/wallet-restoration.test.ts
- packages/e2e/test/util.ts
Test for simulation of concurrent wallet restoration workload from specified number of users.
Process
Test gradually increase load from 1 user to specified number of users
Time measured till last wallet in the batch restored
Parameters
MAX_USERS - max number of concurrent wallet restorations in the batch
RESTORATION_TIMEOUT -  max wait time in milliseconds 
Groups - (currently hardcoded) users divided by number of tx in wallet to restore
Output written to csv file with 2 columns number of concurrent users and restoration time
> test: concurrent users metrics

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
- packages/cardano-services/src/Metadata/DbSyncMetadataService.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.ts
- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/queries.ts
PostgreSQL has the concept of a [prepared statement](https://www.postgresql.org/docs/9.3/static/sql-prepare.html). `node-postgres` supports this by supplying a name parameter to the query config object. If you supply a name parameter the query execution plan will be cached on the PostgreSQL server on a per-connection basis.
We need to optimize the paginated queries and take the advantage of prepared statements.
Check the commit messages
- `withPagination()` is refactored to use parametrized queries with `$` signs
- added prepared statements support for `txs-by-addresses` queries
> feat: Parametrize pagination queries and add support for prepared statements in txs by addresses

- packages/cardano-services/src/Http/HttpServer.ts
- packages/cardano-services/test/cli.test.ts
The current metrics exposed by[npm: express-prom-bundle](https://www.npmjs.com/package/express-prom-bundle) has no granular metrics per route.
We need to enable it and check if a prom client needs an additional path normalization function.
> feat(cardano-services): add path metrics on provider server

- packages/cardano-services/test/Program/services/ogmios.test.ts
- packages/ogmios/package.json
- packages/ogmios/src/Ogmios/TxSubmissionClient.ts
- packages/ogmios/src/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.ts
We discovered an ogmios client bug affecting the submission of multiple transactions through a single long lasting WebSocket connection.
Basically the transaction submission client needs to implement the mirror/reflection feature as the [query client](https://github.com/CardanoSolutions/ogmios/blob/31a2d6e8ca17e1e6e7eb4bf72a041bece49ec80e/clients/TypeScript/packages/client/src/StateQuery/Query.ts#L28) does.
Implement the mirror/reflection feature from the StateQuery client in the TxSubmit client.
> feat(ogmios): ogmios TxSubmit client now uses a long-running ws connection

- packages/ogmios/src/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.ts
We're currently not logging successful tx submissions, so can only rely on requests for gathering metrics on system metrics.
Log the tx hash returned by Ogmios.
The default logging level will now include a log of all submitted transactions. This may appear to be a bit noisy but can be reworked with a more sophisticated metrics solution in future. For now it's not too impactful, and does fit within the "info" category IMO.
> feat(ogmios): log successful transaction submission with info level

- packages/cardano-services-client/src/AssetInfoProvider/assetInfoHttpProvider.ts
- packages/cardano-services-client/test/AssetInfoProvider/assetInfoHttpProvider.test.ts
- packages/cardano-services/src/Asset/AssetHttpService.ts
- packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
- packages/cardano-services/src/Asset/openApi.json
- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/test/Asset/AssetHttpService.test.ts
- packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
- packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
- packages/cardano-services/test/cli.test.ts
- packages/core/src/Asset/types/TokenMetadata.ts
- packages/core/src/Provider/AssetProvider/types.ts
- packages/util-rxjs/src/concatAndCombineLatest.ts
- packages/util-rxjs/src/index.ts
- packages/util-rxjs/test/concatAndCombineLatest.test.ts
- packages/wallet/src/services/AssetsTracker.ts
- packages/wallet/src/services/ProviderTracker/TrackedAssetProvider.ts
- packages/wallet/test/mocks/mockAssetProvider.ts
- packages/wallet/test/services/AssetsTracker.test.ts
A good optimization would be to batch the requests - perform from the wallet just 1 request `provider.getAssets(ids)` instead of `N` requests by single id (could be more than `1k` per wallet, for instance, a random wallet I picked `has got metadata for` `263` assets which mean `263` HTTP requests for a single wallet, without retried ones).
That’s a lot and the improvement also would drastically reduce the produced load to the Token Metadata server.
Also, the rate-limiting issue would be resolved by batching the requests against Token Metadata Server.
Create a new endpoint on the backend `/get-assets` which returns all assets with their nft and token metadata.
Use that new provider method in the wallet and reduce the number of requests significantly.
- create new HTTP endpoint /get-assets …
> feat: Batch requests to Token Metadata server

- packages/cardano-services/src/Program/services/postgres.ts
- packages/cardano-services/test/Program/services/postgres.test.ts
Need to identify poorly performing queries
Add debug log
Also add [missing return](https://github.com/input-output-hk/cardano-js-sdk/pull/673/files#diff-3df69ebf26a058dd3fccae9c81477a3a06fdab0ed5cfe837f8c26ddde64f07f2R58) to SRV proxy
> feat: log all queries

- packages/cardano-services/src/Asset/DbSyncAssetProvider/AssetBuilder.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider/queries.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider/types.ts
- packages/cardano-services/src/Metadata/DbSyncMetadataService.ts
- packages/cardano-services/test/Asset/AssetBuilder.test.ts
- packages/core/src/Provider/AssetProvider/types.ts
After [feat: Batch requests to Token Metadata server](https://github.com/input-output-hk/cardano-js-sdk/pull/691), some more optimization about DB queries can be done.
- Used prepared statement to perform queries;
- Aggregated the `getAssetInfo` two queries in a single one.
Deprecated `getAsset` and its interface
> getAssets queries optimization

- packages/cardano-services/src/NetworkInfo/NetworkInfoHttpService.ts
- packages/cardano-services/src/NetworkInfo/openApi.json
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
Two NetworkInfo openApi paths point to the same operationId, `protocolParams`.
BREAKING CHANGE: remove obsolete NetworkInfo openApi path
/network-info/current-wallet-protocol-parameters.
> fix(cardano-services)!: remove duplicate protocolParams operation id

- packages/e2e/test/wallet/SingleAddressWallet/delegation.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/txChaining.test.ts
- packages/wallet/src/persistence/inMemoryStores/inMemoryWalletStores.ts
- packages/wallet/src/persistence/pouchDbStores/pouchDbWalletStores.ts
- packages/wallet/src/persistence/types.ts
- packages/wallet/src/services/DelegationTracker/DelegationTracker.ts
- packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
- packages/wallet/src/services/TransactionReemitter.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/src/services/types.ts
- packages/wallet/test/SingleAddressWallet/rollback.test.ts
- packages/wallet/test/integration/withdrawal.test.ts
- packages/wallet/test/services/DelegationTracker/RewardAccounts.test.ts
- packages/wallet/test/services/TransactionReemitter.test.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
- packages/web-extension/src/observableWallet/util.ts
The transactions tracker confirmed$ observable name is a bit misleading. The transactions emitted by this observable are transactions that have been submitted with the SingleAddressWallet that were confirmed to be on the chain.
But these transactions are not confirmed as they could be rolled back.
A better name would be onChain$.
The transactions emitted by this observable are transactions that have been submitted with the SingleAddressWallet that were confirmed to be on the chain.
But these transactions are not confirmed as they could be rolled back, so a more suitable name is onChain$ instead of confirmed$
BREAKING CHANGE:
- renamed `TransactionsTracker.outgoing.confirmed$` to `onChain$`
- renamed `TransactionReemitterProps.transactions.outgoing.confirmed$` to `onChain$`
- renamed …
> feat!: rename confirmed$ to onChain$

- packages/cardano-services/src/Http/HttpServer.ts
The default buckets configuration of [express prometheus bundle](https://www.npmjs.com/package/express-prom-bundle) has not a good granularity.
Provided to the module the option to give buckets the granularity we need.
> More granularity in metrics buckets

- packages/core/src/Asset/types/NftMetadata.ts
- packages/core/src/Asset/util/metadatumToCip25.ts
- packages/core/test/Asset/util/metadatumToCip25.test.ts
- packages/e2e/test/wallet/SingleAddressWallet/nft.test.ts
Resolve a couple of CIP25-related validation issues, extracted by the logs from the provider server instance on `mainnet`.
**BREAKING CHANGES**
- _NftMetadata_
`image`: `Uri[]` -> `Uri`
`description?`: `string[]` -> `string`
- _NftMetadataFile_
`src`: `Uri[]` -> `Uri`
**Other non-breaking changes**
- concatenate all protocols if provided as arrays
- improve logging if any required field is missing
> feat(core)!: validation tweaks for CIP-25

- packages/cardano-services/src/Metadata/mappers.ts
- packages/core/src/CML/cmlToCore/cmlToCore.ts
We observe many `RangeError: offset is out of bounds` errors related to Tx Metadata mappings.
Add missed Managed freeable scope in a few places.
> fix: tx metadata memory leak

- packages/core/package.json
- packages/core/test/Asset/util/metadatumToCip25.test.ts
- packages/core/test/tsconfig.json
- yarn.lock
There is a circular dependency that `lerna` complains about
```
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @cardano-sdk/core -> @cardano-sdk/util-dev -> @cardano-sdk/core
```
Remove `util-dev` dependency from `core` pacakge.json
> build(core): rm util-dev circular devDependency

- packages/core/src/CML/cmlToCore/cmlToCore.ts
- packages/dapp-connector/src/WalletApi/types.ts
- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
1. "If amount is not undefined, this request shall be limited to just the UTXOs that are required to reach the combined ADA/multiasset value target specified in amount, and if this cannot be attained, null shall be returned". Currently null is never returned.
2. `getUtxos` 'paginate' argument doesn't work when used with 'amount' argument
See commit log
> fix: cip30 getUtxos compliance

- .github/workflows/continuous-integration-unit-tests.yaml
- .github/workflows/nightly-test.yaml
Nightly workflow is consistently failing with
```
RangeError: WebAssembly.Instance(): Out of memory: wasm memory
```
... at the point of exporting the entire  `@dcspark/cardano-multiplatform-lib-nodejs`.
Double the memory allocation.
> ci: double --max_old_space_size in unit tests

- .github/workflows/continuous-integration-e2e.yaml
- .github/workflows/continuous-integration-unit-tests.yaml
Set default values for TL_DEPTH and TL_LEVEL for unit and e2e test workflows if it launched from forked repository
> ci: set default log level

- packages/key-management/package.json
- packages/util-dev/esm-package.json
- packages/util-dev/package.json
- yarn.lock
`key-management` has a dependency on `util-dev` but it's not being used
- Remove it
- Add "browser" field to util-dev esm package.json to omit docker utils from browser builds
> chore(key-management): rm extraneous util-dev dependency

- packages/util/src/freeable.ts
- packages/util/src/index.ts
- packages/util/src/isPromise.ts
- packages/util/test/isPromise.test.ts
- packages/web-extension/src/messaging/BackgroundMessenger.ts
- packages/web-extension/src/messaging/NonBackgroundMessenger.ts
- packages/web-extension/src/messaging/index.ts
- packages/web-extension/src/messaging/remoteApi.ts
- packages/web-extension/src/messaging/types.ts
- packages/web-extension/src/messaging/util.ts
- packages/web-extension/test/messaging/util.test.ts
- packages/web-extension/test/remoteApi/remoteApi.integration.test.ts
- packages/web-extension/test/remoteApi/remoteApi.test.ts
- tsconfig.json
Remote API can only return POJOs, so it can't be used for fluent interface-style APIs (e.g. tx builder)
eacad41b5b8570ca4e5d0cc4178c4b5740569a4c
- cc0b3b0e10ef4eaf763bea085976669f8be72ed5
- 06939f65daf580b154aa98cc2162d5e1f399c2d7
> feat: remote method returning api

- packages/wallet/package.json
- packages/wallet/test/hardware/ledger/LedgerKeyAgent.integration.test.ts
- packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
- packages/wallet/test/hardware/trezor/TrezorKeyAgent.integration.test.ts
- packages/wallet/test/hardware/trezor/TrezorKeyAgent.test.ts
Tests for hardware wallets split in two for Trezor and Ledger.
> refactor(wallet): split hardware wallet tests

- packages/key-management/src/util/mapHardwareSigningData.ts
Incorrect TTL value prevented transaction from signing.
> fix(key-management): fixed ttl

- packages/cardano-services/src/Http/util.ts
- packages/cardano-services/test/Http/HttpServer.test.ts
The current implementation blocks monitoring services from accessing `/metrics` and `/health` when CORS is enabled, which is too restrictive, given CORS is a client-side security measure.
Only enforce CORS if an `Origin` HTTP header is set.
> refactor(cardano-services): bypass CORS policy when no Origin header set

- packages/cardano-services-client/src/AssetInfoProvider/assetInfoHttpProvider.ts
- packages/cardano-services-client/test/AssetInfoProvider/assetInfoHttpProvider.test.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
- packages/cardano-services/src/Asset/openApi.json
- packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
- packages/core/src/Asset/types/AssetInfo.ts
- packages/e2e/test/wallet/PersonalWallet/nft.test.ts
- packages/util-dev/src/mockProviders/mockAssetProvider.ts
A compatibility mapping was made in 6e28df412797974b8ce6f6deb0c3346ff5938a05, however it's only sufficient for newer clients connecting to the older API, but was a breaking change, and didn't cover backwards compatibility with older clients.
- Restore the field as depreciated
- Remove the client-side compatibility mapping, which is no longer required.
> refactor: restore `AssetInfo.quantity` as depreciated field for backwards compat

- packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
After [getAssets queries optimization](https://github.com/input-output-hk/cardano-js-sdk/pull/697) another optiomization action could be to execute the queries in parallel.
On the other hand this could have the drawback to make the server unresponsive (making busy all the DB connections of the pool).
Execute the `getAssets` queries in parallel.
The queries are parallelized to the HTTP request to get token metadata as well.
@iadmytro can you perform some comparison tests to verify this change yields better performance and acceptable resource demand?
> getAssets queries optimization - parallel execution

- packages/hardware-ledger/src/transformers/requiredSigners.ts
- packages/hardware-ledger/test/testData.ts
- packages/hardware-ledger/test/transformers/requiredsigners.test.ts
- packages/key-management/src/util/ownSignatureKeyPaths.ts
- packages/key-management/test/util/ownSignaturePaths.test.ts
The InMemoryKeyAgent is ignoring the requireSigners field of the transaction when determining which key to use to sign the transaction.
Make the InMemoryKeyAgent search for the keys specified in the requireSigners field.
- Fixed an issue in the InMemoryKeyAgent which was preventing added signers to the requireSigners to be consider for signing.
- Fixed an issue in the LedgerKeyAgent that was preventing stake key hashes in the requiredSigners field to be map correctly
> Lw 6822 in memory key agent should take into account required signers

- .github/workflows/post_integration.yml
- README.md
1. The root readme has a badge for the legacy nightly workflow.
2. Post-integration workflow is failing on docs build. 
1. Remove the link
2. Increase the allocation to `max-old-space-size` by 50%
> Docs/root readme badges + post-integration fix?

- flake.nix
- packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
- packages/util/src/RunnableModule.ts
The configured `CardanoTokenRegistry` URL isn't logged anywhere, and with a default value in place, it would be more transparent to log when starting up.
- Log the config object on construction.
- Also changes the log level within `getTokenMetadata`, as it's too noisy for `info`, and more suited to `debug`.
> Feat/Improve CardanoTokenRegistry logging

- package.json
- packages/cardano-services-client/package.json
- packages/cardano-services/package.json
- packages/core/package.json
- packages/crypto/package.json
- packages/dapp-connector/package.json
- packages/e2e/package.json
- packages/golden-test-generator/package.json
- packages/governance/package.json
- packages/hardware-ledger/package.json
- packages/input-selection/package.json
- packages/key-management/package.json
- packages/ogmios/package.json
- packages/projection-typeorm/package.json
- packages/projection/package.json
- packages/tx-construction/package.json
- packages/util-dev/package.json
- packages/util-rxjs/package.json
- packages/util/package.json
- packages/wallet/package.json
- packages/web-extension/package.json
This PR removes the `contributors` arrays in all package.json files since those are hard to maintain and contributions can be analyzed based on Git more easily.
none
> chore: remove contributors arrays everywhere

- packages/core/src/Provider/TxSubmitProvider/types.ts
- packages/tx-construction/src/tx-builder/OutputBuilder.ts
- packages/tx-construction/src/tx-builder/finalizeTx.ts
- packages/tx-construction/src/tx-builder/types.ts
- packages/tx-construction/test/tx-builder/TxBuilder.test.ts
- packages/util-dev/src/mockProviders/index.ts
- packages/util-dev/src/mockProviders/mockHandleProvider.ts
- packages/wallet/src/PersonalWallet/PersonalWallet.ts
- packages/wallet/src/services/TransactionReemitter.ts
- packages/wallet/src/services/types.ts
- packages/wallet/src/types.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
We want to continue the implementation to return and work with standard handles. 
LW-6653
- Wallet package: 
PersonalWallet now has the handles implementation. 
ObservableWallet now takes handles. 
- Tx-construction: 
~~Replaces signedTx with SubmitTxArgs~~
Adds Cbor to SignedTx
> Feature/LW-6653 add context to txSubmit

- packages/e2e/src/factories.ts
- packages/e2e/test/wallet/PersonalWallet/delegationDistribution.test.ts
- packages/e2e/test/wallet/PersonalWallet/multiAddress.test.ts
- packages/wallet/src/services/AddressDiscovery/HDSequentialDiscovery.ts
- packages/wallet/test/services/addressDiscovery/HDSequentialDiscovery.test.ts
- packages/wallet/test/services/addressDiscovery/SingleAddressDiscovery.test.ts
- packages/wallet/test/services/addressDiscovery/mockData.ts
PersonalWallet currently derives and retains 5 addresses for stake keys [0;5) and the 1st external payment key.
It is not ideal, because in single delegation mode only one address is being used, and wallet with 5 addreses will query data for all 5 (utxo, tx history etc.).
This commit changes the behavior to retain only used addresses.
NOTE: it is possible that stake key is registered, without having any associated transactions (no utxo for the addresses).
Side fix: also discover 'Internal' type addresses
> feat(wallet): discover used stake keys

- packages/hardware-ledger/src/transformers/assets.ts
- packages/hardware-ledger/test/transformers/assets.test.ts
- packages/hardware-ledger/test/transformers/tx.test.ts
- packages/hardware-ledger/test/transformers/txOut.test.ts
- packages/util-dev/src/mockProviders/mockUtxoProvider.ts
- packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
Some Ledger transactions are failing with
```
"Error: L: Transport failure: Ledger transport failed due to
L: invalid asset group in multiasset token bundle - incorrect ordering of tokens
at chrome-extension://gafhhkghbfjjkeiendhlofajokpaflmk/js/353.js:1:177432
at async chrome-extension://gafhhkghbfjjkeiendhlofajokpaflmk/js/343.js:101:98823"
```
Correct canonical ordering
> fix: correct ledger mapping canonical asset and asset group ordering

- packages/cardano-services/src/Asset/CardanoTokenRegistry.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
- packages/cardano-services/src/InMemoryCache/InMemoryCache.ts
- packages/cardano-services/src/InMemoryCache/defaults.ts
- packages/cardano-services/src/Program/options/common.ts
- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/src/Program/programs/types.ts
- packages/cardano-services/src/Program/services/postgres.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/Asset/CardanoTokenRegistry.test.ts
- packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
- packages/cardano-services/test/Program/programs/httpServer.test.ts
- packages/e2e/package.json
`get-asset` queries are pretty expensive
- cache NFT metadata and base AssetInfo in-memory
- fix query logging
- set `pg.Pool` connection and query timeout to 1 minute
> feat: asset cache

- packages/cardano-services-client/src/HandleProvider/KoraLabsHandleProvider.ts
- packages/cardano-services-client/test/HandleProvider/KoraLabsHandleProvider.test.ts
- packages/cardano-services-client/test/util.ts
- packages/cardano-services/src/Handle/openApi.json
- packages/core/src/Provider/HandleProvider/types.ts
- packages/e2e/src/factories.ts
- packages/wallet/src/services/HandlesTracker.ts
The current implementation of KoralabsHandleProvider depends on the network info provider to return a `resolvedAt` property. However, this is not returned by KoralabsHandleProvider, so we are making that property option but not returning it as the API doesn't have it. 
N/A
> Refactor: removes networkInfoProvider dependency from KoralabHandleProvider

- packages/core/src/Cardano/types/DelegationsAndRewards.ts
- packages/e2e/test/long-running/delegation-rewards.test.ts
- packages/e2e/test/wallet/PersonalWallet/delegation.test.ts
- packages/e2e/test/wallet/PersonalWallet/delegationDistribution.test.ts
- packages/key-management/src/util/ensureStakeKeys.ts
- packages/key-management/src/util/index.ts
- packages/key-management/test/util/ensureStakeKeys.test.ts
- packages/tx-construction/src/tx-builder/TxBuilder.ts
- packages/tx-construction/src/tx-builder/types.ts
- packages/tx-construction/src/types.ts
- packages/tx-construction/test/tx-builder/TxBuilder.test.ts
- packages/tx-construction/test/tx-builder/TxBuilderDelegatePortfolio.test.ts
- packages/web-extension/src/observableWallet/util.ts
Delegating a CIP17 portfolio (multi-delegation).
TxBuilder.delegatePortfolio accepts a CIP17 delegation portfolio and creates the certificates to satisfy it:
* - Portfolio delegations that already exist will be preserved.
* - Delegation certificates will be sent for portfolio pools that are not already delegated.
*   The order in which stake keys are used is:
*     1. Stake keys that are delegated but shouldn't be anymore
*     2. Registered but not delegated stake keys.
*     3. Unregistered stake keys.
*     4. New stake keys are derived if number of pools exceeds the number of available stake keys.
* - Deregister stake key certificates are sent for stake keys delegated to pools that are no longer
*   part of the portfolio, and are not needed for re-delegation.
* All certificates are …
> LW-6702 TxBuilder delegatePortfolio

- packages/cardano-services-client/src/HttpProvider.ts
- packages/cardano-services-client/src/version.ts
- packages/cardano-services-client/test/AssetInfoProvider/assetInfoHttpProvider.test.ts
- packages/cardano-services-client/test/ChainHistoryProvider/chainHistoryProvider.test.ts
- packages/cardano-services-client/test/HandleProvider/handleHttpProvider.test.ts
- packages/cardano-services-client/test/HttpProvider.test.ts
- packages/cardano-services-client/test/NetworkInfo/networkInfoHttpProvider.test.ts
- packages/cardano-services-client/test/RewardProvider/rewardsHttpProvider.test.ts
- packages/cardano-services-client/test/StakePoolProvider/stakePoolHttpProvider.test.ts
- packages/cardano-services-client/test/TxSubmitProvider/txSubmitHttpProvider.test.ts
- packages/cardano-services-client/test/Utxo/utxoHttpProvider.test.ts
- packages/cardano-services/src/PgBoss/stakePoolMetricsHandler.ts
- packages/cardano-services/test/Asset/AssetHttpService.test.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/NetworkInfo/NetworkInfoHttpService.test.ts
- packages/cardano-services/test/Reward/RewardsHttpService.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.test.ts
- packages/cardano-services/test/TxSubmit/TxSubmitHttpService.test.ts
- packages/cardano-services/test/Utxo/UtxoHttpService.test.ts
- packages/e2e/src/factories.ts
- packages/e2e/test/artillery/StakePoolSearch.ts
- packages/e2e/test/blockfrost/StakePoolCompare.test.ts
- packages/e2e/test/load-test-custom/stake-pool-search/stake-pool-search.test.ts
- packages/e2e/test/providers/StakePoolProvider.test.ts
#634 introduced a change in the `HttpProvider` interface that was unnecessary, since the version can be just read in directly, and making it configurable is undesirable.
partial revert of 2e9664fcaff56adcfa4f21eb2b71b2fb6a3b411d to keep the version definition an internal concern.
> fix!: revert inclusion of version in the HttpProvider interface

- packages/cardano-services-client/src/HandleProvider/KoraLabsHandleProvider.ts
- packages/cardano-services/src/Handle/TypeOrmHandleProvider.ts
- packages/cardano-services/src/Handle/openApi.json
- packages/cardano-services/test/Handle/HandleHttpService.test.ts
- packages/core/src/Provider/HandleProvider/types.ts
- packages/tx-construction/src/tx-builder/OutputBuilder.ts
- packages/tx-construction/test/tx-builder/TxBuilder.test.ts
- packages/util-dev/src/mockProviders/mockHandleProvider.ts
- packages/wallet/src/services/HandlesTracker.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/wallet/test/services/HandlesTracker.test.ts
LW-7172
`HandleResolution` now resolves `cardanoAddress` instead of `resolvedAddresses.cardano`. 
Do the appropriate refactor to accept the new type.
> feat: adds cardanoAddress type in HandleResolution interface

- packages/cardano-services-client/src/HttpProvider.ts
- packages/cardano-services-client/src/typings.d.ts
In lace, we get the error bellow  [here](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/cardano-services-client/src/HttpProvider.ts#L9), since `require` is not available in the browser
`Error: ReferenceError: require is not defined
`
> fix(cardano-services-client): package.json import

- packages/cardano-services-client/src/HandleProvider/KoraLabsHandleProvider.ts
- packages/cardano-services-client/test/util.ts
Background and profile image from handle public api are ipfs url and not ipfs hash as stated in the documentation.
> fix(cardano-services-client): background and profile image as ipfs url

- Dockerfile
- packages/e2e/package.json
- packages/e2e/test/long-running/cache-invalidation.test.ts
- yarn.lock
Recently we changed the `DISABLE_DB_CACHE` setting of our test _local-network_ to `true` while the cache invalidation tests requires it to `false`: it needs a cache to check it is invalidated.
Changed the test in order to start its own provider-server with the setting configured as it needs.
Also refactored the main `Dockerfile` to take more advantage from docker build cache
> Refactor cache invalidation test

- packages/key-management/src/util/ensureStakeKeys.ts
- packages/key-management/test/util/ensureStakeKeys.test.ts
- packages/tx-construction/package.json
- packages/tx-construction/src/tx-builder/TxBuilder.ts
- packages/tx-construction/test/tx-builder/TxBuilder.bootstrap.test.ts
- packages/tx-construction/test/tx-builder/TxBuilderDelegatePortfolio.test.ts
- yarn.lock
`KeyAgent` doesn't wait for wallet to settle before taking the current value of `knownAddresses$` when building the transaction.
KeyAgent now awaits for non-empty knownAddresses$ for all it's uses
> fix(tx-construction): builder now awaits for non-empty knownAddresses before building the tx

- packages/e2e/test/wallet/PersonalWallet/multiAddress.test.ts
- packages/wallet/src/services/AddressDiscovery/HDSequentialDiscovery.ts
- packages/wallet/test/integration/withdrawal.test.ts
- packages/wallet/test/services/addressDiscovery/HDSequentialDiscovery.test.ts
Internal address at payment index #0 is accidentally skipped on address discovery.
> fix(wallet): discovery should search for 1/0 too

- packages/tx-construction/package.json
- yarn.lock
`tx-construction` depends on `wallet` but does not use it. It creates a circular dependency messing up installed modules for the users
> fix(tx-construction): rm redundant circular dependency on 'wallet' package

- packages/cardano-services/test/PgBoss/util.ts
- packages/cardano-services/test/Program/services/pgboss.test.ts
- packages/cardano-services/test/jest-setup/snapshots/projection.sql
Unit tests are affected by a flakiness which ends with a No stake pools found error.
Some tests deletes the fixtures due to the call `createObservableDataSource({ devOptions: { dropSchema: true } })`: the source of the flakiness is the order jest execute the tests.
Refactored the tests which need the described call to use a dedicated database
> LW-7360 refactor some tests to use a dedicated database

- packages/key-management/src/cip8/cip30signData.ts
- packages/tx-construction/src/tx-builder/finalizeTx.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
With the introduction of HD wallet discovery, is taking longer for the known addresses array to be populated, this is causing issue when trying to sign transaction before the known addresses have been resolved.
Wait in the relevant places for the addresses to be resolved.
> fix: wallet finalizeTx and CIP30 now wait for at least one known address

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
The API introduced in CIP-30 getUsedAddresses was implemented with the single address wallet in mind, but this is now returning an invalid response when used in conjunction with a multi-address wallet (either HD compatibility or multi-delegation)
Update getUsedAddresses so it return all known addresses.
> fix(wallet): cip30 getUsedAddresses now returns all known addresses

- packages/cardano-services/src/Projection/migrations/1689091319930-cost-pledge-numeric.ts
- packages/cardano-services/src/Projection/migrations/index.ts
- packages/cardano-services/src/Projection/prepareTypeormProjection.ts
- packages/cardano-services/test/Projection/prepareTypeormProjection.test.ts
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.test.ts
- packages/ogmios/src/CardanoNode/OgmiosObservableCardanoNode/OgmiosObservableCardanoNode.ts
- packages/ogmios/test/CardanoNode/ObservableOgmiosCardanoNode.test.ts
- packages/ogmios/test/mocks/mockOgmiosServer.ts
- packages/ogmios/test/mocks/types.ts
- packages/projection-typeorm/src/entity/PoolRegistration.entity.ts
- packages/projection-typeorm/src/entity/util.ts
When running projection services on mainnet, we ran into several issues:
1. Projector stops due to local state queries being unavailable in Byron era
2. Fails to insert some pool registrations, where `cost` or `pledge` exceeds postgres `bigint` (signed 64bit integer)
See commits
> fix: mainnet projection issues

- packages/core/src/Cardano/Address/EnterpriseAddress.ts
- packages/core/src/Cardano/util/addressesShareAnyKey.ts
- packages/core/src/Cardano/util/index.ts
- packages/core/test/Cardano/Address/EnterpriseAddress.test.ts
- packages/core/test/Cardano/util/addressesShareAnyKey.test.ts
Add a utility to determine whether 2 addresses share any (either payment or staking) key
Fix EnterpriseAddress.fromCredential 9b647b77ddaa9364bf0aea32b3aded8661a832c9
> feat: add addressesShareAnyKey util

- packages/cardano-services/src/Program/programs/projector.ts
- packages/cardano-services/src/Program/programs/types.ts
- packages/cardano-services/src/Projection/ProjectionHttpService.ts
- packages/cardano-services/src/Projection/createTypeormProjection.ts
- packages/cardano-services/src/cli.ts
- packages/projection/src/operators/logProjectionProgress.ts
We need to add benchmark capabilities to the projector to measure effect of changes.
Added the `--exit-at-block-no` command line argument.
Sample logs of interest:
```
[2023-07-27T11:19:22.161Z]  INFO: projector/12 on 6d24b4d3ed48: [Projector] Initializing 0.08% at block #1000 All: eta 2023-07-27T15:03:08 at 90 b/s
[2023-07-27T11:19:26.581Z]  INFO: projector/12 on 6d24b4d3ed48: [Projector] Initializing 0.17% at block #2000 All: eta 2023-07-27T13:55:39 at 129 b/s - 1K: eta 2023-07-27T12:48:16 at 226 b/s
[2023-07-27T11:19:30.955Z]  INFO: projector/12 on 6d24b4d3ed48: [Projector] Initializing 0.25% at block #3000 All: eta 2023-07-27T13:32:50 at 151 b/s - 1K: eta 2023-07-27T12:47:20 at 229 b/s
[2023-07-27T11:19:34.770Z]  INFO: projector/12 on 6d24b4d3ed48: [Projector] Initializing 0.33% at …
```
> LW-6949 benchmark tools

- packages/e2e/test/web-extension/extension/background/cip30.ts
- packages/util-dev/src/mockProviders/mockData.ts
- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
When calling `getCollateral` this could return null due to lack of `unspendables$` however there may be an available UTXO set that could be used in the `available$` UTXO set.
Adding an optional callback allows a wallet to intercept this call if it will return null in this instance and allow the wallet owner to set collateral and return this set to the DApp without failing.
Added optional `getCollateral` callback to `CallbackConfirmation` which is consumed by `createWalletApi` in `cip30.ts`
> feat(wallet): add optional callback for getCollateral

- .github/std-unexploded.yml
- .github/workflows/std.yml
- nix/local/envs.nix
- fix(local/envs): yq is provided by yq-go package - oversight
- ci: speed up cycle time via the use of remote store
Nix builds can use remote stores (on the cli seen as something like `--store ssh-ng://...`).
Their use significantly reduces the amount of back and forth copying when building on a remote builder and thereby notably reduces the cycle time.
Newer versions of `std-action` (on current `main` branch) have support for this feature, so we enable it here.
The other fixes are incidential.
> ci optimize cycle time

- packages/hardware-trezor/package.json
- packages/hardware-trezor/src/transformers/additionalWitnessRequests.ts
- packages/hardware-trezor/src/transformers/tx.ts
- packages/hardware-trezor/test/transformers/additionalWitnessRequests.test.ts
- packages/hardware-trezor/test/transformers/assets.test.ts
- yarn.lock
This PR implements the `additionalWitnessRequests` required for multi-sig and and token minting witness requests: https://github.com/trezor/connect/blob/e92440e4af786bab7f326397b3e9a64e6c9df77c/docs/methods/cardanoSignTransaction.md?plain=1#L36 
it also fixes one broken unit test for the asset mapper.
> LW-7811(hardware-trezor) additional witness requests mapper

- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/NetworkInfoBuilder.ts
- packages/cardano-services/src/util/DbSyncProvider/DbSyncProvider.ts
The query to get the ledger tip is performed so often by the SDK, using the server side `PREPARED STATEMENT` feature should give some minor performances benefit.
6d4d04bd8
> Use prepared statement for the get ledger tip query

- packages/cardano-services/test/cli.test.ts
Health-check in stake pool provider test caused race condition.
Check only status code of started service.
> test(cardano-services): removed healthcheck from typeorm stake pool provider test

- packages/cardano-services/src/Projection/migrations/1690955710125-address-table.ts
- packages/cardano-services/src/Projection/migrations/1690964880195-stake-key-registrations-table.ts
- packages/cardano-services/src/Projection/migrations/1691042603934-tokens-quantity-numeric.ts
- packages/cardano-services/src/Projection/migrations/index.ts
- packages/cardano-services/src/Projection/prepareTypeormProjection.ts
- packages/projection-typeorm/src/entity/Address.entity.ts
- packages/projection-typeorm/src/entity/PoolRegistration.entity.ts
- packages/projection-typeorm/src/entity/StakeKeyRegistration.entity.ts
- packages/projection-typeorm/src/entity/Tokens.entity.ts
- packages/projection-typeorm/src/entity/index.ts
- packages/projection-typeorm/src/entity/transformers.ts
- packages/projection-typeorm/src/entity/util.ts
- packages/projection-typeorm/src/operators/index.ts
- packages/projection-typeorm/src/operators/storeAddresses.ts
- packages/projection-typeorm/src/operators/storeStakeKeyRegistrations.ts
- packages/projection-typeorm/test/operators/storeAddresses.test.ts
- packages/projection-typeorm/test/operators/storeNftMetadata.test.ts
- packages/projection-typeorm/test/operators/storeStakeKeyRegistrations.test.ts
- packages/projection-typeorm/test/operators/util.ts
- packages/projection/src/operators/Mappers/certificates/index.ts
- packages/projection/src/operators/Mappers/certificates/withStakeKeyRegistrations.ts
- packages/projection/src/operators/Mappers/index.ts
- packages/projection/src/operators/Mappers/withAddresses.ts
- packages/projection/test/operators/Mappers/certificates/withStakeKeyRegistrations.test.ts
- packages/projection/test/operators/Mappers/withAddresses.test.ts
- packages/util-dev/src/chainSync/data/with-pool-retirement.json
- packages/util-dev/src/chainSync/data/with-stake-key-deregistration.json
Handle and utxo/chain history projections will require storing key hashes (payment and stake credentials) in order to be able to query by it.
4f211bee5a92d390b53a3db3054a110f040168b4
See commit log: all other commits are general fixes and refactors
> feat: address projection

- packages/wallet/src/PersonalWallet/PersonalWallet.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
#861 made submitTx idempotent, but also broke internal logic of PersonalWallet preventing it to re-submit transactions
ef64b30c7d02b64746344ea3042ae7b96db888f6
> fix(wallet): do not prevent re-submission

- .github/std-unexploded.yml
- .github/workflows/std-release.yaml
The current setup triggers multiple STD pipelines, one for _each_ release tag.
But we only need the pipeline to run once for `cardano-sdk/cardano-services`.
- Make it a call workflow
- Call it form a release workflow
- Which is in turn able to filter on a broader spectrum of the available event data.
- create a new release after merge (?)
ref: LW-8058
> ci: call std as release process only for specific release prefix

- packages/hardware-trezor/package.json
- packages/hardware-trezor/src/TrezorKeyAgent.ts
- packages/hardware-trezor/src/transformers/additionalWitnessRequests.ts
- packages/hardware-trezor/src/transformers/assets.ts
- packages/hardware-trezor/src/transformers/auxiliaryData.ts
- packages/hardware-trezor/src/transformers/certificates.ts
- packages/hardware-trezor/src/transformers/tx.ts
- packages/hardware-trezor/src/transformers/txIn.ts
- packages/hardware-trezor/src/transformers/txOut.ts
- packages/hardware-trezor/src/transformers/withdrawals.ts
- packages/hardware-trezor/src/types.ts
- packages/hardware-trezor/test/transformers/certificates.test.ts
- packages/hardware-trezor/test/transformers/txOut.test.ts
- yarn.lock
This PR replaces the legacy `trezor-connect` package with `@trezor/connect` and `@trezor/connect-web` and refactors the new `TrezorKeyAgent` in our `hardware-trezor` package to not extend the legacy key agent from the `key-management` package (this made the switch to the new Trezor packages easier)
> chore(hardware-trezor): update to dedicated trezor node and web packages [LW-7776]

- packages/dapp-connector/package.json
- packages/dapp-connector/src/WalletApi/Cip30Wallet.ts
- packages/dapp-connector/src/WalletApi/types.ts
- packages/dapp-connector/test/WalletApi/Cip30Wallet.test.ts
- packages/dapp-connector/test/injectGlobal.test.ts
- packages/dapp-connector/test/testWallet.ts
- packages/e2e/test/web-extension/extension/stubWalletApi.ts
- packages/wallet/src/cip30.ts
- yarn.lock
As a DApp developer, I want to enable the lace DApp connector with an array of extensions, so I can make use of the extensible DApp connector within my DApp.
- Add CIP-95 as a supported extension
- Add `getActivePubStakeKeys` and `getPubDRepKey` to the `WalletApi` interface (without implementation)
- Add a parameter to the `Cip30Wallet.enable` method to be able to pass an array of extensions according to the CIP-30 specification
- Wrap the `Cip30Wallet.api` as a JS object with the allowed methods depending on the extensions array to make `enable` does not return a `Proxy`
> feat: allow extensions for CIP-30 API

- .github/std-unexploded.yml
- .github/workflows/std.yml
It turns out a GH quirk (see code comment) makes booleans stringly typed during expression evaluation
Well, follow suit.
This cannot really be tested until the next merge to `master`, i.e. when the event predicate evals true (:crossed_fingers: )
ref: LW-8219
> ci: fix compare boolean to its string value

- .github/std-unexploded.yml
- .github/workflows/std.yml
It might be surprising to find out that the HEAD of a feature branch is not representing the same commit as is run during CI.
The reason is GitHubs Merge Queue feature which runs CI on a synthetic commit between a branch and the main branch.
Print out the sha explicitly in every step to facilitate auditing and debugging and avoid false assumptions.
ref: LW-8217
> ci: print the current commit sha for auditing in all workflows

- .github/std-unexploded.yml
- .github/workflows/std.yml
ref: LW-8230
When someone directly pushes to master, then there's no branch, and hence no pull request that the gh CLI can infer for the purpose of posting a diff back to the PR as comment.
- Run the diff posting job only when the event type is a PR
- Ensure that deploy runs on master regardless of whether it comes from a PR or not (e.g. a bot release directly pushed to master)
To test this, a new direct push to master would need to be made.
> ci: fix the deployment run on push to master

- packages/cardano-services/src/PgBoss/stakePoolMetricsHandler.ts
- packages/cardano-services/src/PgBoss/types.ts
- packages/cardano-services/src/Program/options/common.ts
- packages/cardano-services/src/Program/programs/pgBossWorker.ts
- packages/cardano-services/src/Program/services/pgboss.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/Program/services/pgboss.test.ts
- packages/cardano-services/test/cli.test.ts
The stake pool rewards job requires the network info provider, so we need to add the network info provider url cli parameter and to propagate it to the job handler.
We had exactly the same problem with the stake pool provider when implementing the stake pool metrics job; in that occasion we introduced the `stakePoolProviderUrl` parameter.
I did this two refactoring rather than _repeating_ what we have for the `stakePoolProviderUrl` parameter to implement the `assetInfoProviderUrl` one; which would have opened the path to an even larger code repetition when adding new provider urls.
- Refactored the `stakePoolProviderUrl` cli parameter into all the provider url parameters.
- Refactored how the configuration is propagated from cli to the job handlers to simply propagate it completely. 
The …
> LW-7438 Refactor cli providers url

- packages/cardano-services/src/Asset/DbSyncAssetProvider/AssetBuilder.ts
- packages/cardano-services/src/Asset/DbSyncAssetProvider/DbSyncAssetProvider.ts
- packages/cardano-services/src/Asset/TypeormAssetProvider/TypeormAssetProvider.ts
- packages/cardano-services/src/Asset/TypeormAssetProvider/index.ts
- packages/cardano-services/src/Asset/index.ts
- packages/cardano-services/src/Asset/openApi.json
- packages/cardano-services/src/Program/options/postgres.ts
- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/src/Program/programs/types.ts
- packages/cardano-services/src/Program/utils.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/Asset/AssetBuilder.test.ts
- packages/cardano-services/test/Asset/AssetHttpService.test.ts
- packages/cardano-services/test/Asset/DbSyncAssetProvider.test.ts
- packages/cardano-services/test/Asset/TypeormAssetProvider/TypeormAssetFixtureBuilder.ts
- packages/cardano-services/test/Asset/TypeormAssetProvider/TypeormAssetProvider.test.ts
- packages/cardano-services/test/Asset/fixtures/FixtureBuilder.ts
- packages/cardano-services/test/cli.test.ts
- packages/core/src/Asset/types/AssetInfo.ts
- packages/core/src/Provider/AssetProvider/types.ts
- packages/e2e/test/wallet/PersonalWallet/nft.test.ts
- packages/util-dev/src/mockProviders/mockAssetProvider.ts
- packages/wallet/test/services/HandlesTracker.test.ts
- packages/wallet/test/services/ProviderTracker/TrackedAssetProvider.test.ts
This PR explores using `TypeORM` as an alternative asset provider to `DbSync` and added a CLI option `--use-typeorm-asset-provider` to enable this provider.
Create `TypeormAssetProvider` to resolve asset info and `TypeormNftMetadataService` to fetch NFT metadata and refactor the provider server to use this new provider
- remove AssetInfo.mintOrBurnCount and AssetInfo.history some fields from Cardano.AssetInfo [breaking change]
- remove `history` from `extraData` property of `AssetProvider` interface [breaking change]
- add `TypeormAssetProvider`
- add `--use-typeorm-asset-provider `CLI argument
> feat: add TypeormAssetProvider to Cardano Services

- packages/e2e/test/wallet/PersonalWallet/delegation.test.ts
- packages/wallet/src/PersonalWallet/PersonalWallet.ts
- packages/wallet/src/services/ActiveStakePublicKeysTracker.ts
- packages/wallet/src/types.ts
- packages/wallet/test/PersonalWallet/load.test.ts
- packages/wallet/test/services/ActiveStakePublicKeysTracker.test.ts
- packages/web-extension/src/observableWallet/util.ts
Add `ObservableWallet.activePublicStakeKeys$` support.
Will later be used by CIP-95 
Below items will be done in a separate PR. This one adds support in ObservableWallet.
- ~~Add web-extension dapp test~~
- ~~integrate with extensions enable work~~
> feat(wallet): active public stake keys tracker support for cip95

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
Implement `getPubDRepKey` method in CIP-95 API
- Use `wallet$.getPubDRepKey()` to return the public DRep key
- Throw `ApiError` in case something goes wrong
> feat(wallet): implement getPubDRepKey() in cip95 api

- nix/cardano-services/deployments/backend-deployment.yaml
- nix/cardano-services/deployments/backend-ingress.yaml
- nix/cardano-services/deployments/handle-projector-deployment.yaml
- nix/cardano-services/deployments/handle-provider-deployment.yaml
- nix/cardano-services/deployments/pgboss-deployment.yaml
- nix/cardano-services/deployments/stake-pool-projector-deployment.yaml
- nix/cardano-services/deployments/stake-pool-provider-deployment.yaml
- packages/cardano-services/src/Http/HttpServer.ts
- packages/cardano-services/src/Http/openApi.json
- packages/cardano-services/src/util/DbSyncProvider/DbSyncProvider.ts
- packages/cardano-services/test/Http/HttpServer.test.ts
- packages/cardano-services/test/cli.test.ts
Services need to report when they are live and also when they are ready, which can be used to interpret the service health. Orchestration logic can be tied to the live result, to determine if a restart is required, or the ready result for starting up dependent services.
- Adds `/live` endpoint that simply returns a `200` if the server is reachable.
- `DbSyncProvider` now only as to access both the node and database to be considered ready.
`/ready` endpoint no longer returns the health check response, and it's been included in the `HttpServer` OpenApi document
> Adds live endpoint and fixes DbSyncProvider ready endpoint

- nix/cardano-services/deployments/pgboss-deployment.yaml
The url link from pg-boss-worker needs to point to the correct service name.
Without really understanding how they are rendered and if the actual service name would be rendered as expceted, ensure that they are both rendered the same way (either right or wrong).
This is currently a root cause for a failure in `dev-preview` deployment.
> fix: service name url mismatch

- nix/cardano-services/deployments/pgboss-deployment.yaml
The application adds the path suffix all on its own, furthermore no https (port 443) is configured _within_ the cluster network.
- remove the path suffix
- change https to http
> fix: pgboss url configuration

- nix/cardano-services/deployments.nix
For the past a while we have handle provider failing due to invalid OCI image name. This is a fix to reduce the amount of alerts
> ci: fix handle provider OCI image reference

- packages/dapp-connector/src/WalletApi/Cip30Wallet.ts
- packages/dapp-connector/src/WalletApi/types.ts
- packages/dapp-connector/test/WalletApi/Cip30Wallet.test.ts
- packages/dapp-connector/test/injectGlobal.test.ts
- packages/dapp-connector/test/testWallet.ts
- packages/e2e/test/web-extension/extension/stubWalletApi.ts
- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
Add support for `getExtensions()` defined in [CIP-30](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0030/README.md#apigetextensions-promiseextension) 
- Add `getExtensions` to `Cip30WalletApi` interface
- Changed return type of `Cip30Wallet.#getAllowedApiMethods` to also include the list of enabled extensions
- Remove unnecessary bindings of `enable` and `isEnabled` in `Cip30Wallet` constructor
> feature/LW-8426 - CIP-30 `getExtensions()`

- Dockerfile
- README.md
- package.json
- packages/cardano-services-client/package.json
- packages/cardano-services/package.json
- packages/core/package.json
- packages/crypto/package.json
- packages/dapp-connector/package.json
- packages/e2e/package.json
- packages/golden-test-generator/package.json
- packages/governance/package.json
- packages/hardware-ledger/package.json
- packages/input-selection/package.json
- packages/key-management/package.json
- packages/ogmios/package.json
- packages/projection-typeorm/package.json
- packages/projection/package.json
- packages/tx-construction/package.json
- packages/util-dev/package.json
- packages/util-rxjs/package.json
- packages/util/package.json
- packages/wallet/package.json
- packages/web-extension/package.json
v14 is now depreciated. We still wish to maintaining support for v16 until EOL.
- Dockerfile is now being built with v18
> chore: bump minimum Node.js version to v16, use v18 in Dockerfile

- .github/workflows/std.yml
This is needed to build and push OCI images for the sanchonet ENV
We can already trigger the build manually, but this is tedious
> chore: include conway-era branch in std workflow

- compose/ogmios/Dockerfile
Previously, we had no native ARM images of `cardano-node-ogmios`
It takes 2 hours to build, but works 😮‍💨
```
❯ cd compose/ogmios/
❯ docker build --build-arg TARGETPLATFORM=linux/arm64 -t cardano-node-ogmios-arm64 .
[wait 2h10m…]
❯ docker run --entrypoint /bin/bash -it --rm cardano-node-ogmios-arm64
15b8c7ef017f:~# apk add file
OK: 20 MiB in 22 packages
15b8c7ef017f:~# file /opt/ogmios/exe/ogmios 
/opt/ogmios/exe/ogmios: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter ld-linux-aarch64.so.1, for GNU/Linux 3.10.0, with debug_info, not stripped
```
n/a
> chore: support AArch64 in `cardano-node-ogmios`

- packages/cardano-services/src/Program/programs/types.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/cli.test.ts
It used to only work with srv or connection string
Add missing cli configuration
> fix(cardano-services): asset provider can now be started with POSTGRES_HOST

- packages/ogmios/src/CardanoNode/OgmiosObservableCardanoNode/OgmiosObservableCardanoNode.ts
- packages/ogmios/src/CardanoNode/OgmiosObservableCardanoNode/createObservableChainSyncClient.ts
- packages/ogmios/src/ogmiosToCore/tx.ts
- packages/ogmios/test/ogmiosToCore/__snapshots__/block.test.ts.snap
- packages/ogmios/test/ogmiosToCore/testData.ts
Asset projector fails on mainnet with
```
2023-10-23 22:44:51.999 | at /nix/store/242nx3dy5l3xq05wvnk9m0kxiszi6y1h-cardano-sdk/libexec/incl/packages/ogmios/dist/cjs/ogmiosToCore/tx.js:332:72 |  
-- | -- | --
  |   | 2023-10-23 22:44:51.999 | at mapCommonTx (/nix/store/242nx3dy5l3xq05wvnk9m0kxiszi6y1h-cardano-sdk/libexec/incl/packages/ogmios/dist/cjs/ogmiosToCore/tx.js:301:38) |  
  |   | 2023-10-23 22:44:51.999 | at Array.map (<anonymous>) |  
  |   | 2023-10-23 22:44:51.999 | at mapTxOut (/nix/store/242nx3dy5l3xq05wvnk9m0kxiszi6y1h-cardano-sdk/libexec/incl/packages/ogmios/dist/cjs/ogmiosToCore/tx.js:265:12) |  
  |   | 2023-10-23 22:44:51.999 | at mapInlineDatum (/nix/store/242nx3dy5l3xq05wvnk9m0kxiszi6y1h-cardano-sdk/libexec/incl/packages/ogmios/dist/cjs/ogmiosToCore/tx.js:256:44) |  
  …
```
> fix(ogmios): don't parse alonzo datum hashes as inline datums

- packages/core/src/Cardano/types/Certificate.ts
- packages/core/src/Serialization/Certificates/AuthCommitteeHot.ts
- packages/core/src/Serialization/Certificates/RegisterDelegateRepresentative.ts
- packages/core/src/Serialization/Certificates/ResignCommitteeCold.ts
- packages/core/src/Serialization/Certificates/UnregisterDelegateRepresentative.ts
- packages/core/test/Serialization/Certificates/ResignCommitteeCold.test.ts
Conway era ledger CDDL has been updated to add an optional anchor in the resign committee cold certificate
https://github.com/input-output-hk/cardano-ledger/blob/master/eras/conway/test-suite/cddl-files/conway.cddl#L313
Update core types & serialization to account for new optional property
Updated core types & serialization to account for new optional property
> feat(core): update certificate serialization resign committee cold certificate

- packages/cardano-services-client/package.json
- packages/cardano-services/package.json
- packages/e2e/package.json
- packages/governance/package.json
- packages/hardware-ledger/package.json
- packages/hardware-trezor/package.json
- packages/input-selection/package.json
- packages/key-management/package.json
- packages/projection-typeorm/package.json
- packages/projection/package.json
- packages/util-dev/package.json
- packages/util-rxjs/package.json
- packages/util/package.json
- packages/wallet/package.json
- packages/web-extension/package.json
[deploy-docs](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/6576994512) job has been failing for a while now.
It was failing because [one of cardano-services tests](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/6576994512/job/17867630287#step:4:950) is consistently failing (captured in LW-8850). Running the tests is not the purpose of the workflow - it will generate coverage report regardless if tests pass or not.
> ci: do not require tests to pass when generating coverage report

- packages/util/src/errors.ts
- packages/util/src/serializableObject.ts
- packages/util/test/serializableObject.test.ts
- packages/wallet/test/services/WalletUtil.test.ts
> LW-9018 fix unit tests 

- packages/core/test/CardanoNode/util/bufferChainSyncEvent.test.ts
A too short delay is often cause of CI unit tests failures.
Increased the delay to reduce the probability of this error.
> test(cardano-services): increase the dealy of flaky test

- packages/dapp-connector/src/WalletApi/Cip30Wallet.ts
- packages/dapp-connector/test/WalletApi/Cip30Wallet.test.ts
- packages/dapp-connector/test/injectGlobal.test.ts
The initial and full APIs should remain POJOs to ensure compatability with dApps
LW-9080
revert removal of initial bind, introduce test to guard against change
> fix(dapp-connector): re-implement initial cip-30 api

- packages/hardware-trezor/src/transformers/tx.ts
- packages/hardware-trezor/src/transformers/txOut.ts
- packages/hardware-trezor/test/testData.ts
- packages/hardware-trezor/test/transformers/tx.test.ts
- packages/hardware-trezor/test/transformers/txOut.test.ts
- packages/wallet/test/hardware/trezor/TrezorKeyAgent.test.ts
This PR introduces additional data mappers where we added `referenceInputs` and `referenceScript`.
[JIRA Ticket](https://input-output.atlassian.net/browse/LW-9015)
SDK testing standards were followed when developing this ticket
It will not be tested by SDETs in isolation! (Described in JIRA Ticket)
Add Trezor TX reference inputs and script mappers
New mappers were added. No breaking changes
> chore(hardware-trezor): add trezor tx reference inputs and script mappers

- packages/hardware-trezor/src/TrezorKeyAgent.ts
- packages/hardware-trezor/src/transformers/tx.ts
- packages/hardware-trezor/test/testData.ts
- packages/hardware-trezor/test/transformers/tx.test.ts
- packages/wallet/test/hardware/trezor/TrezorKeyAgent.test.ts
This PR introduces additional collateral data mappers.
[JIRA Ticket](https://input-output.atlassian.net/browse/LW-8285) and Plutus signing mode https://input-output.atlassian.net/browse/LW-8286 ( described in: https://input-output.atlassian.net/browse/LW-8285?focusedCommentId=235169)
SDK testing standards were followed when developing this ticket
It will not be tested by SDETs in isolation! (Described in JIRA Ticket)
Add Trezor TX `collateralInputs`, `collateralReturn`, and `totalCollateral` mappers
New mappers were added. No breaking changes
> feat(hardware-trezor): add trezor tx collateral mappers

- packages/cardano-services/test/Program/services/postgres.test.ts
`yarn workspace @cardano-sdk/cardano-services test` sometimes fails with following error
```
Error: Unhandled error. (error: terminating connection due to administrator command
at Parser.parseErrorMessage (/home/cicci/iohk/cardano-js-sdk/node_modules/pg-protocol/src/parser.ts:369:69)
at Parser.handlePacket (/home/cicci/iohk/cardano-js-sdk/node_modules/pg-protocol/src/parser.ts:188:21)
at Parser.parse (/home/cicci/iohk/cardano-js-sdk/node_modules/pg-protocol/src/parser.ts:103:30)
at Socket.<anonymous> (/home/cicci/iohk/cardano-js-sdk/node_modules/pg-protocol/src/index.ts:7:48)
at Socket.emit (node:events:513:28)
at addChunk (node:internal/streams/readable:324:12)
at readableAddChunk (node:internal/streams/readable:297:9)
at Socket.Readable.push (node:internal/streams/readable:234:10)
at …
```
> test(cardano-services): fix flaky test

- packages/hardware-trezor/src/transformers/index.ts
- packages/hardware-trezor/src/transformers/requiredSigners.ts
- packages/hardware-trezor/src/transformers/tx.ts
- packages/hardware-trezor/test/testData.ts
- packages/hardware-trezor/test/transformers/requiredSigners.test.ts
- packages/hardware-trezor/test/transformers/tx.test.ts
- packages/wallet/test/hardware/trezor/TrezorKeyAgent.test.ts
This PR introduces an additional `requiredSigners` data mapper.
[JIRA Ticket](https://input-output.atlassian.net/browse/LW-8283)
SDK testing standards were followed when developing this ticket
It will not be tested by SDETs in isolation! (Described in JIRA Ticket)
Add Trezor TX `requiredSigners` mapper
A new mapper was added. No breaking changes
> feat(hardware-trezor): add trezor tx required signers mapper

- .github/workflows/continuous-integration-e2e.yaml
- compose/common.yml
- demo/README.md
- demo/projection-typeorm.js
- packages/cardano-services/docker-compose.yml
- packages/cardano-services/test/jest-setup/rebuild-test-db.sh
- packages/e2e/docker-compose.yml
- packages/e2e/local-network/scripts/ogmios-start.sh
- packages/e2e/test/long-running/projector-ogmios-connection.test.ts
- scripts/preprod-network.sh
Cardano Node and Ogmios are bundled as a single image by the ogmios project.
This creates a connection between compatible versions.
However, we may want to start versions that are not tested/bundled together for experimental purposes or just to get a preview of them running together.
Use separate services for `cardano-node` and `ogmios`.
> chore: use separate images for node and ogmios

- packages/cardano-services-client/package.json
- packages/cardano-services-client/src/version.ts
- packages/cardano-services-client/version.json
- packages/cardano-services/package.json
- packages/cardano-services/src/StakePool/TypeormStakePoolProvider/mappers.ts
- packages/cardano-services/src/StakePool/TypeormStakePoolProvider/util.ts
- packages/cardano-services/src/StakePool/openApi.json
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.test.ts
- packages/core/package.json
- packages/core/test/CardanoNode/util/bufferChainSyncEvent.test.ts
- packages/crypto/package.json
- packages/dapp-connector/package.json
- packages/e2e/package.json
- packages/golden-test-generator/package.json
- packages/governance/package.json
- packages/hardware-ledger/package.json
- packages/hardware-trezor/package.json
- packages/input-selection/package.json
- packages/key-management/package.json
- packages/ogmios/package.json
- packages/projection-typeorm/package.json
- packages/projection/package.json
- packages/tx-construction/package.json
- packages/util-dev/package.json
- packages/util-rxjs/package.json
- packages/util/package.json
- packages/wallet/package.json
- packages/web-extension/package.json
When I introduced `ros` I broken back compatibility; we need to restore it. 
- copy the property `ros` into `apy` one; 
- when sort by `apy` is requested, act as sort by `ros` was requested;
- minor change to `yarn cleanup` to make it faster
- increased a delay in test to make the test more strong
> LW-9237 typeorm stake pool provider backward compatibility

- packages/wallet/src/PersonalWallet/PersonalWallet.ts
- packages/wallet/src/types.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/web-extension/src/observableWallet/util.ts
we consolidated address storage in the wallet in #1009 and there was no way to re-discover addresses,
since storage is managed by the wallet internally
add ObservableWallet.discoverAddreses
> feat: add ObservableWallet.discoverAddreses

- packages/dapp-connector/src/AuthenticatorApi/PersistentAuthenticator.ts
- packages/dapp-connector/src/AuthenticatorApi/types.ts
- packages/dapp-connector/src/WalletApi/types.ts
- packages/dapp-connector/src/index.ts
- packages/dapp-connector/src/util.ts
- packages/dapp-connector/test/AuthenticatorApi/PersistentAuthenticator.test.ts
- packages/dapp-connector/test/util.test.ts
- packages/e2e/test/web-extension/extension/background/cip30.ts
- packages/e2e/test/web-extension/extension/background/requestAccess.ts
- packages/key-management/package.json
- packages/key-management/src/cip8/cip30signData.ts
- packages/key-management/src/types.ts
- packages/key-management/src/util/createWitnesser.ts
- packages/key-management/test/cip8/cip30signData.test.ts
- packages/wallet/src/PersonalWallet/PersonalWallet.ts
- packages/wallet/src/cip30.ts
- packages/wallet/src/types.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/wallet/test/integration/cip30mapping.test.ts
- packages/web-extension/src/cip30/exposeAuthenticatorApi.ts
- packages/web-extension/src/cip30/exposeWalletApi.ts
- packages/web-extension/src/cip30/initializeBackgroundScript.ts
- packages/web-extension/src/cip30/util.ts
- packages/web-extension/src/messaging/util.ts
- packages/web-extension/test/messaging/util.test.ts
- yarn.lock
Current setup loses information about the sender/origin of cip30 method calls
LW-7832
- add a context argument to all cip30 implementation methods and map sender via messaging transformer
- (BREAKING) replace authenticator 'origin' argument to 'sender'
- (BREAKING) hoist 'senderOrigin' util to dapp-connector package
> feat: track cip30 method call origin

- packages/core/src/Cardano/types/Certificate.ts
RegisterCcHotKeyCertificate and RetireCcCertificate are duplicates of AuthorizeCommitteeHotCertificate and ResignCommitteeColdCertificate respectively.
BREAKING CHANGE: remove duplicate RegisterCcHotKey and RetireCc certificates
> refactor(core)!: remove duplicate committee certificates

- packages/cardano-services/src/Http/HttpServer.ts
- packages/cardano-services/test/Http/HttpServer.test.ts
- packages/cardano-services/test/Http/openApi.json
Given /v[major].[minor].[patch],
Server accepts requests to urls that have <= minor version number
Server does not accept requests to urls that have different major version number
Patch version is ignored
> feat(cardano-sevices): allow api compatible version requests

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
When `cip30.getCollateral` is called, Lace will present the dapp information. Thus, we need a reliable way to get the dapp tab. See [cip30.ts](https://github.com/input-output-hk/lace/blob/f7c4fd1972184bf5d84b196894a6e0700236ca0b/apps/browser-extension-wallet/src/lib/scripts/background/cip30.ts#L70-L71)
> feat(wallet): forward MessageSender to GetCollateralCallback

- packages/key-management/src/util/ownSignatureKeyPaths.ts
- packages/key-management/test/util/ownSignaturePaths.test.ts
- packages/wallet/test/services/WalletUtil.test.ts
[Current cardano ledger implementation wrongfully does not require a witness for DRep registration certificate.](https://github.com/input-output-hk/cardano-ledger/issues/3890)
Prepare SDK for when Cardano ledger releases the version which requires witness DRep registration certificates
> feat: sign own dRep registration certificate

- Dockerfile
SDK packages are organized in a way that all the dependencies are handled at root level: i.e. all the dependencies are tracked in `/yarn-project.nix` and `/yarn.lock` and installed in `/node_modules`, included dependencies required only at client side and ones required only for e2e testing.
The drawback of this is that all these dependencies not required at back-end side are installed and built inside our `Docker` image.
Some of these dependencies need to be downloaded and rebuild. With a high throughput line, this is not a big issue, but in case of internet problems or for those who have poor lines, this can result in a huge waste of time.
Actually proposed by @mkazlauskas;
adding `--mode=skip-build` to `yarn build` step in Docker image makes the `docker build` time on my local env to …
> chore: add mode skip build in docker image yarn build phase

- nix/cardano-services/deployments/backend-ingress.yaml
`stake-pool-provider` version has not been updated in the deployment manifest thus making it not reachable. This PR fixes this issue
> chore: fix stake-pool-provider routing

- packages/cardano-services-client/src/TxSubmitProvider/txSubmitHttpProvider.ts
- packages/core/src/CardanoNode/util/cardanoNodeErrors.ts
Two comments were not addressed in the original [PR](https://github.com/input-output-hk/cardano-js-sdk/pull/1005),
so I am addressing them here.
> chore: consistent object create and remove todo

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
We need to support Conway era voting procedures.
Added voting procedure to chain `DbSyncChainHistoryProvider`.
It's enough to take a quick look at the newly introduced query to be warried about its complexity and relative performances issues, so I did some investigation around.
```
cexplorer=# EXPLAIN SELECT
tx.hash AS tx_id,
voter_role,
committee_voter,
dh.raw AS drep_voter,
ph.hash_raW as pool_voter,
tx2.hash AS governance_action_tx_id,
ga.index::INTEGER AS governance_action_index,
CASE
WHEN vote = 'No' THEN 0
WHEN vote = 'Yes' THEN 1
WHEN vote = 'Abstain' THEN 2
END AS vote,
va.url,
va.data_hash
FROM tx
JOIN voting_procedure AS vp ON vp.tx_id = tx.id
JOIN governance_action AS ga ON governance_action_id = ga.id
JOIN tx AS tx2 ON ga.tx_id = tx2.id
LEFT JOIN drep_hash AS dh ON drep_voter …
```
> LW-8968 add voting procedures to db-sync chain history

- Dockerfile
- README.md
I merged #1024 too much fast
Added references to the possible issues introduced
> docs: add documentation for #1024

- packages/core/src/util/slotCalc.ts
- packages/core/test/util/slotCalc.test.ts
Some of our `slotCalc` utilities are not taking care of skipped eras in `EraSummary[]`.
In the real world **this is not impacting _mainnet_ nor _preprod_** while this impacts on _preview_ since it has this use case.
Fixed those utilities affected by the bug: `epochSlotsCalc` and `createSlotTimeCalc`.
Not added a specific test for `createSlotEpochInfoCalc` since it relies on `createSlotEpochCalcImpl` (not affected by the bug) and `createSlotTimeCalc` (fixed and tested in this PR).
> fix(core): take care of skipped eras in era summaries

- packages/wallet/src/services/AssetsTracker.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/test/services/AssetsTracker.test.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
Currently, PersonalWallet only fetches asset metadata once when it is started. Metadata of some of the CIP-68 NFTs is updated in a transaction made by the owner of the user NFT (e.g. adahandle personalization).
LW-8332
PersonalWallet will re-fetch CIP-68 NFT metadata when it sees an on-chain transaction with a corresponding reference NFT
> feat(wallet): re-fetch cip68 nft metadata

- packages/projection-typeorm/src/operators/storeStakePools.ts
- packages/projection-typeorm/test/operators/storeStakePools.test.ts
- packages/util-dev/src/chainSync/data/preview-stake-pool-problem.json
- packages/util-dev/src/chainSync/index.ts
There is something not working as expected in `stake_pool.status` computation.
Changed one of the queries involved in the process as fix attempt
> LW-9428 fix the query to get activating stake pools which must be updated to active

- packages/web-extension/src/walletManager/SignerManager/SignerManager.ts
- packages/web-extension/src/walletManager/SignerManager/types.ts
- packages/web-extension/test/walletManager/SignerManager.test.ts
Signing can fail due to user error (e.g. entering wrong passphrase)
LW-9094
This commit adds a mechanism that enables retries for a single sign request
> feat(web-extension): add willRetryOnFailure sign option to SignerManager

- nix/local/envs.nix
`yarn workspace @cardano-sdk/hardware-trezor test` was failing to execute due to missing library.
> build: add udev package to LD_LIBRARY_PATH

- packages/cardano-services/test/jest-setup/rebuild-test-db.sh
yarn `--cwd`
[option is ignored](https://github.com/yarnpkg/berry/pull/1812#discussion_r485873759) in some yarn versions.
In my case (yarn 3.2.1), the `cwd` arg from
`yarn --cwd $PACKAGES_DIR/e2e wait-for-network`,
invoked by `rebuild-test-db.sh` is ignored.
This causes yarn to simply search for the `wait-for-network` Since `wait-for-network` does not have a colon (:) in the name, it is not picked up when yarn is run from
the root of the repository, so the step fails due to missing script. [Otherwise, if the specified name contains a colon character, and if one of the workspaces in the project
contains exactly one script with a matching name,
then this script will get executed](https://yarnpkg.com/cli/run). There are 2 possible solutions:
- specify path without --cwd, as suggested in the …
> chore(cardano-services): use yarn workspace because cwd is ignored

- packages/cardano-services/test/jest-setup/rebuild-test-db.sh
Our tests historically suffer some instabilities.
When a flaky test fails during the procedure to regenerate the fixtures, implies a huge amount of time to restart it from beginning: from 30m to 1h depending on how much far from the end of the procedure the failing test is.
Launching the tests in `while` loop to let the script to restart them in case of error.
Introduced general rebuild steps at the beginning of the procedure to:
- ensure everything builds before _starting_ the actual rebuild procedure
- perform basic rebuild steps to make the script working even if it is the first action after changing branch
> re-run failing tests when regenerating fixtures

- nix/cardano-services/packages.nix
**LW-9464**
ChromeDriver version was hardcoded. This would break in a non-obvious way on the next ChromeDriver update.
Read the version from `node_modules/chromedriver/lib/chromedriver.js`. The hash will still need to be updated, but at least the error message will be clear, providing both hashes (you can `grep` for the old one and replace it).
It costs us around 5 seconds, I thought it's the least awkward option for the end user (who updates this dependency).
—
> ci: take the exact version from lib/chromedriver.js

- packages/key-management/src/cip8/cip30signData.ts
- packages/key-management/src/types.ts
- packages/key-management/src/util/createWitnesser.ts
- packages/key-management/test/cip8/cip30signData.test.ts
- packages/key-management/test/util/createWitnesser.test.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/web-extension/src/walletManager/SignerManager/types.ts
- packages/web-extension/src/walletManager/walletManager.ts
- packages/web-extension/test/walletManager/SignerManager.test.ts
SignerManager signData requests don’t have ‘address’ property. Instead, it only has derivation path to sign with.
In order to get the address, we need to update Witnesser and SignerManager interfaces to preserve address as additional context of the signing operation.
- SignDataContext now has an additional optional address field.
- Witnesser signBlob now takes a context as one of its arguments (of type SignDataContext, same as SignerManager signData).
> feat!: signerManager and Witnesser now propagate signData confirmation address

- packages/cardano-services/src/Program/programs/projector.ts
- packages/cardano-services/src/Program/programs/types.ts
- packages/cardano-services/src/Projection/prepareTypeormProjection.ts
- packages/cardano-services/src/cli.ts
- packages/e2e/docker-compose.yml
- packages/projection-typeorm/src/operators/storeStakePoolMetadataJob.ts
- packages/projection-typeorm/test/operators/storeStakePoolMetadataJob.test.ts
Latest applied changes in the SDK introduced some delays in fetching stake pool metadata. Since the default retry delay for the job which fetches the metadata is tailored for `live-mainnet` no retries are performed during the rebuild fixtures procedure.
The sum of this two facts makes the newly generated fixtures missing the metadata.
- made the retry delay for the job configurable
- configured said delay to 60" in `local-network`
> LW-9535 configurable metadata job retry delay

- packages/cardano-services/src/PgBoss/stakePoolRewardsHandler.ts
The `pool-rewards` job uses `pgboss.job` table as a registry to check which is the last epoch for which it run.
This is not enough as **pg-boss** archives completed jobs in `pgboss.archive` table:
Added `COUNT(*) FROM pgboss.archive` to the query which performs given check.
> LW-9518 Use `pgboss.archive` table to check computed epoch rewards

- .eslintrc.js
- packages/e2e/test/web-extension/extension/background/walletManager.ts
- packages/e2e/test/web-extension/extension/ui.ts
- packages/projection-typeorm/src/TypeormStabilityWindowBuffer.ts
- packages/projection-typeorm/src/entity/PoolRegistration.entity.ts
- packages/wallet/src/persistence/inMemoryStores/InMemoryCollectionStore.ts
- packages/wallet/src/persistence/inMemoryStores/InMemoryDocumentStore.ts
- packages/wallet/src/persistence/inMemoryStores/InMemoryKeyValueStore.ts
- packages/wallet/src/persistence/pouchDbStores/PouchDbKeyValueStore.ts
- packages/wallet/src/services/ProviderTracker/TrackedWalletNetworkInfoProvider.ts
- packages/web-extension/src/observableWallet/util.ts
- packages/web-extension/src/walletManager/SigningCoordinator/SigningCoordinator.ts
- packages/web-extension/src/walletManager/SigningCoordinator/exposeSigningCoordinatorApi.ts
- packages/web-extension/src/walletManager/SigningCoordinator/types.ts
- packages/web-extension/src/walletManager/SigningCoordinator/util.ts
- packages/web-extension/src/walletManager/WalletRepository/WalletRepository.ts
- packages/web-extension/src/walletManager/WalletRepository/types.ts
- packages/web-extension/src/walletManager/types.ts
- packages/web-extension/src/walletManager/walletManager.ts
- packages/web-extension/src/walletManager/walletManager.types.ts
- packages/web-extension/test/walletManager/SigningCoordinator.test.ts
- packages/web-extension/test/walletManager/WalletRepository.test.ts
- packages/web-extension/test/walletManager/walletManager.test.ts
This PR refactors the `WalletRepository` and related code to handle wallet metadata as well as account metadata.
Introduces a separate `AccountMetadata` type that can be different from the wallet metadata and also splits the `WalletRepository::updateMetadata` into two separate methods `updateWalletMetadata` and `updateAccountMetadata` to avoid confusion and complicated checks.
Both types need to be passed explicitly in most cases as something like `<WalletMetadata extends {}, AccountMetadata extends {} = WalletMetadata>` might be convenient in the first place but obscures the fact that the metadata for wallets and accounts can be different eventually.
> feat(web-extension): handle wallet metadata in repository [LW-9503]

- packages/cardano-services/environments/.env.preprod
- packages/cardano-services/environments/.env.preview
Our `preview` and `preprod` **docker compose** environments are configured to use **smash**, while they should use the `direct` method.
Fixed the cfg
> Fix smash settings in preview and preprod env files

- packages/projection-typeorm/src/operators/storeHandles.ts
- packages/projection-typeorm/test/operators/storeHandles/subhandle.test.ts
ADA Handle rules require all subhandles to have a parent handle. Therefore, we must validate that subhandle has a valid parent handle.
Query for existence of parent handle before inserting a subhandle
> fix(projection-typeorm): ignore orphan subhandles

- compose/common.yml
Shutting down a docker compose infrastructure take a long time due to `cardano-subit-api` hangs.
Changed its stop signal into `SIGINT`.
> LW-9518 Use SIGINT to stop cardano-submit-api

- compose/common.yml
- packages/cardano-services/environments/.env.mainnet
Local test networks in our docker compose infrastructure are using `mainnet` `cardano-token-registry` server URL.
I double checked, this problem do not impact deployed environments.
Fixed the configuration in our docker compose to make test networks using the IOG maintained `dev` server.
> LW-9518 Fix local testnets cfg for cardano-token-registry

- packages/projection/src/operators/logProjectionProgress.ts
@mirceahasegan found a minor bug which is preventing the projector to log the moving average speeds after a restart.
> LW-9518 Log moving average speeds even if after a restart

- packages/e2e/test/web-extension/extension/ui.ts
- packages/util-rxjs/src/TrackerSubject.ts
- packages/util-rxjs/test/TrackerSubject.test.ts
- packages/wallet/test/PersonalWallet/load.test.ts
- packages/wallet/test/PersonalWallet/shutdown.test.ts
- packages/web-extension/src/messaging/remoteApi.ts
- packages/web-extension/src/walletManager/SigningCoordinator/SigningCoordinator.ts
- packages/web-extension/src/walletManager/WalletRepository/WalletRepository.ts
- packages/web-extension/src/walletManager/WalletRepository/types.ts
- packages/web-extension/src/walletManager/types.ts
- packages/web-extension/test/walletManager/SigningCoordinator.test.ts
- packages/web-extension/test/walletManager/WalletRepository.test.ts
- packages/web-extension/test/walletManager/util.ts
- packages/web-extension/test/walletManager/walletManager.test.ts
This PR contains fixes for 2 issues:
1. `WalletRepository` data model is incorrect, because extended**Account**PublicKey is unique to a wallet account, not to a wallet
2. WalletManager.activeWalletId$ emits null when no wallet is active. However, remoteApi.ts implementation relies on TrackerSubject, which uses null to check for value presence and filters it out.
LW-9709 LW-9094 LW-9170
1. Hoist `extendedAccountPublicKey` to `Bip32WalletAccount` type
2. `TrackerSubject.value$` observable type changed to `T | typeof TrackerSubject.NO_VALUE`
> feat: hoist extendedAccountPublicKey into Bip32WalletAccount type

- packages/web-extension/src/walletManager/walletManager.ts
- packages/web-extension/test/walletManager/walletManager.test.ts
When wallet is deactivated, it should emit null to indicate there's no active wallet
When wallet manager is reinitialized after deactivation, it shouldn't load any wallet
LW-9094
> fix(web-extension): delete active wallet from storage and emit null

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/cardano-services/test/ChainHistory/fixtures/FixtureBuilder.ts
- packages/cardano-services/test/ChainHistory/fixtures/queries.ts
- packages/cardano-services/test/data-mocks/tx.ts
The confirmed tx body was missing the `collateralReturn` property, which is required for displaying collaterals in Lace's activity detail view.
> feat(cardano-services): resolve collateralReturn property

- packages/core/src/Cardano/types/Block.ts
- packages/core/test/Cardano/types/Block.test.ts
ogmios 6 production readiness task.
Since `VrfVkBech32.fromHex` utility is used only by the ogmios block mapper, this change goes directly into conway-era branch.
> test(core): add unit tests VrfVkBech32.fromHex

- packages/core/src/Cardano/Address/PaymentAddress.ts
- packages/wallet/src/services/WalletUtil.ts
- packages/wallet/test/services/WalletUtil.test.ts
In order to inspect the transaction that’s build by the dapp, input resolver that we have in WalletUtil is not going to work because it only resolves own addresses.
Create a new input resolver that utilizes the existing one and queries chain history provider for inputs that are not resolved as own
Add a decorator to the inputResolver that additional resolve inputs from the backend if the inputs are not found in our UTXO set.
> feat(wallet): added a new input resolver decorator that also fetches from the backend

- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
Fixtures generated with current cardano stack versions no longer causes problems.
Un-skipped a couple of tests skipped in the past as a quick workaround.
> chore(cardano-services): un-skip previously skipped unit tests

- packages/cardano-services/src/StakePool/DbSyncStakePoolProvider/DbSyncStakePoolProvider.ts
- packages/cardano-services/src/StakePool/TypeormStakePoolProvider/util.ts
- packages/cardano-services/test/StakePool/StakePoolHttpService.test.ts
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.test.ts
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/fitxures/TypeormFixtureBuilder.ts
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/fitxures/queries.ts
- packages/core/src/Provider/StakePoolProvider/util.ts
We want to sort stake pools by a new set of fields.
Implemented the new sorting options.
> LW-9573 Stake pools sorting

- packages/key-management/src/cip8/cip30signData.ts
- packages/key-management/src/types.ts
- packages/key-management/test/cip8/cip30signData.test.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
The blob that's being signed wraps the payload
Adding the actual payload to context makes it easier to display it to the signer
> feat(key-management): add payload to SignDataContext when signing cip8 structure

- packages/core/src/util/transactionSummaryInspector.ts
- packages/core/test/util/transactionSummaryInspector.test.ts
The TransactionSummaryInspector doesn't properly account for transaction fees and always displays them as unresolved balance.
Fix TransactionSummaryInspector to properly account for transaction fees
> fix(core): transactionSummaryInspector now correctly accounts for transaction fees

- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/src/Program/programs/types.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/Program/services/ogmios.test.ts
- packages/cardano-services/test/cli.test.ts
- packages/ogmios/src/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.ts
- packages/ogmios/test/Provider/TxSubmitProvider/OgmiosTxSubmitProvider.test.ts
Handle validation on submit is nice to have, but it should not prevent submitting transactions when it's not possible to do the validation (e.g. due to a bug, handle provider outage, or just not having a handle provider available).
Make handle validation an opt-in feature, so it is now possible to start a tx-submit provider without it.
> feat: add explicit handle validation arg

- packages/cardano-services/test/Program/services/ogmios.test.ts
These tests previously relied on a mocked OgmiosServer, making them tightly coupled with the ogmios implementation.
Since our ogmios implementation was abstracted behind the OgmiosCardanoNode/OgmiosObservableCardanoNode, we can mock them and test the factory utils.
Complete rewrite to not require ogmios server.
Test only the ogmios.ts utils.
> test(cardano-services): test ogmios utils

- packages/core/src/Serialization/TransactionBody/ProposalProcedure/ProposalProcedure.ts
- packages/core/test/Serialization/TransactionBody/ProposalProcedure/ProposalProcedure.test.ts
- packages/tx-construction/src/createTransactionInternals.ts
- packages/tx-construction/src/index.ts
- packages/tx-construction/src/tx-builder/TxBuilder.ts
- packages/tx-construction/src/tx-builder/initializeTx.ts
- packages/tx-construction/src/tx-builder/types.ts
- packages/tx-construction/src/types.ts
- packages/tx-construction/test/createTransactionInternals.test.ts
- packages/tx-construction/test/tx-builder/TxBuilder.test.ts
- packages/web-extension/src/observableWallet/util.ts
Implement a method that would allow users of TxBuilder to update the transaction body.
For example, a user could build and insert a certificate, allowing the user to leverage the input selection, fee calculation, etc, even if TxBuilder does not have a high-level API to support adding that certificate.
Non-goal: guard users against malformed/incorrect transactions.
For example: users could potentially modify the certificates already added by the txbuilder for staking distribution.
Add a `customize` method to TxBuilder. The callback passed into `customize` will be called on transaction `build`, before input selection is performed.
> feat(tx-construction): add customizeCb to GenericTxBuilder

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/core/src/Cardano/types/Transaction.ts
- packages/core/src/Serialization/Certificates/PoolRegistration.ts
- packages/projection/test/InMemory/storeStakePools.test.ts
- packages/projection/test/operators/Mappers/certificates/withStakePools.test.ts
Stake key de-registration certificates currently has a wrong deposit value (the value from relative epoch parameters rather than the value from epoch parameters relative to when stake key was registered).
Stake pool registration certificates doesn't show any deposit.
- Fixed the deposit value for stake key de-registration certificates.
- Added the deposit for stake pool registration certificates.
> LW-9604 deposit values

- packages/core/src/Asset/NftMetadata/fromMetadatum.ts
- packages/core/src/Cardano/types/Asset.ts
The `asset-projector` exit with error while projecting.
Wrapped the line throwing in a `try / catch` block.
> fix(core): make the projector not exit on asset name error

- nix/cardano-services/deployments.nix
- nix/cardano-services/oci-images.nix
Keeps OCI image from rebuilding on each commit by taking into account only sources and not commit hash. Fixes https://github.com/input-output-hk/lace-ops/issues/29
commit has is no longer part of OCI image, it is passed separately
> chore: pass BUILD_INFO via deployments

- packages/hardware-ledger/src/LedgerKeyAgent.ts
- packages/hardware-trezor/src/TrezorKeyAgent.ts
Webpack exports ledger and trezor libaries under `{default: {...}}`.
We're [already using a hack for this for Ledger](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/hardware-ledger/src/LedgerKeyAgent.ts#L35-L40). This PR applies the same for Trezor.
Also fixed Ledger error mapping, when device is already open
> fix: trezor bundler compatibility

- packages/core/src/Serialization/Common/Anchor.ts
- packages/core/test/Serialization/Common/Anchor.test.ts
For cardano-node-8.8 the length of urls will be increased from 64 -> 128 bytes - see in CDDL here.
This will allow much more flexibility in URLs which can be used for governance metadata anchors and pool metadata anchors.
For examples, IPFS links will be able to be used to store off-chain metadata. (edited).
Master branch (pre-conway) does not support the 128bytes anchors. Even so, usage of >64bytes anchors will result in a failed anchor, until `master` branch also uses Cardano Node 8.8+
> feat(core): cbor ser/des handle 128 bytes anchors

- packages/core/src/Serialization/TransactionBody/TransactionBody.ts
- packages/core/test/Serialization/TransactionBody/TransactionBody.test.ts
There is a bug in the transaction body serialization logic which causes incorrect CBOR to be produced if there are no inputs in the transaction.
Fix the bug
> fix(core): transaction body can now serializes bodies with no inputs correctly

- nix/cardano-services/packages.nix
During OCI image build there is an IFD which is super annoying during deployments, this PR attempts to fix it
Pass empty file instead of chromedriver since it is unused during build anyways
> chore: pass fake chromedriver to package build to avoid IFD

- packages/projection-typeorm/test/createTypeormTipTracker.test.ts
#1129 was not enough: skipping the test moved the error to next one.
Skipped the entire `describe` block.
> test(projection-typeorm): skip flaky tests

- .github/workflows/std-release.yaml
- .github/workflows/std.yml
- README.md
[LW-9880](https://input-output.atlassian.net/browse/LW-9880)
→ Jira
A [run that proves](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/8155419455) that the new deployment matrix works.
→ Jira
→ Jira
[LW-9880]: https://input-output.atlassian.net/browse/LW-9880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LW-9880] ci: deploy dev-preprod & dev-mainnet on release

- packages/wallet/src/PersonalWallet/PersonalWallet.ts
- packages/wallet/src/persistence/inMemoryStores/inMemoryWalletStores.ts
- packages/wallet/src/persistence/pouchDbStores/pouchDbWalletStores.ts
- packages/wallet/src/persistence/types.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/src/services/WalletUtil.ts
- packages/wallet/src/services/types.ts
- packages/wallet/src/services/util/equals.ts
- packages/wallet/src/services/util/index.ts
- packages/wallet/src/services/util/newAndStoredMulticast.ts
- packages/wallet/test/integration/cip30mapping.test.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
- packages/wallet/test/services/UtxoTracker.test.ts
- packages/wallet/test/services/WalletUtil.test.ts
- packages/wallet/test/services/util/equals.test.ts
- packages/wallet/test/services/util/newAndStoredMulticast.test.ts
- packages/wallet/test/util.ts
- packages/web-extension/src/observableWallet/util.ts
LW-9469 - Support for transaction chaining
Created `ObservableWallet.transactions.outgoing.signed$` which is an Observable of an array of transactions.
- New transactions are added to it as they are signed
- Removed from it when they are either
- inFlight$
- tip is > validityInterval.invalidHereafter
- any input utxo is consumed by other transaction in history$
- ~~explicitly dismissed~~
~~Consumed utxo from signed transactions are removed from `ObservableWallet.utxo.available$`~~
Created `signTx` util function to replace usage of observable wallet `finalizeTx` as it was interfering with tests expectation of utxos to be present in `wallet.utxo.total$`.
> [LW-9469] Cache signed transactions

- packages/core/src/Cardano/types/Governance.ts
- packages/core/src/Serialization/TransactionBody/ProposalProcedure/HardForkInitiationAction.ts
- packages/core/test/Serialization/TransactionBody/ProposalProcedure/HardForkInitiationAction.test.ts
While working on LW-9418 I discovered a couple of problems.
Please check the commits
> LW-9418 hard fork proposal fixes

- compose/common.yml
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/mappers.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/queries.ts
- packages/cardano-services/src/NetworkInfo/DbSyncNetworkInfoProvider/types.ts
- packages/e2e/local-network/scripts/make-babbage.sh
- packages/e2e/src/util/util.ts
- packages/e2e/test/wallet/PersonalWallet/conwayTransactions.test.ts
We need to cover Conway era transactions in our e2e test.
Added a test suite with many (hopefully all) transactions with new features in Conway era
- Fixed DRep representation in related certificates
- Fixed newly added deposits in Conway era in `DbSyncChainHistoryProvider`
- Fixed `NewConstitution` proposal representation in `DbSyncChainHistoryProvider`
- Bumped protocol major version in local-testnet
- Fixed containers dependencies in docker compose infrastructure
> LW-9418 Add Conway era txs e2e tests

- .github/workflows/std.yml
Triggering `dev-preprod` manually [failed with a JSON error](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/8232153217).
Looking at the error, the `fromJSON` function got an empty string:
```
Error when evaluating 'strategy' for job 'deploy'. .github/workflows/std.yml (Line: 235, Col: 18): 
Error parsing fromJson,.github/workflows/std.yml (Line: 235, Col: 18): 
Error parsing fromJson,.github/workflows/std.yml (Line: 235, Col: 18): 
Error reading JToken from JsonReader. Path '', line 0, position 0.,.github/workflows/std.yml (Line: 235, Col: 18): 
Unexpected value ''
```
I don't get how it's possible that `dev-preview` _ever_ worked, if `needs`' outputs are only available when you specify `needs:` explicitly?
Or maybe they are available indeterministically 😕 
Successful …
> ci: fix `dev-preprod` deployment

- packages/cardano-services-client/src/version.ts
- packages/cardano-services-client/version.json
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/openApi.json
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/e2e/test/wallet/PersonalWallet/phase2validation.test.ts
- db-sync chain-history provider maps consumed collateral amount to fee property. It should be setting totalCollateral instead, and (if the original fee property of transaction body is unavailable), set fee: 0n
- similarly, we seem to be mapping the consumed collateral inputs into body.inputs. Test this, and update the mapping to map to body.collaterals (leaving inputs as an empty array, like with the fee)
- lastly, same for outputs and collateralOutput
> fix(cardano-services): phase-2 failure tx mapper

- .github/workflows/std-release.yaml
Deployment on release failed – https://github.com/input-output-hk/cardano-js-sdk/actions/runs/8249290630.
You don’t use `steps:`, see <https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow>
~~I don’t know how this ever worked… (again)~~ — it [never has](https://github.com/input-output-hk/cardano-js-sdk/actions/workflows/std-release.yaml)
n/a
> ci: fix calling convention of std.yml from std-release.yml

- nix/cardano-services/deployments/default.nix
We did few cardano-stack migrations, some references had to change. Also removed the unversioned dev-preprod since it is no longer used
> Update deployment references

- packages/crypto/src/Bip32/Bip32PrivateKey.ts
While looking into how Cardano handles Bip32, specifically how it generates keys from Bip39-word entropy, I discovered that the error message in question kept correcting me for providing a 64-byte length key and not a 32-byte length key. However, the actual check is done against 96-bytes, i.e. the length of xprv after the pbkdf2 algorithm.
Perhaps the idea is that the original entropy should be 32-bytes and that's why NORMAL_ED25519_PRIVATE_KEY_LENGTH is set to that. However, that's not what the if-statement is actually checking against.
Replace NORMAL_ED25519_PRIVATE_KEY_LENGTH with BIP32_ED25519_PRIVATE_KEY_LENGTH, the length that is actually checked against.
None.
> fix(crypto): replace variable in keylength error message

- packages/web-extension/src/walletManager/walletManager.ts
- packages/web-extension/src/walletManager/walletManager.types.ts
We want to be able to force the reloading of a wallet even if its properties haven't changed. this is useful when configuring wallet providers differently.
Add a new optional field "force" that if set to true always re-activates the wallet.
A new param 'force' has been added to the wallet manager
> feat(web-extension): added an optional parameter to WalletManager acivate to allow force reload

- packages/cardano-services-client/src/TxSubmitProvider/TxSubmitApiProvider.ts
- packages/cardano-services/src/Program/programs/providerServer.ts
In order to enable custom TX Submit endpoints in Lace, we need to modify our TxSubmitApiProvider to take an axio adapter so it can work on browser environments.
Add a new parameter to the TxSubmitApiProvider so it can take the Axio adapter for the browser.
TxSubmitApiProvider now takes an extra argument in its constructor
> feat(cardnao-services): txSubmitApiProvider now takes axios adapter

- .github/workflows/std.yml
Discovered in #1162
In those runs, the workflow doesn’t have access to our secrets, so they fail.
@mkazlauskas wants to not run the workflow then.
n/a
> ci: don’t run `std.yml` on PRs from forks

- .github/workflows/std-release.yaml
- .github/workflows/std.yml
[LW-10154](https://input-output.atlassian.net/browse/LW-10154)
See Jira.
Here’s a commit (6c82af41bdc7c6984bdc17f7925180204576354e) that proves that [the secrets are being passed now](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/8434171309/job/23096848796#step:2:1).
n/a
[LW-10154]: https://input-output.atlassian.net/browse/LW-10154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LW-10154] ci: make `secrets` available through `workflow_call:`

- .github/workflows/std.yml
- nix/cardano-services/deployments/default.nix
https://input-output.atlassian.net/browse/LW-10177
The only difference here is that `staging-preprod@us-east-1@v2` points to whatever is on latest master
> Deploy staging preprod

- packages/projection-typeorm/test/createTypeormTipTracker.test.ts
Unit tests often fails with following error.
```
FAIL test/createTypeormTipTracker.test.ts
● createTypeormTipTracker › with failing connection › reconnects and eventually emits the tip
QueryFailedError: relation "block" does not exist
at PostgresQueryRunner.query (../../src/driver/postgres/PostgresQueryRunner.ts:299:19)
at SelectQueryBuilder.loadRawResults (../../src/query-builder/SelectQueryBuilder.ts:3787:25)
at SelectQueryBuilder.executeEntitiesAndRawResults (../../src/query-builder/SelectQueryBuilder.ts:3
at SelectQueryBuilder.getRawAndEntities (../../src/query-builder/SelectQueryBuilder.ts:1669:29)
at SelectQueryBuilder.getMany (../../src/query-builder/SelectQueryBuilder.ts:1759:25)
at src/createTypeormTipTracker.ts:29:34
```
Skipped the flaky test
> test(projection-typeorm): skip flaky test

- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/ChainHistoryBuilder.test.ts
- packages/cardano-services/test/ChainHistory/fixtures/FixtureBuilder.ts
- packages/cardano-services/test/ChainHistory/fixtures/queries.ts
- packages/cardano-services/test/data-mocks/tx.ts
We need to add Conway era txs unit tests
Added unit tests to `DbSyncChainHistoryProvider`.
> LW-9419 conway era unit tests

- packages/input-selection/src/GreedySelection/util.ts
- packages/input-selection/test/GreedySelection/GreedySelection.test.ts
There was a bug in the greedy input selector that was causing some of the change outputs to be discarded if the UTXO didn't have enough ADA to hold more native assets.
When an UTXO can not hold any more native assets (due to its min value constraint), the UTXO needs to be removed from the list of UTXOs that can hold assets, but have to be later merged back with the rest of the assets before returning the selection.
> fix(input-selection): greedy input selector now correctly distributes assets among addresses

- packages/cardano-services/test/jest-setup/rebuild-test-db.sh
- packages/e2e/src/util/util.ts
- packages/e2e/test/local-network/register-pool.test.ts
- packages/e2e/test/long-running/shared-wallet-delegation-rewards.test.ts
- packages/e2e/test/long-running/simple-delegation-rewards.test.ts
While working in `conway-era` for `LW-9422` I noticed:
- some change in that branch could be imported in `master` branch;
- some e2e test files has _conflicting names_.
The `rebuild-test-db.sh` file had following command:
```
yarn workspace @cardano-sdk/e2e test:long-running delegation-rewards.test.ts
```
this was making it to start more tests than required.
- Cherry picked the _cross-branch changes_;
- Changed test file and case names to no longer be ambiguous.
> LW-9422 Conway era cherry pick

- packages/cardano-services/test/ChainHistory/ChainHistoryHttpService.test.ts
- packages/cardano-services/test/ChainHistory/fixtures/queries.ts
- packages/cardano-services/test/StakePool/DbSyncStakePoolProvider/StakePoolBuilder.test.ts
With the introduction of `cardano-node 8.8` some test was disabled: we need to re-enable them.
- `buildAndQuery, queryPoolHashes & queryTotalCount`: was enough to re-enable it, most likely previously rebuild fixtures was enough;
- `finds transactions with address within outputs`: it uses `fixtureBuilder.getGenesisAddresses()`; I have no idea about what was changed from previous version to make genesis addresses no longer having ids starting from 1, but I know which is the value of their utxos: changed the `fixtureBuilder` to get genesis addresses regardless from their ids;
- `Ada handle`: it seems a bug was introduced in `cardano-submit-api`: submitting txs through `ogmios` fixes the problem.
> LW-9889 Re-enable skipped tests

- compose/aarch64.yml
[LW-8192](https://input-output.atlassian.net/browse/LW-8192)
PR analogous to #1171 – look there for details.
`yarn sanchonet:up` works 😌 
[LW-8192]: https://input-output.atlassian.net/browse/LW-8192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LW-8192] chore: enable running on AArch64 (`conway-era`)

- nix/cardano-services/deployments/default.nix
- nix/cardano-services/operables.nix
- nix/cardano-services/packages.nix
intent here is to test tracing-gc in dev-mainnet
> chore: enable gc tracing

- nix/cardano-services/deployments/backend.provider.nix
- nix/cardano-services/deployments/default.nix
- nix/cardano-services/deployments/stake-pool.nix
- nix/local/envs.nix
**This PR implements:**
- Migration of live-mainnet from legacy us-east-1 to us-east-2 cluster
- Removal of Lace 1.8 compatible deployments
- As recently discussed disabling of handle provider in `live-pre*` deployments
This PR is expected to be merged to `release/cardano-services/0.27.x` branch which will be merged back to master
> Deploy new live mainnet

- packages/hardware-trezor/src/transformers/withdrawals.ts
This is a continuation of https://github.com/input-output-hk/cardano-js-sdk/pull/1216 adding a missing safe comparison to mitigate CWE-208 vulnerability
> [LW-10288] - Added missing comparison from audit in IOHKCYB-596

- packages/cardano-services/src/PgBoss/stakePoolRewardsQueries.ts
- packages/cardano-services/src/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.ts
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/util.test.ts
- packages/cardano-services/test/cli.test.ts
- packages/core/src/Provider/StakePoolProvider/types/StakePoolProvider.ts
We need to tweak default fuzzy search options to find better ones for our use case.
Added `location` and `distance` to the set of used fuzzy options.
Ensure `stake-pool-rewards` job selects only `leader` and `member` rewards: exclude `refunds` and eventual newly added types.
> LW-10308 New fuzzy options

- compose/common.yml
CI no longer works as `db-sync`, `cardano-node` and `cardano-submit-api` docker images are no longer available on Docker hub.
- Changes the `db-sync` docker repository to `ghcr.io/intersectmbo`.
- Changes the `cardano-node` and `cardano-submit-api` docker repository to `public.ecr.aws/e8d0p1a5` (thanks to @gytis-ivaskevicius ).
Bumped `db-sync` version from `13.1.0.0` to `13.1.0.2` because the one used before this change is no available in the new repository.
> LW-10426 db-sync, cardano-node and cardano-submit-api docker images

- nix/cardano-services/deployments/default.nix
As of creating this PR we have 3.29TB of logs since beginning of the month, sometimes they are getting discarded due to the Grafana rate limit
Set logging severity to `info` instead of `debug` to optimize for cost and avoid discarding logs. This can be easily temporarily switched back if there is a need
> Reduce logs

- .github/workflows/std.yml
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/src/ChainHistory/openApi.json
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/core/src/Cardano/types/Transaction.ts
This fails:
```
curl 'https://live-mainnet.lw.iog.io/v2.0.0/chain-history/txs/by-addresses' \
-H 'authority: dev-mainnet.lw.iog.io' \
-H 'accept: application/json, text/plain, */*' \
-H 'accept-language: en-US,en;q=0.9' \
-H 'content-type: application/json' \
-H 'origin: chrome-extension://gafhhkghbfjjkeiendhlofajokpaflmk/' \
-H 'sec-fetch-dest: empty' \
-H 'sec-fetch-mode: cors' \
-H 'sec-fetch-site: none' \
-H 'sec-gpc: 1' \
-H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36' \
-H 'version-api: "3.0.0"' \
-H 'version-software: 0.17.9' \
--data-raw '{"addresses":["addr1qyf9jlvjr6en2wjkyrcdge0c8xrhgflkg4m5kwhl4yfw7g4yw2z95kepz8urcn8gl425e2jqm2pv94rm959yvqvcg32q286tna"],"blockRange":{"lowerBound":{"__type":"undefined"}},"pag …
```
> fix(cardano-services): correct mapping of chain history redeemer purpose

- packages/hardware-ledger/src/LedgerKeyAgent.ts
- packages/hardware-ledger/src/transformers/certificates.ts
- packages/hardware-ledger/src/transformers/index.ts
- packages/hardware-ledger/src/transformers/tx.ts
- packages/hardware-ledger/src/transformers/withdrawals.ts
- packages/hardware-ledger/test/testData.ts
- packages/hardware-ledger/test/transformers/certificates.test.ts
- packages/hardware-ledger/test/transformers/tx.test.ts
- packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
Adjust mappers to match new `conway-era` certificates.
> [LW-10219]  Ledger: Sign new certificate types

- packages/util-dev/src/createStubStakePoolProvider.ts
Fuzzy search on text metadata fields has been implemented on StakePoolsProvider.
StakePoolProviderStub should mimic the same functionality.
Adjust `queryStakePools` method in `packages/util-dev/src/createStubStakePoolProvider.ts` so it could query proper pools matching `text` filtering option.
> feat(util-dev): adjust stakePoolProviderStub with text filters option

- packages/e2e/package.json
While working on other tasks I realized in our `local-network` we are not honoring the `.env.local` file.
Loaded it at `local-network` startup.
> chore(e2e): honor the .env.local file

- packages/cardano-services/src/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.ts
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.test.ts
The fuzzy stage pools search of `TypeormStakePoolProvider` throws an error in case of empty search result.
Fixed the SQL in this edge case.
> fix(cardano-services): stake pool fuzzy search empty result

- packages/cardano-services/src/Projection/migrations/1715157190230-rewards-pledge-numeric.ts
- packages/cardano-services/src/Projection/migrations/index.ts
- packages/projection-typeorm/src/entity/PoolRewards.entity.ts
Working on LW-10287 I noticed some `mainnet` stake pool has a `pledge` greater than the maximum `int8`.
Changed the type of `PoolRewardsEntity.pledge` column to accept those values as well.
> fix: increase the size of pledge column of stake pool rewards table

- packages/core/src/Asset/NftMetadata/fromMetadatum.ts
- packages/core/src/Asset/NftMetadata/fromPlutusData.ts
- packages/core/test/Asset/NftMetadata/fromMetadatum.test.ts
- packages/core/test/Asset/NftMetadata/fromPlutusData.test.ts
1. CIP-68 assets ([example](https://preprod.cexplorer.io/asset/asset14w53nf5ghakjcp37ruj7a8ffavjpn2cxamdvsl)) minted with NMKR are not compliant with [CIP-68](https://cips.cardano.org/cip/CIP-0068), as datum is missing the 3rd `extra` item (must be set to `#6.121([])` if not used
2. Some assets are minted without 'name' (only 'image')
3. [Current cip25 spec](https://cips.cardano.org/cip/CIP-0025) has an example of 'version' represented as a number (not string) and our current implementation expects a string. There are probably assets that we wouldn't be able to parse due to that. 
- Loosen nft metadata validation by adding a 'strict' argument; loose by default
- Make version parsing more flexible, supporting both string and number
> feat(core): nft metadata parsing loose mode

- packages/e2e/test/web-extension/extension/ui.ts
- packages/web-extension/README.md
- packages/web-extension/src/walletManager/SigningCoordinator/SigningCoordinator.ts
- packages/web-extension/test/walletManager/SigningCoordinator.test.ts
It's difficult to confirm that we don't have roundtrip issues when troubleshooting
Add log of transaction id that is being signed
> feat(web-extension): add log of transaction id when signing

- compose/common.yml
- packages/cardano-services/src/Asset/TypeOrmNftMetadataService.ts
- packages/cardano-services/src/Asset/TypeormAssetProvider/TypeormAssetProvider.ts
- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/core/src/Asset/NftMetadata/fromMetadatum.ts
- packages/core/src/Cardano/types/Asset.ts
- packages/core/test/Cardano/types/Asset.test.ts
Some characters in asset names are valid utf-8, but not ones we want to store in database, add the ability to strip these.
- Add param `stripInvisibleCharacters` to `AssetName.toUTF8` function to remove control/invisible characters
- Remove check on asset name when fetching nft metadata
> [LW-10173] fix utf8 decoding asset name

- packages/cardano-services/src/Http/HttpServer.ts
- packages/cardano-services/test/Http/HttpServer.test.ts
Found as a part of [LW-7619](https://input-output.atlassian.net/browse/LW-7619).
`path.join` is being used for constructing the HTTP paths when registering handlers. This is useful, because the developer doesn’t have to keep track of `../`, double slashes, no slashes, leading slashes, following slashes etc.
At the same time, Windows uses backslashes in its paths, and therefore in `path.join`.
Let’s add a `.replaceAll`.
I tested this code on Windows and it works there.
_n/a_
[LW-7619]: https://input-output.atlassian.net/browse/LW-7619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: register HTTP handlers with forward slashes on Windows

- nix/cardano-services/deployments/default.nix
Some times ago we added `--trace-gc` option to try to identify if we had some garbage collector related problems.
Next we realized the problems had distinct sources.
Now we do not need this, while it is _flooding_ our logs in grafana with _useless_ information.
Removed the `--trace-gc` option.
> chore: remove --trace-gc from provider-server

- packages/projection-typeorm/src/pgBoss.ts
- packages/projection-typeorm/test/operators/storeStakePoolRewardsJob.test.ts
pg-boss jobs have their own (well handled by pg-boss itself) retry strategy.
Recently we were warried about some edge cases:
-  what happens when the `pg-boss-worker` dies (so the final `UPDATE` is not performed)?
-  what happens when the DB server dies so `pg-boss-worker` has no chances to perform final `UPDATE`?
pg-boss handles these case as well: jobs have an expiry timeout, once expired, they are retried anyway.
Another interesting pg-boss option in this field is the job retention time (by default two weeks): a job, till not successfully completed, is retried for two weeks.
Increased the retention time to one year, to have a chance to address problems even if spotted later than the default two weeks.
> LW-10511 Increase pg-boss jobs retention to one yaer

- packages/cardano-services/docker-compose.yml
- packages/cardano-services/src/Program/programs/blockfrostWorker.ts
While working on LW-10560 I realized we are refreshing stake pool metrics once per day, but recently I agreed with legal team we are refreshing them about every 5 hours.
Increased the rate to six times per day (each four hours).
> Increase stake pool metrics refresh rate

- nix/cardano-services/deployments/backend-ingress.nix
Probably all provider routes should be configured above monolithic ones so they would overwrite it without any additional configuration
> chore: prefer asset provider route if it is deployed

- packages/e2e/test/wallet/PersonalWallet/handle.test.ts
`Ada handle` test suite was skipped due to a tx deserialization problem in `cardano-submit-api` which was solved in the latest version.
Un-skipped the test suite
> test(e2e): re-enable previously skipped test

- packages/e2e/.env.example
- packages/e2e/package.json
- packages/e2e/src/environment.ts
- packages/e2e/src/factories.ts
- packages/e2e/src/util/util.ts
- packages/e2e/test/long-running/shared-wallet-delegation-rewards.test.ts
- packages/e2e/test/long-running/simple-delegation-rewards.test.ts
- packages/e2e/test/wallet/PersonalWallet/byron.test.ts
- packages/e2e/test/wallet/PersonalWallet/delegationDistribution.test.ts
- packages/e2e/test/wallet/PersonalWallet/handle.test.ts
- packages/e2e/test/wallet/PersonalWallet/mint.test.ts
- packages/e2e/test/wallet/PersonalWallet/multiAddress.test.ts
- packages/e2e/test/wallet/PersonalWallet/multisignature.test.ts
- packages/e2e/test/wallet/PersonalWallet/nft.test.ts
- packages/e2e/test/wallet/PersonalWallet/txChainHistory.test.ts
- packages/e2e/test/wallet/PersonalWallet/unspendableUtxos.test.ts
- packages/e2e/test/wallet/SharedWallet/delegation.test.ts
- packages/e2e/test/wallet/SharedWallet/simpleTx.test.ts
- To run e2e tests against networks like preprod/preview/mainnet, we need to adjust the timeouts to be more generous.
- Fix mint test to burn tokens only from the test policyId, to avoid signing issues.
Introduced a new env variable `NETWORK_SPEED=slow|fast`. Default is `fast`, for running e2e tests against the local-testnet.
> LW-7691 e2e tests on preprod adjustments

- packages/projection-typeorm/test/operators/storeNftMetadata.test.ts
- packages/projection-typeorm/test/operators/util.ts
- packages/projection/src/operators/Mappers/withNftMetadata.ts
- packages/util-dev/src/chainSync/data/missing-extra-datum-metadata-problem.json
- packages/util-dev/src/chainSync/index.ts
Projecting NFT metadata does not project it for https://preprod.cexplorer.io/asset/asset14w53nf5ghakjcp37ruj7a8ffavjpn2cxamdvsl
LW-9799
It was validating shape of the datum in 2 places
Add a new chain sync events dataset
> fix: project datum nft metadata with missing extra field

- .kube/eu-central-1
- .kube/us-east-1
- .kube/us-east-2
- scripts/deployed-db.sh
The script we have to connect to deployed DBs (thank you very much @gytis-ivaskevicius) requires some explicit data as input parameter, some of them must be kept in mind (as the name of the regions) some could be determined by the script itself (as the region for `dev` environments).
Added a new scripts which performs some checks and computations and accepts shortened input parameters.
I tried a first implementation through the `justfile` (nice tool!), but I had some problems with complex bash syntaxes as `cat << EOF`, so to make it fast, I added a new script outside of `justfile`.
We could improve this by moving the script inside the `justfile`.
> Improve db selection through input parameters while connecting to deployed databases

- packages/projection-typeorm/src/entity/NftMetadata.entity.ts
- packages/projection-typeorm/src/entity/transformers.ts
- packages/projection-typeorm/test/operators/storeNftMetadata.test.ts
- packages/util-dev/src/chainSync/data/extra-data-null-characters-problem.json
- packages/util-dev/src/chainSync/index.ts
- packages/util/test/serializableObject.test.ts
Projecting assets on mainnet fails with
```
{
query: 'INSERT INTO "nft_metadata"("name", "description", "image", "media_type", "files", "type", "other_properties", "user_token_asset_id", "parent_asset_id", "created_at_slot") VALUES ($1, DEFAULT, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING "id"',
parameters: [
'Baddy',
'ipfs://QmUuAp49pB1yNHgS21j5yRQMeBumuBDDWyFQdNEWCTvKnD',
'image/png',
'[]',
'CIP-0025',
'{"__type":"Map","value":[["symbol","\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000BADD"],["decimals",{"__type":"bigint","value":"0"}]]}',
'65bcf672806de8a2335576339e801d41f3275c0c07dd6aadf2ea41d9000000000042414444',
'65bcf672806de8a2335576339e801d41f3275c0c07dd6aadf2ea41d9000000000042414444',
72845971
],
driverError: error: unsupported Unicode escape sequence
at Parser.parseErrorMessage …
```
> fix: sanitize other_properties

- packages/tx-construction/src/input-selection/selectionConstraints.ts
- packages/tx-construction/test/tx-builder/TxBuilderPlutusScripts.test.ts
Redeemer indices must be computed relatively to the lexicographical order of the inputs
Sort the inputs before calculating the indices
> fix(tx-construction): tx-builder now computes redeemer indices correctly everytime

- packages/e2e/local-network/scripts/make-babbage.sh
- packages/e2e/local-network/scripts/pools/update-node-utils.sh
`conway-era` branch introduces several changes in the `local-network` startup scripts.
This small PR is aimed to slightly reduce the diff between the two main branches in order to facilitate next merges reducing the chances of merge conflicts.
Changing the `--supply-delegated` option also helped to remove the ugly `sed` applied to the `genesis/shelley/genesis.json` file.
> LW-10576 follow up

- packages/core/src/Serialization/PlutusData/PlutusList.ts
- packages/core/test/Serialization/PlutusData.test.ts
PlutusList is not encoding following canonical CBOR (uses indefinite length array rather than the definite length form). see https://github.com/input-output-hk/cardano-js-sdk/issues/1318
PlutusList should encode by default using definite length CBOR arrays.
> fix(core): plutus list now encodes to canonical CBOR

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
Version `sancho-4-2-1` of **db-sync** introduced some new `deposit` fields.
Used them to simplify queries performed by `DbSyncChainHistoryProvider`.
> LW-10561 - Use new deposit fields from db-sync

- packages/e2e/src/util/createMockKeyAgent.ts
- packages/e2e/src/util/util.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/multisignature.test.ts
- packages/e2e/test/wallet_epoch_0/SharedWallet/utils.ts
- packages/hardware-ledger/src/LedgerKeyAgent.ts
- packages/hardware-ledger/test/LedgerKeyAgent.test.ts
- packages/hardware-trezor/src/TrezorKeyAgent.ts
- packages/key-management/src/InMemoryKeyAgent.ts
- packages/key-management/src/KeyAgentBase.ts
- packages/key-management/src/types.ts
- packages/key-management/src/util/key.ts
- packages/key-management/test/InMemoryKeyAgent.test.ts
- packages/key-management/test/KeyAgentBase.test.ts
- packages/wallet/test/services/KeyAgent/restoreKeyAgent.test.ts
- packages/web-extension/src/walletManager/SigningCoordinator/SigningCoordinator.ts
- packages/web-extension/src/walletManager/WalletRepository/WalletRepository.ts
- packages/web-extension/src/walletManager/WalletRepository/types.ts
- packages/web-extension/src/walletManager/types.ts
- packages/web-extension/test/walletManager/WalletRepository.test.ts
- packages/web-extension/test/walletManager/util.ts
Key agent only supported CIP1852 which would make it impossible to create multi-sig keys complaint with CIP-1954
Add support for CIP 1854 to key agent and wallet repository.
> feat: add support for cip 1854

- packages/core/src/Serialization/PlutusData/PlutusList.ts
- packages/core/test/Serialization/PlutusData.test.ts
This PR fixes properly the CBOR encoding of Plutus Lists (see https://github.com/input-output-hk/cardano-js-sdk/pull/1319#issuecomment-2151584168 for context)
Plutus List will be encoded as an empty array `80` when the list is empty, and as an indefinite length array when there are one or more elements.
> fix: plutus list now serializes using the correct encoding depending on its size

- nix/cardano-services/packages.nix
[LW-10722](https://input-output.atlassian.net/browse/LW-10722)
Minor breakage of `dev-preview`.
More/less a one-liner, see the diff.
I also added a test, which would've caught it in the original PR #1325.
[LW-10722]: https://input-output.atlassian.net/browse/LW-10722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LW-10722] chore: fix OCI after #1325

- packages/cardano-services/package.json
- packages/wallet/package.json
- yarn.lock
In some packages we are using `envalid` `v7.3.0`, in some others `envalid` `v7.3.1`.
Bumped the version in those packages using the lower one.
> chore: unify envalid version

- packages/util-dev/package.json
This package has it's own variant of esm-package.json, because it has to set the 'browser' field to omit docker.js from browser builds.
> chore(util-dev): copy the correct esm-package.json

- packages/hardware-ledger/src/LedgerKeyAgent.ts
- packages/hardware-trezor/src/TrezorKeyAgent.ts
This PR removes the device model's guard. All the possible Trezor and Ledger devices are whitelisted now. It is up to the end app to restrict usage.
[Jira](https://input-output.atlassian.net/browse/LW-10698)
- All Trezor and Ledger device models are whitelisted now
> chore: whitelist all device models

- packages/cardano-services-client/src/AssetInfoProvider/assetInfoHttpProvider.ts
- packages/cardano-services-client/src/ChainHistoryProvider/chainHistoryHttpProvider.ts
- packages/cardano-services-client/src/HandleProvider/handleHttpProvider.ts
- packages/cardano-services-client/src/HttpProvider.ts
- packages/cardano-services-client/src/NetworkInfoProvider/networkInfoHttpProvider.ts
- packages/cardano-services-client/src/RewardsProvider/rewardsHttpProvider.ts
- packages/cardano-services-client/src/StakePoolProvider/stakePoolHttpProvider.ts
- packages/cardano-services-client/src/TxSubmitProvider/txSubmitHttpProvider.ts
- packages/cardano-services-client/src/UtxoProvider/utxoHttpProvider.ts
- packages/cardano-services-client/test/ChainHistoryProvider/chainHistoryProvider.test.ts
LW-10778
openApi 3.1.0 version bump brought only two conway-era specific Redeemer purpose enum values: "vote" and "propose". Which makes it backwards compatible to 3.0.1 back-ends. But the version check does not allow querying 3.0.1 back-ends. 
This change will allow users to override the 3.1.0 version and perform requests with any custom version, in this case 3.0.1
> chore(cardano-services-client): LW-10778 allow openapiVersion override when configuring client providers

- .github/workflows/std.yml
This fixes the flaky `curl: Argument list too long` error.
E.g. [here](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/9578082666/job/26408697313?pr=1337#step:8:38), but @mkazlauskas has been seeing it for some time now. 
Read the PR comment from a file, not from `argv`.
_n/a_
> chore(ci): fix "curl: Argument list too long"

- .eslintrc.js
- packages/e2e/test/long-running/multisig-wallet/MultiSigWallet.ts
- packages/e2e/test/projection/single-tenant-utxo.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/plutusTest.test.ts
- packages/ogmios/src/CardanoNode/OgmiosObservableCardanoNode/OgmiosObservableCardanoNode.ts
- packages/wallet/src/persistence/pouchDbStores/PouchDbCollectionStore.ts
- packages/wallet/src/persistence/pouchDbStores/PouchDbDocumentStore.ts
- packages/wallet/src/persistence/pouchDbStores/PouchDbKeyValueStore.ts
- packages/wallet/src/persistence/pouchDbStores/PouchDbStore.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/web-extension/test/remoteApi/remoteApi.integration.test.ts
> chore: disable promise/always-return eslint rule

- packages/crypto/src/Bip32/Bip32PrivateKey.ts
- packages/crypto/src/Bip32Ed25519.ts
- packages/crypto/src/strategies/CmlBip32Ed25519.ts
- packages/crypto/src/strategies/SodiumBip32Ed25519.ts
- packages/crypto/test/bip32/Bip32PrivateKey.test.ts
- packages/crypto/test/strategies/Bip32Ed25519.test.ts
- packages/key-management/src/InMemoryKeyAgent.ts
functions like [`fromBip39Entropy()`](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/crypto/src/Bip32/Bip32PrivateKey.ts#L80) are essential for them to operate without being async, so upstream functions do not required async.
`pbkdf2` replace with `pbkdf2Sync`
- functions using `fromBip39Entropy()` can remove `await`
> feat: remove async from fromBip39Entropy

- packages/wallet/src/Wallets/util.ts
`isValidSharedWalletScript` is required on the ui side to hide some of the settings options.
> [lw-10539] export isValidSharedWalletScript util

- packages/e2e/local-network/scripts/setup-new-delegator-keys.sh
- packages/e2e/local-network/scripts/start.sh
Applied bb219b69c2 (from `conway-era` branch) to:
1. reduce merge conflict chances;
2. immediately take advantage from it in `master` branch as well.
> LW-10555 Reduce the initial delay in local-network from one to half epoch

- packages/cardano-services/src/Program/options/common.ts
- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/src/Program/programs/types.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/Program/programs/httpServer.test.ts
- packages/cardano-services/test/Program/services/pgboss.test.ts
- packages/cardano-services/test/util/validators.test.ts
Dba cache and cardano node configuration options are specific of the provider-server, but working LW-10739 I noticed they can be useful for other services.
Moved the options to common options section.
> LW-10739 Make db cache and cardano node config common options

- packages/core/src/Cardano/types/Cip1854ExtendedAccountPublicKey.ts
- packages/core/src/Cardano/types/index.ts
- packages/core/test/Cardano/types/Cip1854ExtendedAccountPublicKey.test.ts
Add a new `Cip1854ExtendedAccountPublicKey` type that encodes CIP 1854 extended public keys in bech32 following CIP 5 specification.
> feat: create Cip1854ExtendedAccountPublicKey core type

- packages/cardano-services/src/util/TypeormProvider/TypeormProvider.ts
- packages/cardano-services/src/util/createTypeormDataSource.ts
- packages/cardano-services/test/util/TypeormProvider.test.ts
SRE reported some not accurate health check.
Added a query in the `healthCheck` method.
Fixed an unhandled error which was making rxjs to exit the program.
> LW-10816 Improve typeORM provider health check

- packages/core/src/Serialization/Common/CborSet.ts
- packages/core/src/Serialization/TransactionWitnessSet/Redeemer/Redeemers.ts
- packages/core/test/Serialization/TransactionWitnessSet/VkeyWitness.test.ts
Witness set properties were not preserving original CBOR encoding upon re-serialization.
CborSet and Reedemers types now implement a cache mechanism.
CborSet and Redeemers now preserve their CBOR encoding unless changed.
> fix(core): cbor encoding of witnessSet is now preserved upon re-serialization

- nix/cardano-services/deployments/default.nix
This PR promotes the chain-history service separation through the rest of the environments. It was already added to staging and dev-pre* I  manually deployed the dev-mainnet contained in this PR. 
NOTE: This PR blocks the release of @cardano-sdk/cardano-services@0.28.12 . I did not consider the patch when I started testing and merging this work. If there are concerns with the overlapping work this can be made configurable.
The separation included here is low risk as it uses existing infra, just isolating one service to its own resources.
> chore: enable chain-history dev-main*

- .github/workflows/k6-web-socket.yaml
Newly added `workflow_dispatch` workflow are not shown in the `Actions` tab unless merged in the default branch.
Added an empty skeleton just to make it appear on the website, next I can select the right branch... etc...
> LW-10842 Add the web socket load test GHA skeleton to make it appear on the website

- nix/cardano-services/deployments/default.nix
Enable asset projector in remaining dev envs to give time to initialise before enabling typeORM asset provider
> chore: enable asset projector in remaining dev envs

- .github/workflows/std.yml
A follow-up to PR #1350
We missed a [failing check](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/9939246371/job/27453458427).
Correct the attr path of the new devshell in `std.yml` – it’s the default one now.
_n/a_
> chore(ci): correct how `std.yml` enters the devshell

- .gitignore
- nix/local/envs.nix
- nix/local/kubeconfig/eu-central-1
- nix/local/kubeconfig/us-east-1
- nix/local/kubeconfig/us-east-2
Now kubeconfig files are being copied to git ignored directory to avoid untracked changes and it no longer depends on `~/.aws/credentials` configuration
> chore: remove kubeconfig dependency on ~/.aws/credentials

- packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
This PR fixes a broken unit test that mints using plutus scripts with ledger devices.
> test(wallet): fix failling plutus script mint unit test for ledger devices

- packages/hardware-ledger/src/LedgerKeyAgent.ts
- packages/hardware-ledger/src/transformers/certificates.ts
- packages/hardware-ledger/src/transformers/tx.ts
- packages/hardware-ledger/src/transformers/votingProcedures.ts
- packages/hardware-ledger/test/testData.ts
- packages/hardware-ledger/test/transformers/certificates.test.ts
- packages/hardware-ledger/test/transformers/votingprocedures.test.ts
- packages/key-management/src/types.ts
- packages/key-management/src/util/stubSignTransaction.ts
- packages/key-management/test/util/stubSignTransaction.test.ts
- packages/util/src/index.ts
- packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
Signing a vote proposal with Ledger HW device returns MissingVKeyWitnessesUTXOW.
This was due to attempting to sign with DRep key hash which is not supported.
Compare wallet DRep key hash to voter DRep key hash. If they are match, sign with `VoterType.DREP_KEY_PATH`
> Fix lw-10852 Ledger hw sign voting proposals

- nix/cardano-services/deployments/default.nix
Increase asset-projector memory to avoid OOM kill
> chore: increase asset-projector mem

- packages/e2e/src/util/util.ts
- packages/wallet/src/services/ProviderTracker/ProviderStatusTracker.ts
- packages/wallet/test/services/ProviderTracker/ProviderStatusTracker.test.ts
simple-delegation-rewards e2e test started failing due to transaction not withdrawing all rewards. Issue was exposed after the websocket networkInfo provider was implemented and activated for the e2e tests, making responses instant (as opposed to slower HTTP requests). Wallet syncStatus updates were debounced causing the syncStatus not to update in case of many bursting requests, effectively causing the TxBuilder to consider the providers synced.
updates the pending requests observable to emit any pending requests updates immediately, while debouncing only non-pending updates
> fix(wallet): tx not withdrawing all rewards

- packages/cardano-services/src/Asset/TypeOrmNftMetadataService.ts
- packages/cardano-services/src/Asset/TypeormAssetProvider/TypeormAssetProvider.ts
TypeormAssetProvider creates a query runner per asset in 'getAssets' call. It can be up to 100 assets per call, which creates a lot of query runners.
LW-11038
This fix makes it use a single query runner.
> fix(cardano-services): use a single QueryRunner/connection for getAssets

- nix/cardano-services/deployments/default.nix
ATM asset-provider-server is unstable.
Disabling it in all `dev` environments; it should be tests in `staging-preprod`.
> chore: disable asset-provider-server in all dev envs

- nix/cardano-services/deployments/default.nix
We do not need submitapi on sanchnet, setting "USE_SUBMIT_API=false " to make sure
> chore: disable submitapi sanchonet

- packages/web-extension/src/walletManager/util.ts
We're always including both staking and payment scripts, even if staking witness is not required
> fix(web-extension): do not include staking script if not required in the tx

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
Now https://github.com/input-output-hk/cardano-db-sync/issues/1571 is solved we need to add the same distinction in SDK.
Changed the query accordingly.
> LW-11106 Add distinction between committe with or without script

- .github/workflows/std.yml
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/e2e/src/util/util.ts
- packages/e2e/test/wallet_epoch_3/PersonalWallet/conwayTransactions.test.ts
LW-11110
DbSyncChainHistoryProvider will crash if it encounters an AlwaysAbstain or AlwaysNoConfidence vote delegation certificate.
If drep_hash is null, check the value of `drep_view` which will indicate in which of the 2 scenarios we are in.
> fix(cardano-services): drep_hash can be null when delegating to abstain or no confidence

- packages/cardano-services/src/util/TypeormService/TypeormService.ts
> fix: remove redundant, uninitialized logger from TypeormService

- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/src/cip30.ts
- packages/wallet/src/types.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/wallet/test/integration/cip30mapping.test.ts
- packages/web-extension/src/observableWallet/util.ts
Our CIP-30 `getUnusedAddresses` implementation currently always returns an empty array. Particular DApps require wallets to use a freshly created address, as such we must enable this feature in our CIP-30 implementation.
BaseWallet now implements a new `getNextUnusedAddress` method, which tries to find and track the next unused wallet, it does this by first listing all known addresses, picking the address with the highest derivation index and checking whether this is an empty address or not, if it is an unused address, it returns this address, otherwise, it generates a new unused address, adds it to the tracked addresses and returns it. This guarantees that we are always tracking our next unused address if it is ever requested.
- BaseWallet implementes a new  `getNextUnusedAddress` method …
> feat!: add a new function to generate and track unused addresses in ObservableWallets

- Dockerfile
- packages/cardano-services/.env.test
- packages/cardano-services/README.md
- packages/cardano-services/package.json
- packages/cardano-services/src/Asset/TypeOrmNftMetadataService.ts
- packages/cardano-services/src/Program/programs/pgBossWorker.ts
- packages/cardano-services/src/Program/services/pgboss.ts
- packages/cardano-services/src/Program/services/postgres.ts
- packages/cardano-services/src/util/TypeormProvider/TypeormProvider.ts
- packages/cardano-services/src/util/TypeormService/TypeormService.ts
- packages/cardano-services/src/util/createTypeormDataSource.ts
- packages/cardano-services/test/Program/services/pgboss.test.ts
- packages/cardano-services/test/util/TypeormService.test.ts
- packages/projection-typeorm/src/createDataSource.ts
- packages/projection-typeorm/test/createDataSource.test.ts
- yarn.lock
> fix: no migrations on worker and provider startup

- packages/e2e/test/long-running/shared-wallet-delegation-rewards.test.ts
- packages/e2e/test/wallet_epoch_0/SharedWallet/simpleTx.test.ts
- packages/e2e/test/wallet_epoch_3/SharedWallet/delegation.test.ts
- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/src/types.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/web-extension/src/observableWallet/util.ts
The base wallet currently have a updateWitness method that adds signatures to a given transaction, however, this method does not preserve the original CBOR, we must modify this method to correctly preserve CBOR of the transaction.
Modify updateWitness to take the CBOR of the transaction, add signatures to it, and return the transaction with the new signatures encoded as CBOR.
> feat!: replace updateWitness with addSignatures in observable wallet

- packages/hardware-ledger/src/transformers/certificates.ts
- packages/hardware-ledger/test/transformers/certificates.test.ts
Self drep `Ledger.DRepParamsType.KEY_PATH` was used when mapping VoteDelegation certificate.
That is wrong, we have to pass the drep key hash, otherwise the ledger device will always calculate the DRep as our own, instead of the target one.
VoteDelegation certificate should map drep to `DRepParamsType.KEY_HASH`.
> fix(hardware-ledger): delegate vote drep is a hash not key path

- packages/ogmios/src/ogmiosToCore/tx.ts
- packages/ogmios/test/ogmiosToCore/block.test.ts
- packages/ogmios/test/ogmiosToCore/testData.ts
[LW-11243](https://input-output.atlassian.net/browse/LW-11243)
Byron transaction fee is calculated using the cbor size.
In the absence of cbor from the projected block, the fee cannot be calculated.
The code assumed cbor is present all the time.
This code was merged from the `conway-era` branch.
Use `0` fee if the cbor is not available to use for calculation.
[LW-11243]: https://input-output.atlassian.net/browse/LW-11243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ogmios): cannot calculate tx fee for byron block without cbor

- packages/ogmios/src/ogmiosToCore/tx.ts
Mainnet projection crashes with `InvalidStringError: Invalid string: "expected length '64', got 128"` because it encounters a Byron tx with signatures map that have different length key (128 instead of the expected 64)
Our signatures key validation only supports praos txes
We are not currently using signatures at all. Safe to ignore for the time being.
> fix(ogmios): ignore byron signatures in ogmios mapper

- packages/cardano-services/test/util/TypeormService.test.ts
- packages/core/src/CardanoNode/types/CardanoNodeErrors.ts
- packages/core/src/CardanoNode/util/cardanoNodeErrors.ts
- packages/core/test/CardanoNode/util/cardanoNodeErrors.test.ts
- packages/e2e/test/wallet_epoch_3/PersonalWallet/conwayTransactions.test.ts
- packages/ogmios/src/CardanoNode/queries.ts
- packages/wallet/src/Wallets/BaseWallet.ts
The latest version of the node changed priorities on the types of errors it reports, we were retrying some transactions that we weren't suppose to. We are now handling properly the new types of errors.
- Added to our retry exception list of errors `CredentialAlreadyRegisterd` and `DrepAlreadyRegistered`
- Added a timeout in the TypeormSerivce tests that tests re-connection to allow the service to reconnect to the datasource.
> test(e2e): fix flaky conway era e2e tests

- packages/core/src/CardanoNode/types/CardanoNodeErrors.ts
- packages/core/src/CardanoNode/util/cardanoNodeErrors.ts
- packages/core/test/CardanoNode/util/cardanoNodeErrors.test.ts
- packages/ogmios/src/CardanoNode/queries.ts
- packages/wallet/src/Wallets/BaseWallet.ts
We still have some flakiness:
https://github.com/input-output-hk/cardano-js-sdk/actions/runs/10387686363/job/28761702839?pr=1421
#1414 follow up
Added retry strategy for missing exceptions
> LW-11264 Add to BaseWallet re-submit exceptions UnknownCredential and DrepNotRegistered errors

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
cip30 getUsedAddresses was throwing when no used addresses were found
cip30 getUsedAddresses now returns an empty array instead of throwing
> fix(wallet): cip30 getUsedAddresses now returns an empty array if no used addresses are found

- packages/core/src/Cardano/Address/PointerAddress.ts
- packages/core/test/Cardano/util/addressesShareAnyKey.test.ts
- packages/core/test/Serialization/TransactionBody/TransactionOutput.test.ts
- packages/projection-typeorm/src/operators/storeStakePools.ts
- packages/projection/src/operators/Mappers/certificates/withCertificates.ts
- packages/projection/test/InMemory/storeStakePools.test.ts
- packages/projection/test/operators/Mappers/certificates/withCertificates.test.ts
- packages/projection/test/operators/Mappers/certificates/withStakeKeyRegistrations.test.ts
- packages/util-dev/src/Cip19TestVectors.ts
There are invalid output addresses on mainnet, referencing stake credentials by invalid stake pointer address. These references consist in part of a absolute slot number, which is a location on the blockchain of the stake key registration certificate for that key. The issue arose during indexing when we've found large slot numbers that overflow the JS `Number.MAX_SAFE_INTEGER`.
The mainnet transaction hash, whose first transaction output that caused this issue is: `9a47e091709e4fe1a8ba1291bc8cfd0c0ed0bb9220688b3ccfad5f2d961e8d8e`
We change the variable length encoding/ decoding for pointer addresses to use `bigint` for `Cardano.Pointer.slot` type to support correct serialization for pointer addresses.
We have exclusively changed the `Cardano.Pointer.slot` type to `bigint` and not the …
> Bug: support overflowing pointer address slots with constraints

- packages/core/src/TxMetadata/cip20.ts
- packages/core/src/TxMetadata/index.ts
- packages/core/test/TxMetadata/cip20.test.ts
- packages/util/src/index.ts
- packages/util/src/string.ts
- packages/util/test/string.test.ts
When fixing https://github.com/input-output-hk/lace/issues/978 I discovered there's more we can be doing in the SDK to help applications produce compliant CIP-20 transaction metadata. I've fixed the immediate issue here https://github.com/input-output-hk/lace/pull/1379, but there were no tests and I would rather put energy into removing the responsibility from Lace altogether.
https://github.com/input-output-hk/lace/blob/e877d4668c02ae647ed39293f05233d0ac513663/packages/cardano/src/wallet/lib/get-auxiliary-data.ts#L1-L74
N.B. This implementation is based on https://cips.cardano.org/cip/CIP-20 which defines a format to support multi-entry messages, whereas Lace currently only has good support for single entry (with a split to handle > 64 bytes). To adopt this solution we will be …
> Feature: CIP20 helper functions + StringUtils

- packages/cardano-services/src/Projection/prepareTypeormProjection.ts
While supporting @will-break-it on LW-10737 we realized about this issue.
Loaded the mapper.
> fix(cardano-services): correctly load Mapper.withGovernanceActions

- nix/cardano-services/deployments/default.nix
Follow up of #1447
Enabled the new projector on all the `dev` and `staging` environments.
> chore: enable walle_api_projector on all dev and staging environments

- .github/workflows/test-deploy-e2e.yaml
- packages/e2e/src/scripts/generate-dotenv.sh
- packages/e2e/src/util/util.ts
- Some recently introduced change (fast / slow network distinction, hot reload, etc.) wasn’t reflected on e2e against deployed environments: this broken them.
- Sometimes we need to choose a specific cluster to run the tests against: we need to add this option.
- Fixed the impacted files
- Added the cluster dedicated CI input
- Reduced the amount of confirmation required in slow networks
> LW-11310 Add option to choose target cluster for deployed environments e2e tests

- packages/tx-construction/src/computeScriptDataHash.ts
- packages/tx-construction/test/computeScriptDataHash.test.ts
PPViewHashesDontMatch issue when submitting the transaction with AsHash datum
https://github.com/IntersectMBO/cardano-ledger/blob/c183a0b037c943a387f5a450b5354e56eb1aa598/eras/conway/impl/cddl-files/conway.cddl#L340
> fix: update hashScriptData for conway

- .github/workflows/std.yml
- nix/cardano-services/deployments/default.nix
- packages/cardano-services/src/Asset/TypeormAssetProvider/TypeormAssetProvider.ts
`asset-provider` has memory consumption issues.
Optimized `TypeormAssetProvider.getAssets` method.
- Used `withDataSource` rather than `withQueryRunner`.
- Aggregated the SQL queries to get all `assetInfo`s and `nftMetadata`s with one query (one query for each: two new queries) rather than performing one query for each `assetInfo` or `nftMetadata`.
- Parallelized the functions to get `assetInfo`s, `nftMetadata`s and `tokenMetadata`s.
Before the change, `TypeormAssetProvider.getAssets` was performing several SQL queries on a singe `QueryRunner` _trying to parallelize them_ through `Promise.all`.
A `QueryRunner` represent a PostgreSQL client. Even if [pg](https://www.npmjs.com/package/pg) allows to perform multiple queries before the response for the first one is received, under the wood, …
> LW-11068 Asset provider OOM fix attempt

- packages/cardano-services/src/Asset/TypeormAssetProvider/TypeormAssetProvider.ts
- packages/cardano-services/src/InMemoryCache/InMemoryCache.ts
- packages/cardano-services/src/InMemoryCache/WarmCache.ts
- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/src/TxSubmit/NodeTxSubmitProvider.ts
- packages/cardano-services/src/util/TypeormProvider/TypeormProvider.ts
- packages/cardano-services/test/Asset/TypeOrmNftMetadataService.test.ts
- packages/cardano-services/test/Asset/TypeormAssetProvider/TypeormAssetFixtureBuilder.ts
- packages/cardano-services/test/Asset/TypeormAssetProvider/TypeormAssetProvider.test.ts
- packages/cardano-services/test/Handle/TypeOrmHandleProvider.test.ts
- packages/cardano-services/test/InMemoryCache/InMemoryCache.test.ts
- packages/cardano-services/test/InMemoryCache/SharedTests.ts
- packages/cardano-services/test/InMemoryCache/WarmCache.test.ts
- packages/cardano-services/test/StakePool/TypeormStakePoolProvider/TypeormStakePoolProvider.test.ts
- packages/cardano-services/test/TxSubmit/NodeTxSubmitProvider.test.ts
- packages/cardano-services/test/util/TypeormProvider.test.ts
- packages/e2e/src/factories.ts
This PR aims to improve health check API response times  (to under 1 sec) by pre-fetching and caching the underlying service health.
Generating on-demand health check responses is taking a long time. 
We want to aggregate and cache underlying health check responses in the background. On-demand health check API responses will be generated from the always-warm cache.
We implemented a WarmCache logic by extending InMemoryCache.
One cache can be shared with multiple providers.
Now, various providers will be aggregating health checks independently in the background.
> feat(cardano-services): improve health check response times by aggregating and caching

- packages/e2e/test/web-extension/extension/background/cip30.ts
- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
- packages/web-extension/src/messaging/BackgroundMessenger.ts
- packages/web-extension/src/messaging/NonBackgroundMessenger.ts
- packages/web-extension/src/messaging/remoteApi.ts
- packages/web-extension/src/messaging/types.ts
it happens due to unknown reason, possibly due to the recently introduced BFCache feature in chromium)
also log runtime.lastError when port disconnects
Do not throw if port re-connects within 10s (normally it takes ~1s)
BREAKING CHANGE: change return type of createWalletApi callbacks. 
See [changes in lace](https://github.com/input-output-hk/lace/commit/01b8b6e86faa2cf83a3ccc100277fa6f05840793)
> fix: expect disconnects during remote api method call

- packages/e2e/test/web-extension/extension/background/cip30.ts
- packages/e2e/test/web-extension/extension/background/supplyDistributionTracker.ts
- packages/e2e/test/web-extension/extension/background/walletManager.ts
- packages/web-extension/src/walletManager/walletManager.ts
- packages/web-extension/test/walletManager/walletManager.test.ts
Using Lace, activeWallet and activeWalletId observables emit independently. In order to synchronise you need to know which emits first.
Emitting both from the same observable eliminates potential race conditions
LW-11406
> feat(web-extension)!: emit wallet and id from activeWallet$

- packages/cardano-services/src/Program/options/index.ts
- packages/cardano-services/src/Program/options/providers.ts
- packages/cardano-services/src/Program/programs/providerServer.ts
- packages/cardano-services/src/Program/programs/types.ts
- packages/cardano-services/src/cli.ts
- packages/cardano-services/test/cli.test.ts
For most providers, we have multiple implementations.
This feature allows us to pick which implementation we run inside the related HttpService.
This PR is based on `blockfrost` branch and can be merged directly into the `master` once the `blockfrost` branch is merged.
It's backward compatible by respecting or throwing errors in case of conflict with the old env vars or configs.
For example,
- if `USE_SUBMIT_API` is set to any value, setting the `TX_SUBMIT_PROVIDER` value will throw an error.
> feat(cardano-services): implement provider selection based on env variables and config

- README.md
- package.json
- packages/cardano-services/scripts/tx-cbor.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/DbSyncChainHistoryProvider.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
- packages/e2e/test/wallet_epoch_3/SharedWallet/delegation.test.ts
I noticed a problem about certificates type; while fixing it I noticed some other issues... while working on them I discovered some more else... that chain originated this misc fixes PR.
Discovered issues.
- We are using an hard-code `Cardano.CredentialType.KeyHash` while building certificates.
- We are using a not correct sorting for transaction inputs.
- We are sorting `collateralReturn`: it's useless to sort an _up to 1 element_ array.
- We are using an hard-coded `null` for `poolParameters` while building `PoolRegistrationCertificate`s; this makes `getCertificatesByType` to not pick given certificates.
- We are loading assets for `collateralReturn` as it was an output but assets for it are stored in `multi_assets_descr` column not in `ma_tx_out` table.
- Computed the `stakeCredential` …
> LW-11425 Misc fixes

- packages/wallet/src/services/AddressTracker.ts
- packages/wallet/src/services/ChangeAddress/DynamicChangeAddressResolver.ts
- packages/wallet/src/services/util/sortAddresses.ts
- packages/wallet/test/services/AddressTracker.test.ts
- packages/wallet/test/services/ChangeAddress/DynamicChangeAddressResolver.test.ts
- packages/wallet/test/services/ChangeAddress/testData.ts
User used Lace to manage his ada handle settings ( a lot of those ) and Eternl wouldn't show his balance anymore ( because of the discovery gap )
Then after quite a few transactions, it suddenly used a newly created (index 557) address for change and sticked to it for the following 3 transactions.
Lace is probably picking the newly created unused address as change address sometimes. This changes makes sure it always picks the same addresses per reward accounts and its always the lowest derivation index.
> fix(wallet): dynamicChangeResolver gives preference to lower derivation indices

- packages/cardano-services/src/Projection/ProjectionHttpService.ts
- Projectors often have negative heath check.
- Investigation conclusions:
1. the default health check timeout is 1 minute;
2. even if _unusual_ it is _normal_ for networks to take longer than 1 minute to produce a new block.
Increased the default health check timeout to 3 minutes;
> LW-11492 Fix attempt for projector health check

- packages/projection-typeorm/test/operators/storeHandles/ownership.test.ts
- packages/projection-typeorm/test/operators/storeHandles/util.ts
- packages/projection/src/operators/Mappers/withHandles.ts
- packages/util-dev/src/chainSync/data/cip68-handle-problem.json
- packages/util-dev/src/chainSync/index.ts
Found some suspicious logs in mainnet handle provider:
```
[TypeOrmHandleProvider] silverfox has no associated address, which could be the result of a double mint.
```
It [is a valid handle](https://cexplorer.io/asset/asset1lafyy7j4kaa09wrsg34jgz3r3d60ryr3daqth2/tx#data) that was minted just once by upgrading a cip25 handle into cip68.
The bug is caused by [withHandles mapper](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/projection/src/operators/Mappers/withHandles.ts#L163-L164) overwriting handles found in outputs with the ones found in mint (burned), therefore setting address to `null`.
> fix: correctly set handle owner when handle is upgraded to cip68

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
Now that addresses in address$ observable are guaranteed to be sorted, we no longer need to sort it here.
> fix(wallet): remove redundant sort on getChangeAddres

- compose/common.yml
- packages/e2e/local-network/Dockerfile
- packages/e2e/local-network/scripts/install.sh
External dependencies versions in SDK are behind the ones used in deployed environments.
- Bump `cardano-node` to `v9.1.1`
- Bump `db-sync` to `v13.5.0.1`
> LW-11501 Bump cardano-node to v9.1.1 and db-sync to v13.5.0.1

- packages/e2e/test/k6/scenarios/wallets.test.js
wallets K6 test does not fail regardless of how many requests fail.
P95, P99 response times seem to include the failed response times, which are usually fast.
abort k6 wallets test if too many failed requests
- show that test is failing, otherwise failed requests are considered successful with small response time
- To save on K6 VUh
-
> test(e2e): abort k6 wallets test if too many failed requests

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/util.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
Data present in sanchonet let us to discover some minor issues on something we did early about Conway era.
Details in the commits.
> LW-9675 conway era fixes

- packages/core/src/Serialization/TransactionBody/Value.ts
- packages/core/test/Serialization/TransactionBody/Value.test.ts
It looks like the author meant to do:
if(reader.peek() === UNSIGNED_INT) { reader.readUInt() }
instead of
if(reader.peek() === UNSIGNED_INT) { reader.readInt() }
> Fix signed/unsigned bug in Value.fromCBOR

- packages/e2e/test/wallet_epoch_0/PersonalWallet/byron.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/metadata.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/mint.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/multiAddress.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/phase2validation.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/plutusTest.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/txChainHistory.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/unspendableUtxos.test.ts
- packages/e2e/test/wallet_epoch_0/SharedWallet/simpleTx.test.ts
Out e2e test often uses a piec of code like following
```
await wallet.submitTx(signedTx);
// Search chain history to see if the transaction is there.
const txFoundInHistory = await firstValueFrom(
wallet.transactions.history$.pipe(
map((txs) => txs.find((tx) => tx.id === signedTx.id)),
filter(isNotNil),
take(1)
)
);
```
next perform the checks.
The problem is this code is based only on `ChainHistoryProvider` while some checks are performed on `Observable`s sometimes based on other providers (`AssetProvider`, `UtxoProvider`, etc...).
This is a source of flakiness as check result may be dependent on which provider completes earlier.
Substitute given piece of code (where required) with `submitAndConfirm` utility, which internally also waits for the wallet to be settled, i.e. all the …
> test(e2e): reduce test flakiness

- packages/e2e/test/k6/scenarios/wallets.test.js
Wrong method name causes test to not run this query:
```
TypeError: Object has no member 'stats'
at syncWallet (file:///github/workspace/packages/e2e/test/k6/scenarios/wallets.test.js:248:15(92))
at default (file:///github/workspace/packages/e2e/test/k6/scenarios/wallets.test.js:273:74(47))
```
> test(e2e): fix wrong method name for stake pool stats

- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/ChainHistoryBuilder.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/mappers.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/queries.ts
- packages/cardano-services/src/ChainHistory/DbSyncChainHistory/types.ts
- packages/cardano-services/test/ChainHistory/DbSyncChainHistoryProvider/mappers.test.ts
SRE discovered two queries causing high CPU workload on DB server.
- Optimized the `redeemer` query hoisting the sort at Node.js level.
- Removed meaningless `ORDER BY` for collateral outputs query.
- Removed some dead code I detected while working on this
> LW-11640 Fix queries performances issue

- packages/dapp-connector/src/WalletApi/Cip30Wallet.ts
- packages/dapp-connector/src/injectGlobal.ts
- packages/dapp-connector/test/WalletApi/Cip30Wallet.test.ts
- packages/dapp-connector/test/injectGlobal.test.ts
Add support for:
- inject api under custom key, instead of wallet name
- configure the supported extensions when constructing the Cip30Wallet object
- deviation from standard cip30 api. Currently overrides getCollateral to return empty array when no collaterals are found
> feat(dapp-connector): custom inject key, extensions and api

- packages/dapp-connector/src/WalletApi/Cip30Wallet.ts
Some DApps expect experimental.on/off functions to exist.
For now, adding them as dummy implementation.
> feat(dapp-connector): add dummy on/off methods to Cip30Wallet

- packages/hardware-ledger/src/LedgerKeyAgent.ts
We want to remove the need from the user to pick the ledger device on every use, the Ledger key agent will now first check if there is a connected authorized ledger device to use, if not it will prompt the user to select/authorize one.
> feat(hardware-ledger): the Ledger key agent now picks the first avaialble device if possible

- packages/cardano-services-client/src/WebSocket.ts
`CardanoWsClient` is calling `timeoutID.unref()`, but it is not supported on browsers.
Check if it is a function before calling it to make it being called only under **Node.js**.
> fix(cardano-services-client): do not call timout id unref in browsers

- .github/workflows/k6-web-socket.yaml
- packages/e2e/test/k6/scenarios/web-socket.test.js
We need to test the scenario of multiple connected `CardanoWsClient`s in idle.
Upgraded the `ws-server` load test to be configured for this scenario.
> LW-11659 Add wallet idle time to ws-server load test

- packages/cardano-services-client/src/WebSocket.ts
Working with @AngelCastilloB on LW-11610 we noticed that the web socket activity can't be inspected in the network tab of devTools.
Increased web socket client log verbosity.
> LW-11610 Increase ws client logging verbosity

- packages/core/src/Asset/NftMetadata/types.ts
- packages/core/test/Asset/NftMetadata/fromMetadatum.test.ts
- packages/projection-typeorm/src/operators/storeUtxo.ts
- packages/projection-typeorm/test/operators/storeNftMetadata.test.ts
- packages/projection/src/operators/Mappers/withUtxo.ts
- packages/projection/test/operators/Mappers/withUtxo.test.ts
- packages/util-dev/src/chainSync/data/cip68-witness-datum-problem.json
- packages/util-dev/src/chainSync/index.ts
Some CIP-68 NFT metadata is not being projected LW-11682
Some IPFS URIs are not recognized LW-11673
Some CIP-68 NFTs are created by using transaction witness datum instead of inline datum.
Mappers will now look up witness datum by hash.
https://input-output.atlassian.net/browse/LW-11682
> fix: project cip68 metadata when datum resides in tx witness

- nix/cardano-services/deployments/backend.provider.nix
- nix/cardano-services/deployments/chain-history.nix
Updating backend and chain-history health endpoings to use `/ready`
> chore: update enpoint to ready

- packages/wallet/src/services/TipTracker.ts
- packages/wallet/test/services/TipTracker.test.ts
More ledger-tip requests per polling interval occur.
WHAT: replaced `delay` operator with `auditTime` operator, which starts a timer once the first isSettled$ emission, and emits the last value, ignoring previous ones.
WHY: isSettled$ observable emissions triggered ledger-tip requests, delayed by pollingInterval.
Flapping isSettled$ caused multiple requests to be done, because the flapping was delayed.
Throttling is in place for the case where the ledger-tip request is not resolved yet.
> fix(wallet): one ledger-tip req per pollInterval

- packages/wallet/package.json
- packages/wallet/src/persistence/pouchDbStores/PouchDbCollectionStore.ts
- packages/wallet/src/persistence/pouchDbStores/PouchDbStore.ts
- packages/wallet/src/persistence/pouchDbStores/pouchDbWalletStores.ts
- packages/wallet/test/persistence/pouchDbStores.test.ts
- yarn.lock
PouchDbCollectionStore.setAll used to
1. delete all documents
2. insert the new documents
This approach has a problem that when step 2. fails, all documents from db are gone and not re-created. For some collections such as transactions or utxo this is not a problem, because it can recover, but for it is a big problem for WalletRepository, because there is no way to recover the wallets if they are lost.
LW-11760
This fix updates setAll to perform the following steps:
1. delete *only* the documents that are intended to be deleted
2. upsert all new documents
> fix(wallet): preserve pouchdb collection documents when bulkDocs fails

- packages/cardano-services-client/src/TxSubmitProvider/TxSubmitApiProvider.ts
TxSubmitApiProvider was trying to deserialize the transaction CBOR as transaction body, which was causing a failure in deserialization.
TxSubmitApiProvider now deserializes the CBOR as a transaction when computing the tx hash.
> fix(cardano-services-client): txSubmitApiProvider now computes the tx id correctly

- packages/cardano-services-client/src/HttpProvider.ts
- packages/cardano-services-client/test/HttpProvider.test.ts
HttpProvider is implemented as a Proxy object, which is currently not compatible with SDK's web-extension messaging utilities that are checking exposed/underlying object properties with 'in' operator
LW-11796
This commit has 2 fixes:
- do not throw an error when trying to access an undefined property of an object
- return 'true' with with 'in' operator for defined properties
> fix(cardano-services-client): comply HttpProvider with 'normal' Object behavior

- packages/wallet/src/services/DelegationTracker/DelegationTracker.ts
Delegation tracker was recently updated to follow voting delegations in addition to stake delegations, but the transactions were filtered only for staking certificates.
Include voting certificates in the transaction filter.
> fix(wallet): include voteDelegation certs in delegationTracker

- packages/wallet/src/global.d.ts
- packages/wallet/src/services/WalletUtil.ts
- packages/wallet/test/services/WalletUtil.test.ts
Input resolver currently can only resolve inputs as long as they are part of the UTXO set of the wallet. However if we want to resolve inputs that were already spent (I.E to render tx history), we need to also search in TX history.
Input resolver now searches tx history.
> feat(wallet): input resolver now searches TX history if input cant be found in current UTXO set

- packages/core/src/Asset/types/AssetInfo.ts
- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/src/services/AssetsTracker.ts
- packages/wallet/test/PersonalWallet/load.test.ts
- packages/wallet/test/PersonalWallet/shutdown.test.ts
- packages/wallet/test/services/AssetsTracker.test.ts
Everytime a new instance of base wallet the asset tracker will fetch metadata for all known assets in the transaction history. His could be thousands of assets on an active wallet, which could amount to 10 of thousand of fetches during the day.
The asset tracker now will fetch new asset metadata only for assets that are present in balance, and only every 7 days (+-2 days of variance to avoid re-fetching them all at once)
> feat: asset tracker now uses local cache before fetching asset metadata

- packages/e2e/test/wallet_epoch_0/PersonalWallet/nft.test.ts
it was setting version as part of the map under <asset_name> but the spec specifies that it has to be under the '721' map
> test(e2e): fix cip25 v2 test

- packages/wallet/src/Wallets/BaseWallet.ts
Explain why it is not necessary to call setStatInitialized() for TrackedDrepProvider.
> Explain why it is not necessary to call setStatInitialized() for TrackedDrepProvider.

- packages/e2e/test/web-extension/extension/background/walletManager.ts
- packages/web-extension/src/walletManager/walletManager.ts
- packages/web-extension/src/walletManager/walletManager.types.ts
- packages/web-extension/test/walletManager/walletManager.test.ts
required for Lace pouchdb->extension storage data migration
> refactor(web-extension)!: make StoresFactory async

- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/src/services/UtxoTracker.ts
- packages/wallet/test/services/UtxoTracker.test.ts
wallets with large # of utxo were performing poorly, because every subscription to utxo ran some computation
notably, each call to input resolver was running `firstValueFrom(utxo.available$)` which triggered a series of computations
> perf(wallet): cache mapped addresses and utxo

- packages/cardano-services-client/src/TxSubmitProvider/BlockfrostTxSubmitProvider.ts
- packages/cardano-services-client/test/TxSubmitProvider/BlockfrostTxSubmitProvider.test.ts
it has to be binary, otherwise Blockfrost responds with 400
this bug wasn't caught initially because we're not using BlockfrostTxSubmitProvider in our e2e test suite
LW-11695
> fix(cardano-services-client): correct blockfrost tx submit request body

- packages/core/src/util/transactionSummaryInspector.ts
- packages/core/test/util/transactionSummaryInspector.test.ts
Withdrawals are a type of "own input", which must be accounted for when computing the wallet spent amount
txSummaryInspector should factor in `withdrawals` when calculating the spent `coins`.
`coins = ownOutputs - (ownInputs + ownWithdrawals)
> fix(core): include withdrawals in txSummary spent coins

- packages/tx-construction/src/tsconfig.json
- packages/tx-construction/src/tx-builder/TxBuilder.ts
- packages/util-rxjs/src/index.ts
- packages/util-rxjs/src/poll.ts
- packages/util-rxjs/test/poll.test.ts
- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/src/services/AssetsTracker.ts
- packages/wallet/src/services/DelegationTracker/DelegationTracker.ts
- packages/wallet/src/services/DelegationTracker/RewardAccounts.ts
- packages/wallet/src/services/DelegationTracker/RewardsHistory.ts
- packages/wallet/src/services/DrepInfoTracker.ts
- packages/wallet/src/services/SupplyDistributionTracker.ts
- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/src/services/UtxoTracker.ts
- packages/wallet/src/services/util/index.ts
- packages/wallet/src/services/util/pollProvider.ts
- packages/wallet/src/types.ts
- packages/wallet/test/PersonalWallet/load.test.ts
- packages/wallet/test/integration/CustomObservableWallet.test.ts
- packages/wallet/test/services/AssetsTracker.test.ts
- packages/wallet/test/services/DelegationTracker/DelegationTracker.test.ts
- packages/wallet/test/services/DelegationTracker/RewardAccounts.test.ts
- packages/wallet/test/services/DelegationTracker/RewardsHistory.test.ts
- packages/wallet/test/services/util/pollProvider.test.ts
- packages/web-extension/src/observableWallet/util.ts
> fix: fatal provider errors

- packages/cardano-services-client/src/TxSubmitProvider/BlockfrostTxSubmitProvider.ts
- packages/cardano-services-client/src/blockfrost/BlockfrostClient.ts
- packages/cardano-services-client/src/blockfrost/BlockfrostProvider.ts
- packages/e2e/src/factories.ts
- packages/e2e/test/providers/TxSubmitProvider.test.ts
- packages/util-dev/src/createStubHandleProvider.ts
- packages/util-dev/src/index.ts
BaseWallet has some logic based on TxSubmissionError. Therefore we need to map errors from BlockfrostTxSubmitProvider
Map 2 most important errors:
- ValueNotConserved
- OutsideOfValidityInterval
**Note: for completeness we should follow-up with more error mappings, see [BaseWallet implementation](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/wallet/src/Wallets/BaseWallet.ts#L719-L724)**
LW-11912
> fix: map Blockfrost ValueNotConserved and OutsideOfValidityInterval errors

- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
The BaseWallet will now always use its own context to resolve inputs before using the given input resolver
> feat(wallet): input resolver dependency is now composed with context input resolver

- packages/e2e/test/web-extension/extension/ui.ts
- packages/web-extension/README.md
- packages/web-extension/src/walletManager/SigningCoordinator/KeyAgentFactory.ts
- packages/web-extension/src/walletManager/SigningCoordinator/SigningCoordinator.ts
- packages/web-extension/test/walletManager/SigningCoordinator.test.ts
Bip32Ed25519 was refactored to synchronous methods by hoisting sodium await to top level in #1558, which makes it difficult to use SigningCoordinator without top level await
> refactor(web-extension)!: make KeyAgentFactory methods async

- packages/cardano-services-client/src/ChainHistoryProvider/BlockfrostChainHistoryProvider.ts
- packages/cardano-services-client/test/ChainHistoryProvider/BlockfrostChainHistoryProvider.test.ts
- packages/wallet/src/services/AssetsTracker.ts
- packages/wallet/test/services/AssetsTracker.test.ts
1. BlockfrostChainHistoryProvider used to incorrectly slice all-address transactions array
2. We have recently updated BaseWallet to operate with partial tx history. AssetsTracker is fetching AssetInfo only for assets found in tx history. Therefore it wouldn't fetch asset info for assets currently in balance.
1. This commit changes the behavior to apply the limit per address in order to not miss any transactions. The more addresses you have, the higher the limit. e5559501bf7748c3daf589b6764a608f6b58c870
2. Fetch asset info for tokens in balance e49a4ea5d8b33f866665596d8895fd4970dded27
> fixes: blockfrost chain history transactions limit per address & balance token info

- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/src/services/TipTracker.ts
- packages/wallet/test/services/TipTracker.test.ts
See LW-12174
See commit b75b9dced7ae6dae8d0683159d36e24c3413196e
Tested in Lace, seems to work well
> feat(wallet): add optional pollController$ dependency LW-12174

- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
Initial transactions fetch window reduced to top 10 down from 1 month
> feat(wallet): initial transactions fetch window reduced to top 10 down from 1 month

- packages/hardware-ledger/src/LedgerKeyAgent.ts
There are multiple `Failed to execute 'releaseInterface' on 'USBDevice'` issues reported by sentry.
Further investigation confirmed that `hw-transport-webusb` package also attaches a disconnect event listener while creating a Ledger transport, so we might end up trying to handle disconnection multiple times. 
Wrap `transport.close` call in the on disconnect handler with a try catch clause.
> fix: [lw-12138] handle disconnected ledger wallet error

- packages/cardano-services-client/src/RewardsProvider/BlockfrostRewardsProvider.ts
- packages/cardano-services-client/test/RewardProvider/BlockfrostRewardsProvider.test.ts
Pool id is not mapped in the response of blockfrost rewards providers requests.
> fix: [lw-12169] map pool id in blockfrost rewards provider response

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
there was a race condition that made cip30 transaction chaining flaky:
- we see a new block, we fetch transactions
- we see transaction on chain and we do the following in parallel:
- we fetch utxos
- we remove transaction from inFlight$
- spent utxo becomes 'available' again for a brief period, until utxos are fetched
if getUtxos is called after wallet sees transaction on chain,
but before utxos are fetched from provider, it would resolve spent utxo
await for wallet to settle before resolving utxo
> fix(wallet): await for wallet settle before resolving cip30 utxo LW-12197

- packages/wallet/src/services/TransactionsTracker.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
initially fetched trasactions were returned in asc order, but sliced from array start when we actually want the latest txes
> Fix/sort initially fetched txes - LW-12194

- packages/web-extension/src/storage/persistentCacheStorage/persistentCacheStorage.ts
Allow for storing complex data like bigints, Maps, etc.
Use `toSerializableObject` and `fromSerializableObject` when seting and geting items from the storage
> feat: equip persistent cache with better data serialisation

- packages/cardano-services-client/src/blockfrost/BlockfrostProvider.ts
Blockfrost 404s are already handled in the [fetchSequentially util](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/cardano-services-client/src/blockfrost/util.ts#L52), but these errors are still logged in the [request method of BlockfrostProbider class](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/cardano-services-client/src/blockfrost/BlockfrostProvider.ts#L49) via logger.error.
Change log level to `debug` instead of `error` in case this is blockfrost not found error.
> fix: [lw-12235] handle expected blockfrost 404 errors

- .github/workflows/continuous-integration-blockfrost-e2e.yaml
- .github/workflows/continuous-integration-e2e.yaml
- .github/workflows/continuous-integration-side-tests.yaml
- .github/workflows/continuous-integration-unit-tests.yaml
- .github/workflows/git-checks.yaml
- .github/workflows/post_integration.yml
- .github/workflows/release.yaml
- .github/workflows/test-deploy-e2e.yaml
The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-01
https://github.com/actions/runner-images/issues/11101
> ci: update ubuntu action runner image to 22.04

- packages/web-extension/src/storage/persistentCacheStorage/persistentCacheStorage.ts
In order to make sure the cache metadata collection tracks properly all the stored cache items it is required for read and write operations to be performed in sequence. Otherwise, some parallel metadata writing might cause data loss.
Making read and write operations atomic by maintaining a queue of those operations and performing next one only if previous one finished.
> feat: make metadata update operation atomic in persisten cache storage

- .github/dependabot.yml
- Dependabot is great but it would be better to batch and group by update types for easier handling.
- It's also currently using a non-standard commit type.
- Enabling the **Grouped security updates** option bundles everything together, which is not ideal since it then requires accepting major breaking changes alongside critical security patches :-1: 
Group updates into non-breaking security, non-breaking version, and breaking, on a weekly batch cycle @ 6AM UTC Monday morning. Also set prefix to conform with Conventional Commits, Angular types.
There will be a slight delay on being alerted to critical issues, however I can't see a way to isolate critical updates to use an instantaneous strategy, plus there is a way to be alerted via email.
> build: configure dependabot

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
See [LW-12322](https://input-output.atlassian.net/browse/LW-12322)
Remove auto-collateral management logic and related tests.
[LW-12322]: https://input-output.atlassian.net/browse/LW-12322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(wallet): remove auto-collateral management logic [LW-12322]

- compose/common.yml
- packages/cardano-services-client/src/DRepProvider/BlockfrostDRepProvider.ts
- packages/cardano-services-client/test/DRepProvider/BlockfrostDRepProvider.test.ts
In the inception of governance DReps ids were bech32 encoded using CIP105 spec.
Later a new standard, CIP129 because the defacto bech32 way to encode DRep ids
Blockfrost supports querying for specific DReps using both standards.
We should aim to use a single format throughout the code, to avoid confusion and to be consistent
> refactor(cardano-services-client): use CIP129 when querying dreps/:drepId - LW-12316

- packages/web-extension/src/messaging/index.ts
- packages/web-extension/src/messaging/util.ts
Make bg script detection more robust
Firefox runs background script in a hidden page,
so it has a window object.
Check for `runtime.getBackgroundPage` function which exists in firefox only on background page.
> feat(web-extension): detect bg script when on firefox - LW-11944

- packages/util/src/environment.ts
- packages/wallet/src/services/util/connectionStatusTracker.ts
- packages/web-extension/src/messaging/index.ts
- packages/web-extension/src/messaging/util.ts
isBackgroundProcess is needed in both web-extension and wallet packages.
Hoist it to the utils package
> refactor!: hoist isBackgroundProcess script detection to utils package [LW-12130]

- packages/key-management/src/InMemoryKeyAgent.ts
- packages/key-management/src/types.ts
- packages/key-management/src/util/ownSignatureKeyPaths.ts
- packages/key-management/src/util/stubSignTransaction.ts
- packages/key-management/test/InMemoryKeyAgent.test.ts
- packages/key-management/test/util/ownSignaturePaths.test.ts
- packages/key-management/test/util/stubSignTransaction.test.ts
Lace currently fails to identify when it is being requested to sign a transaction on behalf of a NativeScript where it's signature may be one of the signatures required by that NativeScript.
Evaluate NativeScript(s) used as witnesses to determine keypaths which must be used to sign (if any).
Added the capability described above to enhance Lace's functionality with CIP-30 dApps that leverage NativeScripts.
> NativeScript signing

- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/wallet/test/services/TransactionsTracker.test.ts
Transaction can get stuck as 'inFlight' if they are rejected due to invalidHereAfter, this change will make it so the base wallet now throws before ever queuing the transaction.
- BaseWallet throws before ever queuing the transaction if the transaction is already expired.
> fix(wallet): base wallet will now immediately throw if tx is outside validity interval

- packages/core/src/Serialization/TransactionBody/TransactionBody.ts
- packages/core/test/Serialization/TransactionBody/TransactionBody.test.ts
- packages/hardware-ledger/src/LedgerKeyAgent.ts
- packages/hardware-ledger/src/transformers/txOut.ts
- packages/hardware-ledger/src/types.ts
- packages/hardware-ledger/test/testData.ts
- packages/hardware-ledger/test/transformers/certificates.test.ts
- packages/hardware-ledger/test/transformers/tx.test.ts
- packages/hardware-ledger/test/transformers/txOut.test.ts
- packages/hardware-trezor/src/TrezorKeyAgent.ts
- packages/hardware-trezor/src/transformers/txOut.ts
- packages/hardware-trezor/src/types.ts
- packages/hardware-trezor/test/testData.ts
- packages/hardware-trezor/test/transformers/tx.test.ts
- packages/hardware-trezor/test/transformers/txOut.test.ts
- packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
We had a round-trip issue in our hardware wallet output mappings. This PR introduces a change to check for the actual format on the raw CBOR and passes as as context to the type mappers
Analyze the raw CBOR to detect the output format and pass it as part of the transformation context.
> LW-12624: Fix output mapping on hardware wallets

- packages/cardano-services-client/src/HandleProvider/handleHttpProvider.ts
- packages/cardano-services-client/src/HttpProvider.ts
- packages/cardano-services-client/test/HandleProvider/handleHttpProvider.test.ts
- packages/cardano-services-client/test/HttpProvider.test.ts
In order to investigate the high resolution calls rate we want to add a debug parameter to calls performed by Lace.
Added an unused `check_handle` parameter to resolution calls.
> LW-12668 Add a debug parameter to handle resolution call

- .github/workflows/std.yml
Our build breaks if the last `yarn install` that updates the lock file was done on a non-`x86_64-linux` machine.
Unfortunately, `.yarn/plugins/yarn-plugin-nixify.cjs` then removes Linux-specific dependencies from `yarn-project.nix`, adding ARM64 Darwin-specific ones, and a Nix build can no longer succeed on Linux.
Additionally, some integration has broken between `std-action` and [nixbuild.net](https://nixbuild.net/), so now we trigger the build manually there. After that, it works.
Reject PRs without `@esbuild/linux-x64@npm` in `yarn-project.nix`.
* Here you can see an example of a **failed run** based on a broken commit (b81902d61ff438c4f5ab76763ebe8e00ab8d4993): [actions/runs/14400727809/job/40385721936](https://github.com/input-output-hk/cardano-js-sdk/actions/runs/14400727809/job/4038 …
> fix: reject PRs without `@esbuild/linux-x64@npm` in `yarn-project.nix` & fix the NixBuild.net integration

- packages/input-selection/src/GreedySelection/GreedyInputSelector.ts
- packages/input-selection/src/GreedySelection/util.ts
- packages/input-selection/src/LargeFirstSelection/LargeFirstInputSelector.ts
- packages/input-selection/src/LargeFirstSelection/index.ts
- packages/input-selection/src/RoundRobinRandomImprove/index.ts
- packages/input-selection/src/change.ts
- packages/input-selection/src/index.ts
- packages/input-selection/src/util.ts
- packages/input-selection/test/InputSelectionPropertyTesting.test.ts
- packages/input-selection/test/LargeFirstSelection/LargeFirstSelection.test.ts
- packages/input-selection/test/change.test.ts
- packages/input-selection/test/util/index.ts
Some users with complex wallets that have hundreds (or even thousand) of UTxOs with small amounts can make our current input selection strategy fail due to selecting more inputs than max allowed, we need alternative input selection strategies for such wallets
This PR introduces large first input selection, which reduces the number of outputs needed per transaction.
> feat(input-selection): add large first input selection strategy

- packages/cardano-services-client/src/HandleProvider/KoraLabsHandleProvider.ts
- packages/cardano-services-client/test/util.ts
- packages/cardano-services/src/Handle/TypeOrmHandleProvider.ts
- packages/cardano-services/test/Handle/HandleHttpService.test.ts
- packages/cardano-services/test/TxSubmit/NodeTxSubmitProvider.test.ts
- packages/core/src/Provider/HandleProvider/types.ts
- packages/tx-construction/test/tx-builder/TxBuilder.test.ts
- packages/wallet/src/services/HandlesTracker.ts
- packages/wallet/test/services/HandlesTracker.test.ts
We need to make Lace able to resolve ADA handle bitcoin addresses.
- Changed the `HandleResolution` type to include the bitcoin address.
- Added the new resolution to `KoraLabsHandleProvider`.
> LW-12881 Make KoraLabsHandleProvider compliant with bitcoin

- packages/wallet/src/cip30.ts
- packages/wallet/test/integration/cip30mapping.test.ts
> fix(wallet): resolve only the own signed portions of the witness set

- packages/key-management/src/util/ownSignatureKeyPaths.ts
- packages/key-management/test/util/ownSignaturePaths.test.ts
- packages/wallet/jest.config.js
- packages/wallet/jest.setup.js
- packages/wallet/src/Wallets/BaseWallet.ts
- packages/wallet/src/cip30.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/wallet/test/hardware/ledger/LedgerKeyAgent.test.ts
- packages/wallet/test/hardware/trezor/TrezorKeyAgent.test.ts
- packages/wallet/test/hardware/utils.ts
- packages/wallet/test/integration/cip30mapping.test.ts
Our integration with hardware wallets and transactions with native scripts had a few gaps/bugs that was preventing us from signing correctly multiSig transactions with ledger or trezor.
> fix: fix native script singing

- packages/crypto/src/Bip32Ed25519.ts
- packages/crypto/src/blake2b-hash.ts
- packages/crypto/src/strategies/CmlBip32Ed25519.ts
- packages/crypto/src/strategies/SodiumBip32Ed25519.ts
- packages/e2e/test/handle/KoraLabsHandleProvider.test.ts
- packages/e2e/test/local-network/register-pool.test.ts
- packages/e2e/test/long-running/cache-invalidation.test.ts
- packages/e2e/test/wallet_epoch_0/PersonalWallet/cip30WalletApi.test.ts
- packages/key-management/src/Bip32Account.ts
- packages/key-management/test/Bip32Account.test.ts
- packages/tx-construction/src/tx-builder/initializeTx.ts
- packages/wallet/src/services/PublicStakeKeysTracker.ts
- packages/wallet/test/PersonalWallet/methods.test.ts
- packages/wallet/test/services/PublicStakeKeysTracker.test.ts
LW-12941
We want to make Bip32Account async to improve rendering performance on client side
> feat: make bip32account async

- packages/e2e/package.json
- packages/e2e/test/handle/KoraLabsHandleProvider.test.ts
- yarn.lock
The `KoraLabsHandleProvider` test directly calls the public API, so they are subjected to flakiness due to network errors or handles metadata changes.
Used a mock.
> LW-13058 Fix flaky test in koralabs handle provider

- packages/crypto/src/blake2b-hash.ts
- packages/crypto/src/strategies/CmlBip32Ed25519.ts
- packages/crypto/src/strategies/SodiumBip32Ed25519.ts
setImmediate is not available in browser environments, and we dont really need it.
Remove calls to setImmediate
> fix(crypto): remove setImmediate from async calls

- packages/e2e/test/wallet_epoch_0/PersonalWallet/metadata.test.ts
- packages/tx-construction/src/output-validation/outputValidator.ts
- packages/tx-construction/src/output-validation/types.ts
- packages/tx-construction/test/output-validation/outputValidator.test.ts
`OutputValidator.validateOutput` returns incorrect minimum coin quantity for outputs to Byron address
LW-13214
See commit messages
> fix: use actual address size for min value computation

- packages/crypto/package.json
- packages/tx-construction/package.json
- yarn.lock
The `crypto` and `tx-construction` packages have `npm` as dependencies, which seems incorrect. Moreover, it causes some problems in the lace-platform. The `npm` gets installed in the `node_modules` of the project and then when running `npx` from the terminal it resolves the npm from the `node_modules` instead of the one installed globally. As a consequence npm v9 gets used instead of v10.
> chore: remove npm from dependencies

- packages/core/src/Serialization/TransactionBody/TransactionBody.ts
- packages/core/test/Serialization/Transaction.test.ts
The Conway-era [CDDL specification](https://github.com/intersectmbo/cardano-ledger/tree/master/eras/conway/impl/cddl-files) mandates that optional maps and arrays must be either non-empty or omitted entirely.
However, this rule does not apply to required fields. The transaction outputs array is a required field and must always be present, even if it contains no outputs. The SDK was incorrectly omitting this array when it was empty, leading to invalid transactions. This fix ensures the outputs array is always serialized to maintain compliance.
Additionally, an incorrect falsy check on the TTL value was preventing ttl: 0 from being serialized into core types. Because 0 is a valid TTL, the check has been corrected to properly handle this value.
> fix(core): fix canonical serialization when outputs are empty

- packages/hardware-ledger/src/LedgerKeyAgent.ts
At this point payload was already converted to hex. It's not bytes anymore
> fix(hardware-ledger): fix signData payload size calculation

- packages/core/src/util/transactionSummaryInspector.ts
- packages/core/test/util/transactionSummaryInspector.test.ts
Return resolved inputs as part of transactionSummaryInspector. It is needed when displaying transaction details inputs.
> feat(core): return resolved inputs from summary inspector - [LW-12769]
